### ISSUE TITLE
[feat] apache like sorting header

### ISSUE THREAD

**Issue by quazardous** [coderaiser/cloudcmd#101]
* **Version** (v6.0.0): 
* **Node Version** v0.10.42: 
* **OS** Linux cloudy.localdomain 4.7.6-100.fc23.x86_64 #1 SMP Mon Oct 3 18:15:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux: 
* **Browser name/version**: All

great job !

It would be so sweet if you could add sorting capability to the columns' headers

**Comment by coderaiser** [comment]
What a great idea for a pull request :), it should be added to [readify](https://github.com/coderaiser/readify) first and then adapted to ui of `Cloud Commander` with something [like this](https://gist.github.com/coderaiser/7fbdbad2b8d8594433b34f87dab9fc04).

**Comment by quazardous** [comment]
yes indeed :)
I'm a poor PHP dev... node JS is like another planet lol
but I'll give it a shot if I find some time !

So to start I've to open an issue in [readify](https://github.com/coderaiser/readify) ?

**Comment by coderaiser** [comment]
To start you can think about types of sorting you need, and way of handling options in `readify`.

**Comment by coderaiser** [comment]
With help of [readify v4.1.0](https://github.com/coderaiser/readify/releases/tag/v4.1.0) sorting can be added to [restafary get](https://github.com/coderaiser/node-restafary/blob/master/lib/fs/get.js).
This is how `Cloud Commander` gets directory data via `http`.
`URL` can look like:

```
/api/v1/fs?sort=size&order=desc
```

**Comment by coderaiser** [comment]
With [restafary v2.1.0](https://github.com/coderaiser/node-restafary/releases/tag/v2.1.0) possible to sort listings by `name`, `size` and `date` with `ascending` and `descending` order.

What is left is: adding ui part which will call [loadDir](https://github.com/coderaiser/cloudcmd/blob/2769ac2ef55df88061655637ddc94b6df7f10f2a/client/client.js#L61).

UI part can contain such code for switching of sorting:

```js
$0.onclick = function() {
    const {textContent} = this;
    if (textContent.includes('▾'))
        return this.textContent = textContent.replace('▾', '▴');
    
    if (textContent.includes('▴'))
        this.textContent = textContent.replace('▴', '▾');
}
```

**Comment by quazardous** [comment]
@coderaiser yes :p but not right now... maybe next week...

**Comment by coderaiser** [comment]
Landed in [v6.2.0](https://github.com/coderaiser/cloudcmd/releases/tag/v6.2.0).

**Comment by quazardous** [comment]
bravo !

**Comment by quazardous** [comment]
hi just updated to 6.2.2
chromium : I can see the headers with arrows but files are not sorted at all.
firefox@fedora : got errors when I click on headers: TypeError: event.path is undefined

**Comment by coderaiser** [comment]
Looks like `event.path` supported by Chrome only and [listeners](https://github.com/coderaiser/cloudcmd/blob/ce7210ea8b57cc7c8fba73b8cdc03bf7437e4aaf/client/listeners.js#L62) should be changed.

**Comment by coderaiser** [comment]
Fixed with d3caa9d. Landed in [v6.3.0](https://github.com/coderaiser/cloudcmd/releases/tag/v6.3.0).

**Comment by quazardous** [comment]
cool ! thx !
but cannot update : got a `pipe-io` install error. I'll try in a while hoping it will be fixed...

**Comment by coderaiser** [comment]
@quazardous what kind of error?
Could you please try:
```sh
npm cache clean
npm r cloudcmd -g
npm i cloudcmd -g
```

**Comment by quazardous** [comment]
```
/usr/bin/cloudcmd -> /usr/lib/node_modules/cloudcmd/legacy/bin/cloudcmd.js
/usr/bin/cloudcmd+ -> /usr/lib/node_modules/cloudcmd/bin/cloudcmd.js
npm WARN unmet dependency /usr/lib/node_modules/block-stream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream-ignore requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream-npm requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/glob requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/npmconf requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/tar requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined

```

**Comment by coderaiser** [comment]
Try to update `npm` with:

```sh
npm i npm -g
```
and repeat removing and installing of `Cloud Commander`.

Does it works now?

**Comment by quazardous** [comment]
```
[root@cloudy ~]# npm i npm -g
npm http GET https://registry.npmjs.org/npm
npm http 200 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm/-/npm-4.1.2.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-4.1.2.tgz
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
npm WARN unmet dependency /usr/lib/node_modules/block-stream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream-ignore requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream-npm requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/glob requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/npmconf requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/tar requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm@4.1.2 /usr/lib/node_modules/npm
```
seams my distro is broken for npm :/

**Comment by quazardous** [comment]
got errors on removing / reinstalling npm...

Will try to reinstall it in a while... thx for helping

**Comment by quazardous** [comment]
ok removed all node_module folder and reinstall all from scratch..

sorting is working for files but not for folders

**Comment by coderaiser** [comment]
> sorting is working for files but not for folders

Yes, this is the way it works in `Total Commander` and `Midnight Commander`.
Anyways when you sort by `size` you can not know what size of a directories (it is very time expensive operation).

**Comment by quazardous** [comment]
I'm **not** trying to fix a **bug** in `Total Commander` :)

I do think trying to reach the first or the last modified directory is important in a file explorer software (especially with large directory).

The size of a directory is technically the size of the `inode`. So I can bear "non sized" directories (inode size means only we have lots of sub inodes wich is useless in real life)... It's the way it goes with `ls -lS` (with same size, directories are `name` sorted).

So **NOT** honoring the `date` or `size` sorting for directories **IS** a bug (imo)...

**Comment by quazardous** [comment]
@coderaiser are you using `cloudcmd` in a daily basis ? because I am :)

**Comment by coderaiser** [comment]
@quazardous yes, I am :).

So what type of sorting do you want? I just trying to use [principle of least surprise]( https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

In regular sorting directories comes first and then files. How you want deal with sorting by date? Do not divide `files` and `folders` by type? 

> The size of a directory is technically the size of the inode. So I can bear "non sized" directories (inode size means only we have lots of sub inodes wich is useless in real life)... It's the way it goes with ls -lS (with same size, directories are name sorted).

If size of every directory the same, what purpose of such sorting?

**Comment by quazardous** [comment]
`POLA` is good but for me astonishment comes when clicking on `date` does **not** sort folders by `date` but by `name`. I wonder "Is it a bug ?".

Splitting folders and files like `total commander` is fine and is often more handful than the other way.

- sorting by `name`: folders sorted by `name` + files sorted by `name`
- sorting by `size`: folders sorted by `size`,`name` + files sorted by `size`,`name` (so for folders it will be always by `name`)
- sorting by `date`: folders sorted by `date`,`name` + files sorted by `date`,`name`

**Comment by coderaiser** [comment]
> - sorting by `name`: folders sorted by `name` + files sorted by `name`
> - sorting by `size`: folders sorted by `size`,`name` + files sorted by `size`,`name` (so for folders it will be always by `name`)
> - sorting by `date`: folders sorted by `date`,`name` + files sorted by `date`,`name`

As I understand the only thing you would like to change is sorting directories by date, it could be done with a flag in config ([like it works in Total Commander](http://beerpla.net/2008/10/11/how-to-sort-folders-the-same-way-as-files-in-total-commander/)), when directories sorted by `date` comes first and files sorted by `date` next.

**Comment by quazardous** [comment]
Great !

**Comment by coderaiser** [comment]
@quazardous we can provide one more flag in [readify](https://github.com/coderaiser/readify/blob/81092fb1a47ad1aac1947d7d02e3f32921ab3c8b/lib/readify.js#L162) for sorting directories as files. When enabled it can sort directories by `name` in `ascending` and `descending` order and by `date`.

What you think about a pull request :)?

**Comment by quazardous** [comment]
I will definitly try ;p but I have to handle a little blast of work now :/

**Comment by coderaiser** [comment]
Added ability to sort directories by date in readify [v4.1.5](https://github.com/coderaiser/readify/releases/tag/v4.1.5).
