### ISSUE TITLE
Prefix causing 404s

### ISSUE THREAD

**Issue by rabidlogic** [coderaiser/cloudcmd#102]
I'm running this in Docker, but I don't really see how that would affect it. 

Cloudcmd Version: v6.2.1
Node Version: v7.4.0 (building off node:latest container)
OS: Linux 7ac52767e0c2 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 GNU/Linux
Browser Name/Version: Mozilla Firefox 45.6.0

I've been playing around with Cloud Commander as a solution for a project at work. However, the environment I need to use it in has cloudcmd sitting behind a proxy, which has required me to use a prefix. 

Testing at home, I have been using the prefix=catdog

Initially, I have a join 404ing in the console

http://localhost:8000/catdog/catdog/join:/modules/format-io/lib/format.js:/modules/rendy/lib/rendy.js:/modules/execon/lib/exec.js:/modules/jonny/lib/jonny.js:/modules/emitify/dist/emitify.min.js:/modules/currify/dist/currify.min.js:/modules/itype/dist/itype.min.js:common/util.js:common/cloudfunc.js:client/dom.js:client/events.js:client/rest.js:client/load.js:client/notify.js:client/storage.js:client/files.js:client/dialog.js:client/client.js:client/buffer.js:client/listeners.js:client/key.js:client/directory.js:/join/join.js

(Note how the prefix is duplicated in that instance)

Let me know if you need any additional information.

**Comment by coderaiser** [comment]
Thank you fixed with a13e8c4. Landed in [v6.2.2](https://github.com/coderaiser/cloudcmd/releases/tag/v6.2.2).
