### ISSUE TITLE
vi and nano don't work correctly

### ISSUE THREAD

**Issue by gkovacs** [coderaiser/cloudcmd#103]
* **Version** (v6.2.2): 
* **Node Version** v6.9.2: 
* **OS** macOS Sierra 10.12.2 (Darwin gezamac 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64): 
* **Browser name/version**: Chrome 55

When I open the terminal in the browser interface and type vi, it gives me the error

```
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
```

nano likewise does not work, but just hangs and doesn't give me any error. I assume this is an issue in the implementation of the terminal emulator

**Comment by coderaiser** [comment]
The thing is `console` used in `Cloud Commander` it is not a terminal emulator, it is something like [repl](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop).

`vim` and `nano` can not work in a `repl` they need real terminal emulator. The most popular is [pty.js](https://github.com/chjj/pty.js/) but it is not really supported and requires compilation step during installation (which can be a problem on `windows`).

If you find terminal emulator without native code (javascript only) or a simple cross platform solution to use in `Cloud Commander` let me know. I'll try to integrate it :).

**Comment by coderaiser** [comment]
Related to #43.

**Comment by coderaiser** [comment]
Added support of a terminal in [v6.7.0](https://github.com/coderaiser/cloudcmd/releases/tag/v6.7.0).
