### ISSUE TITLE
Menus don't show on Chrome Linux

### ISSUE THREAD

**Issue by wernight** [coderaiser/cloudcmd#104]
* **Version** (`cloudcmd -v`): Dockerzired `coderaiser/cloudcmd:6.3.0-alpine`
* **OS** (`uname -a` on Linux): Ubuntu 14.04
* **Browser name/version**: Chrome 56.0.2924.76 beta (64-bit)

What doesn't work, does nothing, and normally works on other OSes:

 - Right click a file
 - Left click on bottom menu item
 - Function keys

**Comment by coderaiser** [comment]
1. Try to use `coderaiser/cloudcmd:6.3.1-alpine`
2. Can you open developer tools: is console or network panel has some errors?

**Comment by wernight** [comment]
This bug was already in version 5. Tried 6.3.1 same.

There is two 404 errors:

    GET https://example.com/[object%20Object]/join:/modules/format-io/lib/format.js:/modules/rendy/lib/rendy.js:/modules/emitify/dist/emitify.js:/modules/execon/lib/exec.js:/modules/jonny/lib/jonny.js:lib/util.js:lib/cloudfunc.js:lib/client/dom.js:lib/client/events.js:lib/client/rest.js:lib/client/load.js:lib/client/notify.js:lib/client/storage.js:lib/client/files.js:lib/client/dialog.js:lib/client.js:lib/client/buffer.js:lib/client/listeners.js:lib/client/key.js:lib/client/directory.js:/join/join.js

    GET https://example.com/[object%20Object]/join:/modules/format-io/lib/format.js:/modules/rendy/lib/rendy.js:/modules/emitify/dist/emitify.js:/modules/execon/lib/exec.js:/modules/jonny/lib/jonny.js:lib/util.js:lib/cloudfunc.js:lib/client/dom.js:lib/client/events.js:lib/client/rest.js:lib/client/load.js:lib/client/notify.js:lib/client/storage.js:lib/client/files.js:lib/client/dialog.js:lib/client.js:lib/client/buffer.js:lib/client/listeners.js:lib/client/key.js:lib/client/directory.js:/join/join.js

(note that https:// is handled outside of cloudcmd)

**Comment by wernight** [comment]
Oh I looks a bit more and it looks like there is some Chrome extension that is messing up CloudCmd.

[UPDATING ONCE I FOUND WHICH]

**Comment by coderaiser** [comment]
Yes, most likely the case is the cache.

**Comment by coderaiser** [comment]
Related to #102.
