### ISSUE TITLE
Missing cloudcmd.js when running in docker since version 6.5.0

### ISSUE THREAD

**Issue by wildgers** [coderaiser/cloudcmd#107]
Chrome reports missing cloudcmd.js. With the missing js file I can only browse files. No editing or other functions are working.

I am falling back to version 6.4.0, which is working for me.

Chrome error:
`GET http://localhost:8000/cloudcmd.js 
(index):150 Uncaught ReferenceError: CloudCmd is not defined
    at (index):150`

* **Version** (`cloudcmd -v`): 6.5.0-6.5.4
* **Node Version** `node -v`: -
* **OS** (`uname -a` on Linux): -
* **Browser name/version**: Google Chrome 56.0.2924.87
* **Used docker command**: docker run -v ~:/root -v /:/mnt/fs -t -p 8000:8000 coderaiser/cloudcmd

**Comment by coderaiser** [comment]
Thank you, fixed with fa58e1f, landed in [v6.5.5](https://github.com/coderaiser/cloudcmd/releases/tag/v6.5.5).

**Comment by quaywin** [comment]
I'm still got this bug when run command `npm start`
