### ISSUE TITLE
Can't upload files when root dir is empty, menu doesn't appear

### ISSUE THREAD

**Issue by mikefaraponov** [coderaiser/cloudcmd#108]
* **Version** v6.6.0: 
* **Node Version** v7.6.0: 
* **OS** Linux dd4d2d911b92 4.4.0-63-generic #84~14.04.2-Ubuntu SMP Mon Feb 13 11:04:58 UTC 2017 x86_64 Linux: 
* Chrome *:

**Comment by coderaiser** [comment]
Thank you, fixed with 79c1716. Landed in [v6.6.1](https://github.com/coderaiser/cloudcmd/releases/tag/v6.6.1).
