### ISSUE TITLE
Embedded filepicker Key for Commercial Application

### ISSUE THREAD

**Issue by surjar** [coderaiser/cloudcmd#109]
Hi,
Few queries regarding filepicker:
   1. As filepicker is a commercial service, can I use it in our application as it is, without any subscription with filestack.com.
  2. Is there any config, by which I can disable/remove filepicker from cloudcmd?
  3. Can I use the embedded filepicker key inside cloudcmd/json/modules.json as it is? Are there any limitations, like storage limits, etc. if I use the embedded key as it is for our commercial application?

Thanks,
Suri

**Comment by coderaiser** [comment]
1. You definitely should have your own commercial subscription in filestack.com.
2. There is no such config now. But it is a great idea for a pull request :).
3. To use `filepicker` in commercial application you should provide your own key in [json/modules.json](https://github.com/coderaiser/cloudcmd/blob/db2a58ca44af1728454d11deade8f2e45423f313/json/modules.json#L54).

**Comment by coderaiser** [comment]
Landed in [v6.9.0](https://github.com/coderaiser/cloudcmd/releases/tag/v6.9.0).

**Comment by surjar** [comment]
Thanks!
