### ISSUE TITLE
cloudcmd.js not found with own docker build

### ISSUE THREAD

**Issue by MikeMichel** [coderaiser/cloudcmd#110]
Hi,

when i clone this repo and build my own container the browser complains about missing cloudcmd.js. This sounds like #107 but we are at 6.8.0. For whatever reason the official container is working.

cheers,

Mike

**Comment by coderaiser** [comment]
You should `build` client side first to get things working.

```sh
git clone https://github.com/coderaiser/cloudcmd
cd cloudcmd
npm install
npm run build
npm run docker
```

**Comment by MikeMichel** [comment]
thx, i will check
