### ISSUE TITLE
Is it possible to support "sudo" & "aria2" in the app, deployed in heroku?

### ISSUE THREAD

**Issue by ttestdock** [coderaiser/cloudcmd#112]
* **Version** (`cloudcmd -v`): In heroku, using this command will show "spawn cloudcmd ENOENT".
* **Node Version** `node -v`: v7.7.3
* **OS** (`uname -a` on Linux): Linux b62fb3dc-11d4-471c-a043-80060df45d80 3.13.0-112-generic
* **Browser name/version**: chrome

**Comment by coderaiser** [comment]
Heroku uses cut versions of Ubuntu. Here is a [list of applications available on the stacks of heroku](https://devcenter.heroku.com/articles/stack-packages).

`cloudcmd.heroku.com` it is just a demo, it is updating on every push, so environment cleaned up on every change in repo.

Looks like Heroku does not provide `sudo` and `aria2`.
