### ISSUE TITLE
Feature? Drag & Drop on split window

### ISSUE THREAD

**Issue by banholzer** [coderaiser/cloudcmd#114]
Dropping local files to remote machine works fine. Is there a possibility to drag and drop inside the webgui (split) to copy/move files on the remote machine?

**Comment by coderaiser** [comment]
What a great idea for a pull request :). I think it could be added in [client/listeners.js](https://github.com/coderaiser/cloudcmd/blob/110e421dd65d34a60b0c15f2d9a4c43a52057993/client/listeners.js#L17) in a similar way as a `dragndrop` function.

**Comment by coderaiser** [comment]
Landed in [v6.12.0](https://github.com/coderaiser/cloudcmd/releases/tag/v6.12.0).
