### ISSUE TITLE
Unable to start Gritty Terminal

### ISSUE THREAD

**Issue by Olivier6767** [coderaiser/cloudcmd#115]
* **Version** (`cloudcmd -v`): 6.12.0
* **Node Version** `node -v`: 6.6.0
* **OS** (`uname -a` on Linux): Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
* **Browser name/version**: Safari iOS / Chrome 58.0 (Windows 10) / IE 11 (Windows 10)
* **Used Command Line Parameters**: --terminal
* **Changed Config**: 

I have installed gritty (npm i gritty -g) and have enabled the --terminal and --terminal-path '/usr/local/lib/node_modules/gritty'

The settings are saved in the config file. However I cannot find the way to open the terminal from the web page. I have the menu on the bottom but the >_~  button always open the console. 
If I hit ~ on the  keyboard it does NOT open the console.
Similarly if I hit SHIFT + ~ on the keyboard it does NOT open the  console or terminal.

How do we open the terminal ?
I would suggest that when terminal is enabled, an additional button is displayed to open the terminal.

Thanks.

**Comment by coderaiser** [comment]
Can you show me please output of command `gritty` and output of `cloudcmd` when you run it?
New button is a good idea for a pull request :).

**Comment by Olivier6767** [comment]
Here is the output of gritty: url: http://localhost:1337
Here is the output of cloudcmd: url: http://localhost:33000/
Gritty version: v1.4.14

Unfortunately I don't have the javascript skills to make this change mysef :(

**Comment by coderaiser** [comment]
If you have no messages with like this:

```sh
cloudcmd --terminal: The module '/home/coderaiser/gritty/node_modules/node-pty/build/Release/pty.node'
```

Everything is OK with your installation. Could you please try demo page: `http://cloudcmd.herokuapp.com`. Is terminal works for you?

**Comment by Olivier6767** [comment]
I tried with the demo page and cannot open temrinal either.
However I think I understand what the problem is:
On US keyboard the ~ is on a key by itself.

Picture of US Keyboard
![us-kbd](https://cloud.githubusercontent.com/assets/28684355/26050706/f29e646a-395f-11e7-97a4-2a985a0150ab.JPG)

I'm using French keyboard. the ~ is on the same key as digit 2. It must be accessed using AltGr+2 or Ctrl+Alt+2. This does NOT work on the CloudCmd web page.

Picture of French keyboard
![fren-kbd](https://cloud.githubusercontent.com/assets/28684355/26050783/4316426e-3960-11e7-830b-0e1a5c57b85d.JPG)

It would be nice if the key could be customized (in the config file) or if an additional button could be displayed.

Thanks.

**Comment by coderaiser** [comment]
Added terminal button in [v6.13.0](https://github.com/coderaiser/cloudcmd/releases/tag/v6.13.0).
