### ISSUE TITLE
F8 deletion with html dialogs off

### ISSUE THREAD

**Issue by forwov** [coderaiser/cloudcmd#117]
* **Version** (`cloudcmd -v`): v6.15.3
* **Node Version** `node -v`: v7.10.0
* **OS** (`uname -a` on Linux): Linux  4.4.0-22-generic Ubuntu x86_64 GNU/Linux
* **Browser name/version**: Chrome/59.0.3071.115(32bit)
* **Used Command Line Parameters**: 
* **Changed Config**: 

IF "HTML dialogs" is OFF (через F10), F8 acts NOT as expected while cancel button is pressed. (deletes ANYWAY) were "surprised" when deleted working site. Backups saved us that time, and do everytime :)
Just imagine somebody's reaction when misstyped F7 or F9.

**Comment by coderaiser** [comment]
Thank you and sorry for inconvenience, fixed with https://github.com/coderaiser/smalltalk/commit/43c2e400f4d15352f4d2b170ef206b2a032f219e.

Could you please tell me why are you set `html dialogs` to `off`?

**Comment by forwov** [comment]
Was just playing around with options and noticed that "weird" behaviour.

**Comment by coderaiser** [comment]
Landed in [v6.15.4](https://github.com/coderaiser/cloudcmd/releases/tag/v6.15.4).
