### ISSUE TITLE
editors bracket highlighting option in config

### ISSUE THREAD

**Issue by forwov** [coderaiser/cloudcmd#118]
It would be nice to have ability to change  bracket highlighting style through config file (color, thickness, animation maybe[css]).
If it's not planned in the nearest future could you lead to direction were this can be changed? paths? places? any hints.

**Comment by forwov** [comment]
will it be enough to change these stiles ".ace_bracket {margin: -1px 0 0 -1px;border: 1px solid rgb(192, 192, 192);}" (4 occurances) in  /usr/lib/node_modules/cloudcmd/node_modules/edward/modules/ace-builds/src-min/ace.js ? what else shoud be changed?

**Comment by coderaiser** [comment]
There is 3 editors supported by `Cloud Commander`:
- [edward](https://github.com/cloudcmd/edward) which is uses [Ace](https://ace.c9.io/)
- [dword](https://github.com/cloudcmd/dword) which is uses [codemirror](https://codemirror.net)
- [deepword](https://github.com/cloudcmd/deepword) which is uses [monaco-editor](https://github.com/Microsoft/monaco-editor).

To change bracket highlighting style in this editors you should look in themes of editors listed above.
In [codemirror](https://codemirror.net/doc/manual.html#styling) you can override `CodeMirror-matchingbracket` class to achieve your goal.
