### ISSUE TITLE
i18n inquiry

### ISSUE THREAD

**Issue by forwov** [coderaiser/cloudcmd#119]
As soon as issue #34 (2015) closed due to inactivity what 18n strategy would you use now if had some spare time. What's the best way to make translations in your humble opinion. Do you plan some? If not what would be the easyest way to add another language to the project. paths? places? any hints.

**Comment by coderaiser** [comment]
There is a couple places which should be changed if you want to add i18n:
- [index.html](https://github.com/coderaiser/cloudcmd/blob/616867b3b505030cba984de2764103ddfda96025/html/index.html)
- [config.hbs](https://github.com/coderaiser/cloudcmd/blob/9bc577a83aa4ac1430d3bd4d7193b8ce40b23496/tmpl/config.hbs)

I haven't use any strategy and plan to use none. But if you interested in i18n we can add it. Do you have any ideas about strategy we can use?
Why do you need it?

**Comment by forwov** [comment]
That's just for a friend of mine.

**Comment by coderaiser** [comment]
Do you plan to explore this topic and work on this feature? I will help if you will have some questions. But I do not have time for this now.

**Comment by forwov** [comment]
I'm interested but not very confident in javascript. Seems you use constants everywhere.

**Comment by coderaiser** [comment]
Yep,

> `const` is a signal that the identifier won’t be reassigned.

[JavaScript ES6+: var, let, or const?](https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75)

**Comment by forwov** [comment]
contact me at @bdcontrol if you wish.

**Comment by coderaiser** [comment]
@forwov you can write here if you will have some ideas.
