### ISSUE TITLE
Cloudcmd broken UI

### ISSUE THREAD

**Issue by koperkiewicz** [coderaiser/cloudcmd#120]
* **Version** (`cloudcmd -v`): v6.15.3
* **Node Version** `node -v`: v8.1.3
* **OS** (`uname -a` on Linux): Linux area69 2.6.32-042stab120.20 #1 SMP Fri Mar 10 16:52:50 MSK 2017 x86_64 x86_64 x86_64 GNU/Linux
* **Browser name/version**: Latest Google Chrome and Firefox
* **Used Command Line Parameters**: exec sudo -u root cloudcmd --port=9001 -a -u user -p password
* **Changed Config**: 

I get this broken UI when trying to use cloudcmd:

![image](https://user-images.githubusercontent.com/9249155/28015521-9a8f40ae-6570-11e7-91cf-f77fa36cd8b4.png)

It used to be fine and now out of sudden it stopped working. Tested on latest Google Chrome and Firefox.

**Comment by coderaiser** [comment]
Could you please open [console](https://developer.mozilla.org/en/docs/Tools/Web_Console) and check if there any errors?

**Comment by koperkiewicz** [comment]
There are couple errors:

`Failed to load resource: the server responded with a status of 403 (Forbidden)
:9001/join:css/reset.css:css/style.css:css/icons.css:css/help.css:css/query.css:css/supports.css Failed to load resource: the server responded with a status of 403 (Forbidden)
cloudcmd.js Failed to load resource: the server responded with a status of 403 (Forbidden)
wh1ter4bb.it/:389 Uncaught ReferenceError: CloudCmd is not defined
    at wh1ter4bb.it/:389
supports.css Failed to load resource: the server responded with a status of 403 (Forbidden)
urls.css Failed to load resource: the server responded with a status of 403 (Forbidden)`

**Comment by coderaiser** [comment]
Could you please remove current version of `Cloud Commander` with:
```
npm r cloudcmd -g
```

and install a new version `6.15.4` with

```
npm i cloudcmd -g
```

Is it helps?

**Comment by koperkiewicz** [comment]
It did not help.

**Comment by koperkiewicz** [comment]
Now I noticed that it only breaks UI on 9001 port. It is werid because I was using that port all the time and haven't got any problems.

**Comment by coderaiser** [comment]
I can't reproduce this bug. Maybe you have nginx settings, or anything else?

**Comment by forwov** [comment]
after "npm r cloudcmd -g" and installing again throwed an error (look attachment) seems with /legacy/ in path.

[log.tar.gz](https://github.com/coderaiser/cloudcmd/files/1135803/log.tar.gz)

**Comment by coderaiser** [comment]
Try to use: `npm i cloudcmd@latest -fg`

**Comment by forwov** [comment]
Thanks it worked.
