### ISSUE TITLE
Config flag to disable contact button/feature

### ISSUE THREAD

**Issue by jzaefferer** [coderaiser/cloudcmd#125]
* **Version** (`cloudcmd -v`): coderaiser/cloudcmd:7.1.0-alpine
* **Node Version** `node -v`: n/a
* **OS** (`uname -a` on Linux): n/a
* **Browser name/version**: Firefox 54
* **Used Command Line Parameters**: `--no-console --no-terminal --no-config-dialog`
* **Changed Config**: n/a

There are a few menu bar items I'd like to remove for our deployment. Setting `--no-console --no-terminal --no-config-dialog` gets me 75% of the way, but I couldn't find a toggle like that for the contact button. Would it be possible to get that added?

If yes, is there a way for me to help get that implemented?

**Comment by coderaiser** [comment]
It is a good idea for a pull request :).
You can add this option in the same way [--no-console](https://github.com/coderaiser/cloudcmd/commit/c3c008ff720f90281aea91bbd1539403bbca4fa1) was added.

**Comment by jzaefferer** [comment]
Looks like there have been a lot of structural changes since that commit. I'll try to find the new places.

**Comment by coderaiser** [comment]
No as much as it looks like, directories 'lib' and 'lib/server' renamed to 'server'. And no need to change 'client'.

**Comment by coderaiser** [comment]
Landed in [v7.2.0](https://github.com/coderaiser/cloudcmd/releases/tag/v7.2.0).
