### ISSUE TITLE
Latest Docker image broken?

### ISSUE THREAD

**Issue by anansii** [coderaiser/cloudcmd#127]
Ubuntu 16.04.LTS remote server via SSH
Docker Server Version: 17.06.0-ce

**Input:** 
docker run -t --rm -v ~:/root -v /:/mnt/fs -p 8000:8000 coderaiser/cloudcmd

**Output:**
module.js:487
    throw err;
    ^

Error: Cannot find module './sort-selectors'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/node_modules/html-minifier/node_modules/clean-css/lib/optimizer/level-1/optimize.js:4:21)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by coderaiser** [comment]
I can't reproduce. What version of `Cloud Commanderare` you using? Run
`
docker run -t --rm -v ~:/root -v /:/mnt/fs -p 8000:8000 coderaiser/cloudcmd -v
`

**Comment by coderaiser** [comment]
Just updated `cloudcmd:latest` image. Please run `docker pull coderaiser/cloudcmd` to update your local image. But before that please check version of your image.

**Comment by anansii** [comment]
Hi, I had the old image already removed, but I can confirm that it now works with the latest image. 

Thanks a lot :)

docker run -t --rm -v ~:/root -v /:/mnt/fs -p 8000:8000 coderaiser/cloudcmd -v
url: http://localhost:8000/
from coderaiser/cloudcmd
ad74af05f5a2: Pull complete
2b032b8bbe8b: Pull complete
a9a5b35f6ead: Pull complete
3245b5a1c52c: Pull complete
afa075743392: Pull complete
9fb9f21641cd: Pull complete
b1074d048a61: Pull complete
602b2c2b7041: Pull complete
54bf441dcfcb: Pull complete
71e8a98e3aeb: Pull complete
2b99913ae2af: Pull complete
cf2b7842dcce: Pull complete
Digest: sha256:6aea94f9fc486aaeff24a19593563e25b16336d903c99d37168f3d042c7af46f
Status: Downloaded newer image for coderaiser/cloudcmd:latest
v7.2.0

**Comment by coderaiser** [comment]
That is great, glad to help :).
