### ISSUE TITLE
Contextmenu and overlays not working in Firefox

### ISSUE THREAD

**Issue by jzaefferer** [coderaiser/cloudcmd#128]
* **Version** (`cloudcmd -v`): coderaiser/cloudcmd:7.2.0-alpine
* **Node Version** `node -v`: n/a
* **OS** (`uname -a` on Linux): n/a
* **Browser name/version**: Firefox 54
* **Used Command Line Parameters**: --port 80 --root /test --auth --username admin --password password --no-console --no-terminal --no-config-dialog --no-contact
* **Changed Config**: n/a

Unfortunately I'm unable to reproduce this issue locally, it only occurs "in production". This gist contains a URL that is working for now, including credentials. The files it shows are irrelevant, though I'd still like to remove the link to the gist once this is resolved: https://gist.github.com/jzaefferer/20c63cc9648278e760e96b5f78a5cb6d

As a baseline, this works fine in Chrome Canary. Chrome 60 still has the issue I described in #124

This I looked for to try and pin down the actual issue, in Firefox 54:
*  when loading the page, it doesn't log anything to the console.
* when I tab to the file panel, then cursor down to a folder and press enter, it logs "TypeError: E is undefined", from cloudcmd.js:1:48409 (when I click on that, Firefox opens the minified file in a separate tab, I don't know how to get it to load the source mapped source file
* none of the menu buttons work. Console only logs "Use of getPreventDefault() is deprecated.  Use defaultPrevented instead." on the first click
* the contextmenu doesn't work, instead it always shows the native menu.
* Navigation with the mouse (only left click) works fine

I've looked for existing (closed) issues that might be related, but couldn't find anything useful.

**Comment by coderaiser** [comment]
Looks like it is relates to #124 but on FireFox. When I open your link in Incognito mode, nothing works as you mention, but after page reload everything is OK.

When I use part of your url without credentials and type login/password in dialog box - everything is OK.

Also it can be related to bad certificate, when I open demo url `http://cloudcmd.herokuapp.com`, everything works good so it is definitely not a bug of `Cloud Commander`.

I suggest you to use [letsencrypt](https://letsencrypt.org) to generate valid certificate. It is free.

**Comment by jzaefferer** [comment]
I verified that it has nothing to do with the SSL cert. The same issue happens with a valid certificate. Though I can also confirm that it works when loading the page again without the credentials in the URL. Tracking down what's causing that in Firefox itself is going to be an even bigger PITA.

Thanks for taking a look.
