### ISSUE TITLE
zip extract don't work if archive contains directory

### ISSUE THREAD

**Issue by olegy89** [coderaiser/cloudcmd#129]
Version: 7.3.1 from https://hub.docker.com/r/coderaiser/cloudcmd/
Able to reproduce issue also on demo: http://cloudcmd.herokuapp.com/fs/tmp/

If zip archive contains dirs, it fails to extract with:
ENOENT: no such file or directory, open '/path/'

**Comment by coderaiser** [comment]
Thank you, fixed with coderaiser/node-onezip/pull/1.
Landed in [onezip v1.0.9](https://github.com/coderaiser/node-onezip/releases/tag/v1.0.9).
Please run:

```
npm i cloudcmd -g
```

for changes take effect.
