### ISSUE TITLE
Deploy behind a reverse proxy with Apache

### ISSUE THREAD

**Issue by baquiasg** [coderaiser/cloudcmd#130]
Is there a way to deploy Cloud Commander behind a reverse proxy using Apache ?

Thanks

* **Version** (`cloudcmd -v`): v7.3.1
* **Node Version** `node -v`: v7.10.1
* **OS** (`uname -a` on Linux): Ubuntu 14.04
* **Browser name/version**: Chrome

**Comment by coderaiser** [comment]
I'm not sure what are you talking about, maybe [this will help](https://github.com/jupyterhub/jupyterhub/issues/219).
