### ISSUE TITLE
Read-only mode

### ISSUE THREAD

**Issue by ColinMaudry** [coderaiser/cloudcmd#131]
Hello :)

Feature request: how hard would it be to have read-only mode? I'd like to let friends and colleagues access files, but disabling any write operation.

I may also setup special Unix permissions on the directories, but that's more work...

Thanks!

**Comment by coderaiser** [comment]
Hello,

One of the way of doing this is adding user with read only permissions and starting `Cloud Commander` from this user.

Second way is: is to use docker container with new user who have read only access and mount directory you want to share.
