### ISSUE TITLE
error with gritty

### ISSUE THREAD

**Issue by zolcord** [coderaiser/cloudcmd#135]
when launching cloudcmd with gritty, i get the error :
cloudcmd --terminal: Cannot find module '../build/Release/pty.node'
before
url: http://localhost:80/

* **Version** (`cloudcmd -v`): v7.8.0
* **Node Version** `node -v`: v8.6.0
* **OS** (`uname -a` on Linux): 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux
* **Browser name/version**: google chrome Version 56.0.2924.87 (64-bit)
* **Used Command Line Parameters**: cloudcmd --terminal --terminal-path `gritty --path` --save
* **Changed Config**: port 80

**Comment by coderaiser** [comment]
Looks like you've been update `node.js` version, in this case you should reinstall `gritty`, because of native modules, which should be recompiled, with:

```sh
npm i gritty -g
```

And start `Cloud Commander` again with same flags:

```sh
cloudcmd --terminal --terminal-path gritty --path --save
```
