### ISSUE TITLE
specifying config file when running middleware

### ISSUE THREAD

**Issue by 5shekel** [coderaiser/cloudcmd#136]
first, thank you. cloudcmd is a pleasure to use.  
using cloudcmd as a file manager and editor for a jekyll based blog.  
now i would like to run a 2nd blog with cloudcmd access to its users with their own password

so i understand middleware is my option #88 
i was satisfied with adding `auth`, `user` and `password` to the index.js file.
but then the password is in clear text, so using the config file is better

i cant figure out how to call another configure file from the index.js

* **Version** (`cloudcmd -v`):  v7.9.0
* **Changed Config**: 
[index.txt](https://github.com/coderaiser/cloudcmd/files/1346877/index.txt)

**Comment by coderaiser** [comment]
As I understand what you want is passing `hash` of a password to `Cloud Commander middleware`, same as located in `~/.cloudcmd.json`  and not keep it as plain text. Am I right?

**Comment by 5shekel** [comment]
Yes

**Comment by coderaiser** [comment]
Changed the way of handling passwords in `Cloud Commander Middleware` [v8.0.0](https://github.com/coderaiser/cloudcmd/releases/tag/v8.0.0). No it accepts encrypted password only in the same format as in `~/cloudcmd.json`.
