### ISSUE TITLE
Forbidden when trying accessing folders

### ISSUE THREAD

**Issue by koperkiewicz** [coderaiser/cloudcmd#138]
* **Version** (`cloudcmd -v`): v8.1.2
* **Node Version** `node -v`: v8.1.4
* **OS** (`uname -a` on Linux): Linux area69 2.6.32-042stab123.9 #1 SMP Thu Jun 29 13:01:59 MSK 2017 x86_64 x86_64 x86_64 GNU/Linux
* **Browser name/version**: Evergreen browsers
* **Used Command Line Parameters**: cloudcmd
* **Changed Config**: nothing

Whatever folder or file I try to access I get "Forbidden" info. Reinstallation doesn't help. 

[https://i.imgur.com/SBpDowS.png](url)

@edit: sudo doesn't work either

**Comment by coderaiser** [comment]
Maybe it is related to `user access rights` on your system. Could you please try demo site `http://cloudcmd.herokuapp.com/`, is it works for you?

Also could you please upgrade to latest `LTS` version of node.js which is `8.9.1` on current moment.
