### ISSUE TITLE
Changing layout panels

### ISSUE THREAD

**Issue by solipsist01** [coderaiser/cloudcmd#139]
I'd like to change the layout of the panels
Would it be possible to remove the tables date,owner,mode so that there is more space for longer filenames.

**Comment by coderaiser** [comment]
There is no such possibility but it is a good idea for contributing :).
Looks like [cloudfunc](https://github.com/coderaiser/cloudcmd/blob/a8fafbf87b88e158d179df37b947d83cb99fabca/common/cloudfunc.js#L105) should be changed.

**Comment by coderaiser** [comment]
Closed due to long time of inactivity.

**Comment by coderaiser** [comment]
Added ability to set visible columns with ‘—columns’ flag in ‘Cloud Commander’ [v8.3.0](https://github.com/coderaiser/cloudcmd/releases/tag/v8.3.0).

**Comment by coderaiser** [comment]
Landed ability to hide `date`, `owner` and `mode` in `Cloud Commander` [v8.4.0](https://github.com/coderaiser/cloudcmd/releases/tag/v8.4.0).

You can use:

```
cloudcmd --columns name-size
```
for this purpose.

**Comment by solipsist01** [comment]
Brilliant, thank you ! :)
