### ISSUE TITLE
video playing

### ISSUE THREAD

**Issue by breezzz** [coderaiser/cloudcmd#141]
А каким образом должны просматриваться видео по F3?
у меня выходит окошко плейера на avi, но потом кнопка play быстро стает серой.
На mov даже окошко плейера не появляется.
В итоге не нашел ни одного видео файла, который можно просмотреть.
Что-то надо доустановить?

* **Version** (`cloudcmd -v`): v8.1.3
* **Node Version** `node -v`: v9.4.0
* **OS** (`uname -a` on Linux): Linux srv.localhost.cy 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:50 UTC 2017 i686 i686 i686 GNU/Linux
* **Browser name/version**: Google Chrome 63.0.3239.132 (Официальная сборка), (64 бит)
* **Used Command Line Parameters**:  -
* **Changed Config**: -

**Comment by coderaiser** [comment]
Все зависит от браузера, поддерживаются форматы [перечисленные здесь](https://developer.mozilla.org/ru/docs/Web/HTML/%D0%9F%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%B8%D0%B2%D0%B0%D0%B5%D0%BC%D1%8B%D0%B5_%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0_%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D1%8B).
