### ISSUE TITLE
Не перемещаются файлы при фокусе на ..

### ISSUE THREAD

**Issue by Fot0n** [coderaiser/cloudcmd#142]
* **Version** (`cloudcmd -v`): v8.2.0
* **Node Version** `node -v`: v6.12.2
* **OS** (`uname -a` on Linux): Centos 7.4
* **Browser name/version**: Firefox 57.0.4
* **Used Command Line Parameters**: запускается без параметров с помощью pm2 от имени root

Здравствуйте! Установил последнюю версию cloudcmd на новый VDS и заметил, что если выделить файл/файлы и, переместив фокус в другую панель так что он находится на "..", попытаться вставить появляется сообщение: "No files selected". Если же сместить его (фокус) на другой каталог или файл панели — вырезанное перемещается. Такое поведение ошибка или так задумано?

**Comment by coderaiser** [comment]
Судя по всему, это ошибка. Так быть не должно.

**Comment by coderaiser** [comment]
Исправлено в [v8.2.1](https://github.com/coderaiser/cloudcmd/releases/tag/v8.2.1)
