### ISSUE TITLE
prefix config option only works as command line argument (json config is ignored)

### ISSUE THREAD

**Issue by asaf-romano** [coderaiser/cloudcmd#143]
* **Version** (`cloudcmd -v`): 8.2.1
* **Node Version** `node -v`: 8
* **OS** (`uname -a` on Linux): tested on OS X 
* **Browser name/version**:  -
* **Used Command Line Parameters**:  --config=./cloudcmd_config.json --show-config --prefix "foo" vs. no prefix
* **Changed Config**: 
name, auth, editor, etc.

If I launch cloudcmd with --prefix=foo, it is indeed printing out "url: http://localhost:8000/foo/" (in the printed config it does not show though). On the other hand, setting prefix in the json file doesn't work (url is just http://localhost:8000/) - however the printed config does show the right value.

**Comment by coderaiser** [comment]
How do you run `Cloud Commander`? There is no support of using `cloudcmd --config=./cloudcmd_config.json` the correct version is `cloudcmd --config ./cloudcmd_config.json`.

**Comment by coderaiser** [comment]
Close due to inability to reproduce.
