### ISSUE TITLE
Chmod and chown

### ISSUE THREAD

**Issue by m74m** [coderaiser/cloudcmd#144]
I couldn't find it in the docs, so I'd like to propose a feature which would, in my opinion make Cloudcmd the perfect tool. 

Could a means for (recursive) changing of owner/group and/or Unix access rights be implemented for selected file(s)/directorie(s)? Another option would be the option to automatically change ownership and access right of the copied/moved file to match those of the destination directory.

Thanks

**Comment by coderaiser** [comment]
There was such an issue https://github.com/coderaiser/cloudcmd/issues/63. The main problem is the way how it should be handled on `Windows`, it is not compatible with `Unix` at all.

Also there is `console` and `terminal` which can be used for this purpose.

Do you have any ideas?

**Comment by coderaiser** [comment]
Closed due to absence of ideas.
