### ISSUE TITLE
Auth not working

### ISSUE THREAD

**Issue by Tosko4** [coderaiser/cloudcmd#147]
How do I set an authentication?
I did nano ~/.cloudcmd.json and modified username and password with authentication set to true. I put in the details but the login keeps prompting.

When I press esc, it says 401 unauthorized which is good.

So I went to the json file, but it back to false, and it worked again. I tried to enable Auth via the UI, (F10 settings), again login prompt and keeps prompting. Any idea what I am doing wrong?

* **Version** 8.2.2
* **Node Version** 6.13.0
* **OS** Ubuntu 16.04
* **Browser name/version**: Google Chrome

**Comment by coderaiser** [comment]
`~/.cloudcmd.json` contains `hash` of a `password` so if you write it as plain text you did things wrong :). You should use:
 
```
cloudcmd --username user --password password --auth --save
```

Is it help?

Duplicate in Russian of https://github.com/coderaiser/cloudcmd/issues/72

**Comment by Tosko4** [comment]
That was the fix! Thank you :)
