### ISSUE TITLE
Need help with setting it up with pm2

### ISSUE THREAD

**Issue by Tosko4** [coderaiser/cloudcmd#148]
Hi there,

I am using Cloud Commander and I run it from a VPS. When the console disconnects, the script goes down.

Now I use some other applications on this server which are triggered by a json file and runs it in the background and enabled me to monitor it. Any suggestions on how I can add Cloud Commander to my pm2 ?

Info about pm2: https://www.npmjs.com/package/pm2

* **Version** 8.2.2
* **Node Version** 6.13.0
* **OS** Ubuntu 16.04

**Comment by coderaiser** [comment]
Hi, it is a very interesting use case :). You can use something like this to start `cloudcmd`:
```
$ npm i cloudcmd pm2 -g
$ pm2 start `which cloudcmd`
```

Also you can [generate a startup script](https://www.npmjs.com/package/pm2#startup-script-generation) to keep PM2 and `cloudcmd` alive at every server restart.
with:
```
$ pm2 startup
```

You can [monitor in console](https://www.npmjs.com/package/pm2#terminal-based-monitoring) it with:
```
$ pm2 monit
```
Or in [keymetrics](https://keymetrics.io).

Did I answer you question?

**Comment by Tosko4** [comment]
@coderaiser again, very good assistance! It worked! 👍
