### ISSUE TITLE
Ability to specify UID and GID to use in docker container

### ISSUE THREAD

**Issue by cheesemarathon** [coderaiser/cloudcmd#149]
Hi
Thanks for your work so far
I'm currently running your Docker container on unRAID and I have a tiny issue with it. Upon creating/moving/editing files the user of the file is changed to root. In unRAID the default user is not root so this can cause problems with permissions. Therefore, would it be possible to add a variable that can be entered at startup to set the UID and GID to run the container as?

[Here](https://lime-technology.com/forums/topic/39289-adapting-container-user-and-group-ids-to-the-host/) is a link to a post on the unRAID forums as to how one guy has solved this issue. He explains the issue a bit more as well if my explanation isn't great.

**Comment by coderaiser** [comment]
Hi, to start container with predefined `id` you should determine your user's id first:

```
coderaiser@cloudcmd:~$ id
uid=1010(coderaiser) gid=1010(coderaiser) groups=1010(coderaiser)
```
Then you can use received `id` in `-u` flag in [docker run](https://docs.docker.com/engine/reference/commandline/run/):

```
--user, -u     Username or UID (format: <name\|uid>[:<group\|
```

This way:

```
docker run -t --rm -v ~:/root -v /:/mnt/fs -p 8000:8000 -u 1010 coderaiser/cloudcmd
```

After that `owner` of files should not change.

Is it helps?

**Comment by cheesemarathon** [comment]
That works perfectly, Thanks
