### ISSUE TITLE
Nginx auth conflict

### ISSUE THREAD

**Issue by kirtapix** [coderaiser/cloudcmd#151]
* **Version** (`cloudcmd -v`): 8.3.0/8.4.0
* **Node Version** `node -v`: 9.8.0
* **OS** (`uname -a` on Linux): Linux NasPi 4.9.59+ #1047 Sun Oct 29 11:47:10 GMT 2017 armv6l GNU/Linux* **Browser name/version**: latest firefox
* **Used Command Line Parameters**: sudo cloudcmd

Hi,
Got a problem with basic authentication in Nginx and with in cloudcmd.
When Auth is activated in Nginx, I get the popup to enter my credentials for Nginx but then everything is blocked and I get error 401 on every request for cloudcmd loading(seen in Firefox dev tool console).
If I deactivate Auth in Nginx and clear cache, reload Nginx and cloudcmd, I got the popup for cloudcmd and it loads correctly.
Seems that credentials for Nginx are used for cloudcmd by the webbrowser or something like that.

Thx in advance !

**Comment by coderaiser** [comment]
The thing is `nginx` is a proxy server so when you use [http-auth](http://nginx.org/en/docs/http/ngx_http_auth_basic_module.html) it sets header `status: 401` then gets `username` and `password` but if you not set header directly in [proxy_set](https://serverfault.com/questions/230749/how-to-use-nginx-to-proxy-to-a-host-requiring-authentication) it would not send it to `cloudcmd`. 

Also you can set field [proxy_pass_request_headers](http://nginx.org/en/docs/http/ngx_http_proxy_module.html) as [described here](https://stackoverflow.com/questions/14839712/nginx-reverse-proxy-passthrough-basic-authenication).

Is it helped?

**Comment by kirtapix** [comment]
Tried to add > `more_set_input_headers  'Authorization: $http_authorization';` in my nginx conf file but it didn't helped. I need to recompile Nginx with More mod.
Do you think it is possible to make a connection portal and put cloudcmd and my other web apps behind it ?

**Comment by coderaiser** [comment]
I think you can use `proxy_set_header` or `proxy_pass_request_headers` instead of `more_set_input_headers`.

What do you mean by `connection portal`?

**Comment by kirtapix** [comment]
Ok got it to work, now nginx auto anthenticate in cloudcmd.
Sorry my english technical vocabulary is not as good as yours.
I mean a front-end session manager, something like wwwhisper.

**Comment by coderaiser** [comment]
Glad to help :)
