### ISSUE TITLE
The New Version 8.5.0 hangs (on chrome os)

### ISSUE THREAD

**Issue by beliefless-dogmasless** [coderaiser/cloudcmd#152]
Hy,

Just to let you know, the last version, hangs on chrome os.

<a href="http://fr.tinypic.com?ref=10547b5" target="_blank"><img src="http://i63.tinypic.com/10547b5.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

Check the .gitignore  file, there is a small figure and it goes 'nowhere'. It is 'the same' for the functions below (all the below bar), I can't access it(the functions, they hang).

**Comment by coderaiser** [comment]
Could you please open developer tools and check if there some errors?
Try to clear cache of your browser.  What with previous versions? Are they hang to?

**Comment by beliefless-dogmasless** [comment]
Excuse me, you 'were right', I cleared 'the cache', and both versions work fine. By the way, great software, thanks.
