### ISSUE TITLE
8.5.2 red exclamation icon? Copy/move failure

### ISSUE THREAD

**Issue by inamak** [coderaiser/cloudcmd#156]
Hi - On 8.5.2 and it does not crash any more. However on copy complete the blue progress icon is replaced with a red exclamation icon?

**Comment by coderaiser** [comment]
No, looks like something is wrong. Please try to clear cache and to use demo sites.

**Comment by inamak** [comment]
I just tried in chrome and it doesnt give the same issue so all ok

**Comment by coderaiser** [comment]
Do you have some errors in console?

**Comment by coderaiser** [comment]
I'm talking abou `console` in developert tools of your browser.

**Comment by inamak** [comment]
Hi - yes here is the console log of the error (i removed my internal ip)

[error.log](https://github.com/coderaiser/cloudcmd/files/1855523/error.log)

**Comment by coderaiser** [comment]
What version of `node.js` are you using?

**Comment by inamak** [comment]
Looks to be v8.10.0

**Comment by coderaiser** [comment]
So when you copy/move big files some times files do not get copied/moved? Is it all infromation you can provide?

**Comment by inamak** [comment]
i get the red exclamation mark, and files are only partially transferred. There is an issue with the logging which is detailed in the other issue (probably same as settings) so cant get any info from there until that is sorted.

**Comment by inamak** [comment]
I am running a newer container now with fixed settings. Still getting the same error on moving. Nothing additional in logs.

I did get another error just now. Moving a folder with 2 6gb files in it, first file moved and then it errored with second, and file disappeared from source drive. Popup error with ENOENT error.

**Comment by coderaiser** [comment]
I have no idea why big files not copied. As I understood it is all infromation: when you copy big files, you receive error.  I just copied one `2gb` file and 3 `700mb` files. Everyrhing is OK. The progress should be improved to show not only progress of count of files, but progress of one big file as well.

I'll close it for now and think about it. If I have some idea or fix I'll write here.
Thank you.

**Comment by inamak** [comment]
Ok thanks. I noticed that it doesn't really happen on copy, but always on move. Try with a folder with multiple large files, by moving whole folder.
