### ISSUE TITLE
8.5.2 progress percentage missing

### ISSUE THREAD

**Issue by inamak** [coderaiser/cloudcmd#157]
Hi - I am on 8.5.2 now and still only see the blue icon on copy - no percentage? Cleared browser cache but did not help. Using latest Firefox

**Comment by coderaiser** [comment]
I can not reproduce. Could you please try one of demo sites: https://cloudcmd.now.sh or http://cloudcmd.herokuapp.com

**Comment by inamak** [comment]
I can see the percentage on your demo site but not on my local instance. See screenshot 

<img width="96" alt="progress icon" src="https://user-images.githubusercontent.com/37736436/37923065-1f2cf168-3126-11e8-8a19-6d58f93d1490.png">

I tried in latest firefox and chrome, after clearing cache in both.

**Comment by coderaiser** [comment]
There is [progress](https://github.com/coderaiser/cloudcmd/blob/v8.5.2/json/config.json#L22) option, when it set to `true` `progress` is enabled. Did you change this option? What value in your `~/.cloudcmd.json` file?

**Comment by inamak** [comment]
Weirdly i dont seem to have the ~/.cloudcmd.json file

**Comment by inamak** [comment]
Ah ok will you add percentage for move as well? I get an error when try to change any option - posted the error on that other issue

**Comment by coderaiser** [comment]
There is no need for `progress` of move operations in most cases so I do not know about it.  Why do you need this? Are you often move files from different partitions and it tooks to much time?

**Comment by inamak** [comment]
Yes - moving files from one drive to another on my server for longer term storage. Most of the operations I do are move operations like moving files from temporary location to sorted folders. Also having to move files from drives running low on space.

**Comment by coderaiser** [comment]
OK, we need something with similar API to [copymitter](https://github.com/coderaiser/node-copymitter) but using [fs.rename](https://nodejs.org/api/fs.html#fs_fs_rename_oldpath_newpath_callback) and handling [EXDEV](
http://man7.org/linux/man-pages/man2/rename.2.html) error.

**Comment by coderaiser** [comment]
When you use operations like: `copy`, `delete`, `pack`, `extract` files with operations logic is loading and connecting to server with help of `websockets`. While `websockets` not connected `ajax` version of this operations used, it is with out `progress`. When `websockets` disconnected operations also degrades to `ajax`. Looks like your case is one of this two.

**Comment by inamak** [comment]
Interesting. Any idea why websockets isn't being used a lot of the time?

**Comment by coderaiser** [comment]
This is done for greceful enhancement, `websocket` connection takes time in any case. The same with greceful degradation to `ajax`. Also start load of `Cloud Commander` is much faster, because a lot logic lazy loads on first use.

**Comment by coderaiser** [comment]
Do you have any other questions or ideas for improvements?

**Comment by coderaiser** [comment]
If you have 3 files, progress divedes to three parts: `33%`, `67%`, `100%`. Looks like `copymitter` should be improved to count all file sizes, and then increase current position while streaming or something like that, it is a an interesting idea, but now [fs.copyFile](https://github.com/coderaiser/fs-copy-file) used for this purpose, and it is not provide a progress information, but can speed up the process.
