### ISSUE TITLE
8.5.2 error on changing settings

### ISSUE THREAD

**Issue by inamak** [coderaiser/cloudcmd#158]
Hi - if i try change any settings i get the following error:

EACCES: permission denied, open '/.cloudcmd.json'

Didn't have this issue on 8.4.0 - any idea why its happening?

**Comment by coderaiser** [comment]
What are you using to change settings `config dialog` or `cloudcmd --save`?

**Comment by inamak** [comment]
I am using the config dialog. That is not available on your demo site?

**Comment by coderaiser** [comment]
No on demo site it is not available because a lot peaple enable and disable `auth` option all the time :).

Could you please run command:

```
 node -e 'console.log(os.homedir())'
```
Config is read from the `home` directory by default. What is your home directory?

**Comment by inamak** [comment]
I am running a docker container on unraid which was created by someone else. I will ask why the log isnt showing anything and where config is stored

**Comment by coderaiser** [comment]
There is [--config](https://github.com/coderaiser/cloudcmd/blob/v8.5.2/HELP.md#start) option which can be used to override config options:

```
cloudcmd --config ~/.cloudcmd.json
```

Also you can use [Environment Variables](https://github.com/coderaiser/cloudcmd/blob/v8.5.2/HELP.md#environment-variables-1) to change config options on start of `cloudcmd`.

Is it helps?

**Comment by cheesemarathon** [comment]
hey, I created the template for the docker container.
/root in the container (where the config should be I believe) is mounted to a directory on the host. 
The container is also run with -u 99:100, as mentioned in issue #149 , in order for it to create and modify files with the correct permissions. The folder that is mounted is also owned by user 99 so there shouldn't be permission issues. However, that seems to be the problem. If I run the container without the -u 99:100, although no config is created initially. Upon exiting the config it creates and saves the file.

So if I run with -u 99:100 I can edit files with the correct user but not edit the config and if I run without -u 99:100 it edits files with the wrong user but I can edit the config.

Any ideas?

**Comment by coderaiser** [comment]
Do you really need to change config after docker container start?
If there is necessity for it you should use a little bit different aproach, you said: 
>  /root in the container (where the config should be I believe) is mounted to a directory on the host. 

But [this](https://github.com/coderaiser/cloudcmd/blob/v8.5.2/json/config.json) config file is default options. When you change `config options` via command line or `config dialog` the new config file is created in `~/.cloudcmd.json`. So better solution would be to mount `HOME` directory to directory on the host. 

What this command shows when you run it in your docker container?

```
 node -e 'console.log(os.homedir())'
```

or

```
echo $HOME
```

**Comment by inamak** [comment]
I ran both those commands in the console in the cloudcmd web interface and output for both was

/

**Comment by cheesemarathon** [comment]
However, if you run the above commands without the -u 99:100 command it reports the home directory as /root

**Comment by coderaiser** [comment]
You can override `$HOME` directory [env variable in Dockerfile](https://docs.docker.com/engine/reference/builder/#env) and this should fix things up.

**Comment by cheesemarathon** [comment]
Thank you, that seems to work

**Comment by coderaiser** [comment]
That is great :)
