### ISSUE TITLE
Hot keys not works in Opera 

### ISSUE THREAD

**Issue by ydanila** [coderaiser/cloudcmd#161]
If with older version 6.1.6 I have partial hotkey ignoring - not worked for F3.

Now with updated version hot keys not works at all.

* **Version** (`cloudcmd -v`): 
v9.0.0
* **Node Version** `node -v`: 
v6.11.4
* **OS** (`uname -a` on Linux): 
Linux cubox-i 4.9.12-cubox #7 SMP Thu Feb 23 21:22:20 CET 2017 armv7l armv7l armv7l GNU/Linux
* **Browser name/version**: 
Opera  52.0.2871.40
* **Used Command Line Parameters**: 
* **Changed Config**:

**Comment by coderaiser** [comment]
I could not reproduce this. Could you please try to clean cache of you browser?

**Comment by coderaiser** [comment]
Do you have any errors in Developer Tools Console ?

**Comment by ydanila** [comment]
There is no error. It just can't override standard behaviour for F3 - search command.

**Comment by coderaiser** [comment]
Could you please try this in demo site: `http://cloudcmd.herokuapp.com`

**Comment by ydanila** [comment]
No difference. F3 still has standard behaviour for Opera. If you have logging you will find that I sequentially pressed F1 - F12.

**Comment by coderaiser** [comment]
It is strange, I can not reproduce this on opera `52.0.2871.40`. There is no such logging.
Could you please try to type in `input` in right bottom corner of this [fiddle](https://jsfiddle.net/qn0du9g4/1/).

`f4` and `f3` keys processed in the same way in [client/key/index.js](https://github.com/coderaiser/cloudcmd/blob/v9.0.0/client/key/index.js#L181-L190) file. All this cases uses [event.preventDefault](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) and override default browser functionality.

**Comment by ydanila** [comment]
Same behaviour. All key codes catched except F3. Tested in private mode with disabled extensions.

**Comment by coderaiser** [comment]
Looks like it is a bug in Linux Opera.

**Comment by ydanila** [comment]
In OS info about server side. Client side is under Windows 10 x64. 

In Chrome and FF also tested - F3 works.

**Comment by coderaiser** [comment]
OK, so this is not a bug of `Cloud Commander`. It is a bug of Opera. You better write about it in https://bugs.opera.com/wizard/
