### ISSUE TITLE
cloudcmd and big files properties issue

### ISSUE THREAD

**Issue by kirtapix** [coderaiser/cloudcmd#162]
* **Version** (`cloudcmd -v`): 9.1.0
* **Node Version** `node -v`: v9.8.0  
* **OS** (`uname -a` on Linux): latest debian stretch for Rpi
* **Browser name/version**: latest firefox
* **Used Command Line Parameters**: //
* **Changed Config**: //

Hi Coderaiser,

It seems that cloudcmd can't get properties of files that size is > 2GB, here is a screenshot :
![image](https://user-images.githubusercontent.com/37413390/38354378-af17f8b4-38b9-11e8-90ae-ec471def879d.png)
And thus, can't copy/paste those file.
I tried to change the columns config and if I set it to "name-size-date" here is what I get : 
![image](https://user-images.githubusercontent.com/37413390/38354501-19b71a60-38ba-11e8-92b5-84ce3bd59a08.png)

Thanks in advance !

**Comment by coderaiser** [comment]
Could you please try to clean cache. As I see files with size `0b` is owned by `root` and you have no rights to get information about it. Do you see the same with files owned by you?

**Comment by kirtapix** [comment]
YEs it's also a bug, because all files are owned by user 'pi'

**Comment by coderaiser** [comment]
I can not reproduce this. Just created file
![screen shot 2018-04-05 at 4 59 12 pm](https://user-images.githubusercontent.com/1573141/38370470-d458f6e4-38f2-11e8-8b08-255e3e84f120.png)
Could you pleas run `ls -lha` in this directory?

**Comment by kirtapix** [comment]
Of course, here is a screen of the output, there's about 100files in this directory. It is a shared folder.
![img_20180405_163011](https://user-images.githubusercontent.com/37413390/38372555-6846608e-38ef-11e8-9068-e530a5790581.jpg)

**Comment by coderaiser** [comment]
OK so there is no files owned by `root`. Could you please install `flop` with `npm i flop -g`
And use in this directory.

```
flop -r .
```

Is it shows any files owned by `root`? [flop](https://github.com/coderaiser/flop) reads directory in the same way as `Cloud Commander` does. We need to determine where the error is on client side or server side.

Could you please try to use `node v8`.

**Comment by kirtapix** [comment]
![screenshot_20180406-092119](https://user-images.githubusercontent.com/37413390/38408086-505e36e4-397c-11e8-909a-5585da88d980.png)

**Comment by coderaiser** [comment]
Thank you :), fixed `name-size` columns with 7eff4f7. Landed in [v9.1.1](https://github.com/coderaiser/cloudcmd/releases/tag/v9.1.1).
