### ISSUE TITLE
Left key in image view does not jum to next image

### ISSUE THREAD

**Issue by davidrapin** [coderaiser/cloudcmd#164]
* **Version** (`cloudcmd -v`): 9.1.2
 * **Node Version** `node -v`: 7.5.0
* **OS** (`uname -a` on Linux): Ubuntu 16
* **Browser name/version**: Chrome 49, Firefox 52 
* **Used Command Line Parameters**: `cloudcmd -c config.json`
* **Changed Config**: all defaults (except root directory: `/home/david/btsync-data`)

Steps to reproduce:
- open a folder with 10 images
- right-click on 5th image
- click "View"
- press "left" key
- 🐛 1rst image appears by FancyBox

Expected behavior: 
- 6th image is displayed by FancyBox

**Comment by coderaiser** [comment]
Thank you :). Landed in [v9.1.3](https://github.com/coderaiser/cloudcmd/releases/tag/v9.1.3).

**Comment by davidrapin** [comment]
Thank you for the quick merge 👍
