### ISSUE TITLE
Improvement: swipe images to next/previous

### ISSUE THREAD

**Issue by luismesagravedeperalta** [coderaiser/cloudcmd#169]
The applicaition is AWESOME. Simple as it can be, runs like a sharm. 
It would be nice to be able to swipe the images when accessed from mobile

**Comment by coderaiser** [comment]
Thank you, it is a good idea, but for images [fancybox](http://fancyapps.com/fancybox/) used and it doesn’t support swipe. Maybe you know js libraries for images with swipe support? Maybe we can use one of them instead of ‘fancybox’

**Comment by luismesagravedeperalta** [comment]
This one looks cool http://photoswipe.com

**Comment by coderaiser** [comment]
Yes, it looks good, has no jquery dependency, and can be installed with `npm`.

The thing is `fancybox` used for most modal windows (`view`, `edit`, `console`, `terminal`). And if `photoswipe` can be configurated to a similar appearance, we can try to use it instead of `fancybox` :).

All logic located in [client/modules/view](https://github.com/coderaiser/cloudcmd/blob/b7262f954b217324f60d9896ff57139c91ddedbe/client/modules/view.js) and styles in the [css/view.css](https://github.com/coderaiser/cloudcmd/blob/b7262f954b217324f60d9896ff57139c91ddedbe/css/view.css).

Do you want to give a try?

**Comment by luismesagravedeperalta** [comment]
Ok, i'll take a look and see if I can be of any help :))
Just FYI, I'm trying to setup my own cloud with the RPi, but I just want to be able to browse my files/media, don't care for all the other features nextcloud and other applications provide (use a LOT of resources making files versioning, keep a db with the files structure rather than go directly to fs, etc). Also, cloudcmd takes care of the "data plug-n-play", which none of them do (expected as they use a db, so an initial import would be required, rather than just setting up a root dir as cloudcmd does). I think this is a GREAT project you've got here, and solves what I believe is the most frequent use case: i've got my files, just want to serve them over http. I used to have samba to access my files when in the intranet, but cloudcmd is so easy to use (the two panes features is great for moving stuff around!) that i'm not accessing them over samba anymore. I only need to set a file sync mechanism to map a local folder to the HDD, but that i can do with any other solution out there, and if i can also find something to do the same from my android, the pack is complete :P
Thanks for your help with cloudcmd!

**Comment by coderaiser** [comment]
Glad to see that `Cloud Commander` can be a part of such a big system :).

> Also, cloudcmd takes care of the "data plug-n-play", which none of them do (expected as they use a db, so an initial import would be required, rather than just setting up a root dir as cloudcmd does)

What do you mean by initial import? Files stored in the database and they will be extracted to file system for use in `Cloud Commander`, am I right?

**Comment by luismesagravedeperalta** [comment]
I mean that in cloudcmd I just set up a root directory and it would allow to browse. In nextcloud, for example, I'd need to start from an empty directory and then explicitely add the files and it internally would copy them to the folder plus inserting corresponding rows in their mariadb. The cloud always starts from scratch. It's just another application, for multiple users etc etc. It's really cool but I can't afford to maintain it and all the HDD it consumes. It's literally a personal dropbox.

**Comment by coderaiser** [comment]
OK, I get it.

**Comment by coderaiser** [comment]
@luismesagravedeperalta do you have any progress on this?

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity.
