### ISSUE TITLE
Improvement: Images/videos preview

### ISSUE THREAD

**Issue by luismesagravedeperalta** [coderaiser/cloudcmd#170]
Another nice improvement would be to have images and videos preview.

**Comment by luismesagravedeperalta** [comment]
In the case of images, rather than
```
.text-file {
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAABGdBT…gVFpqRwC8mfoXPPEVPS7LbRaJL2y7bOifRCTEli3U7BMWgLzKlW/CuebZPAAAAAElFTkSuQmCC);
}
```
using a thumbnail instead.

**Comment by coderaiser** [comment]
Sounds interesting :). What sizes of thumbnails do you think better fit current UI?

**Comment by luismesagravedeperalta** [comment]
no clue about the size... I'm not a very UI guy :P... this could help tough, adding an endpoint to just return the 64based thumbnain asyn ( I guess that adding the generation of the thumbnail synchronously would be a great overhead to response time if the directory is big)
https://github.com/chrisben/image-thumb

**Comment by coderaiser** [comment]
Next files should be changed for this purpose:
- [common/cloudfunc.js](https://github.com/coderaiser/cloudcmd/blob/v9.3.0/common/cloudfunc.js#L109)
- [tmpl/fs/file](https://github.com/coderaiser/cloudcmd/blob/v9.3.0/tmpl/fs/file.hbs)
- [client/client.js](https://github.com/coderaiser/cloudcmd/blob/v9.3.0/client/client.js#L487)
- [server/route.js](https://github.com/coderaiser/cloudcmd/blob/v9.3.0/server/route.js#L162)

**Comment by luismesagravedeperalta** [comment]
Yes, I said 64based as I saw that's how it's done at the moment.. the new endpoint would need to create the thumbnail and return it, either in 64based or any other format.
restafary is what you are using in the backend at the moment? I'll run it and check it up..

**Comment by coderaiser** [comment]
Yes, it is one of the modules used on server side. `Restafary` is used for [REST](https://github.com/coderaiser/node-restafary#rest) `CRUD` and getting a list of directory content. It uses [flop](https://github.com/coderaiser/flop) for file operations, which uses [readify](https://github.com/coderaiser/readify) to get list of files with attributes. There was a talk about similar things in #101.

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity.
