### ISSUE TITLE
Added CloudCMD to PGSuite

### ISSUE THREAD

**Issue by Admin9705** [coderaiser/cloudcmd#172]
* **Version** (`cloudcmd -v`):  Newest
* **Node Version** `node -v`: None
* **OS** (`uname -a` on Linux): Linx
* **Browser name/version**: All
* **Used Command Line Parameters**: None
* **Changed Config**: None

Not sure how i could reach you guys, but here is wiki we started: https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/wiki/CloudCMD

have to update 2 screenshots, but got it started.

Works great and deploys with https:// - Great app guys!

**Comment by coderaiser** [comment]
Nice, thank you :). Glad to see such an interesting usage example.

**Comment by Admin9705** [comment]
@coderaiser - Plex Server is a mass media server.  We basically deploy a server with various tools for you to watch your media. Your program enables easy management of the server.  So if someone deploys your program, they access via cmd.domain.com and can see everything, i tricked your program by adding a base file to create plex / guide as the standard login when first starting.  even deploys with https://

**Comment by Admin9705** [comment]
@coderaiser we now use your program as a way to upload multiple jsons in a heartbeat for supertransfer2
