### ISSUE TITLE
Bug: Cloud Commander hijacks right mouse clicking outside of where is needed

### ISSUE THREAD

**Issue by user8446** [coderaiser/cloudcmd#173]
Cloud commander 9.1.1 (issue still on latest 9.4.0)
Chrome 67 

There are many instances where a simple copy/paste is needed with directories or filenames. I understand that there is a cloud commander right click menu when hovering over a directory or file but the right click is hijacked and disabled even over the topmost file path, which it shouldn't be. You can highlight it but right click brings up nothing. Ctrl-C does still work. 

Expected behavior: Right clicking when not hovering over a directory or file should bring up the OS right click menu

Thank you for the development

**Comment by user8446** [comment]
An example of use is if you want to download files inside a remote directory so you need to copy the directory name to create it on your local machine. A simple copy/paste is very useful especially on long 50+ character names. 
Example: No.Country.for.Old.Men.2007.1080p.BluRay.x264.DTS-HD.MA.7.1-Alpha

Top topmost file path would be the only place to copy from and since it is in the panel, you can't use the OS context menu even though the cloud commander context menu isn't needed there.

**Comment by user8446** [comment]
You are correct, Ctrl C does still work as a workaround... you are just jumping from mouse gestures and then to keyboard shortcuts, which is inefficient. Usually you would complete a  task with one or the other.

**Comment by coderaiser** [comment]
Do you use any other operations from context menu besides `copy`? Do you copying full path or just a name of current directory?

**Comment by coderaiser** [comment]
Added ability to copy path with help of a `copy button` with 0cb953a, landed in [v10.0.0](https://github.com/coderaiser/cloudcmd/releases/tag/v10.0.0)
