### ISSUE TITLE
Reorganising the default view

### ISSUE THREAD

**Issue by mstipetic** [coderaiser/cloudcmd#174]
Hey,

I'm trying to figure out how to edit the template. Basically I'd like a one panel mode with the top being the file explorer/editor and bottom an always visible console.
I've been going through the code trying to figure it out, but am having issues. Do you have any suggestions or documentation I could look up?
I've looked into the dword/deepword/edward repos to maybe setup the console manually, but they don't seem to come with the filepicker plugin.

Any suggestions would be very welcome.

**Comment by coderaiser** [comment]
There is no such possibility to embed `file list` independently but it is a good idea for improvement. 

`Console` and one of editors you already can put in one page, that should not be a problem at all.
Here is main place to render files data into tamplates: [buildFromJSON from /common/cloudfunc.js](https://github.com/coderaiser/cloudcmd/blob/v9.4.0/common/cloudfunc.js#L109). All templates located in [/tmpl](https://github.com/coderaiser/cloudcmd/tree/v9.4.0/tmpl).

**Comment by mstipetic** [comment]
Awesome, thanks, will have a look!
