### ISSUE TITLE
socket.io not found when using prefix

### ISSUE THREAD

**Issue by csazku** [coderaiser/cloudcmd#175]
* **Version**: v9.5.0
* **Node Version**: v9.4.0 
* **OS**: Ubuntu 16 
* **Browser name/version**: Chorme v66
* **Used Command Line Parameters**: --prefix
When using the prefix option and trying to edit files the request for socket.io returns 404 not found.
Tested using edward and dword editors and multiple prefixes( the one i was using originally had a dot in it, thought that might be the problem) .
Also tested without prefix and it works fine.
Also when trying to save edited .php files with PATCH method i get an error saying: `ENOENT: no such file or directory, lstat '/usr/local/lib/node_modules/cloudcmd/edward/api/v1/fs/foo.php'`, saving with PUT works fine.

**Comment by coderaiser** [comment]
Can't reproduce in `chrome v68`. Could you please try to clean cache of your browser?

**Comment by csazku** [comment]
Took an other look at it, turns out the config file it was loading contained `"prefix":""` and that did not play well with the cli --prefix option, after deleting said line form the config file and cleaning the browser cache it started working again.

**Comment by coderaiser** [comment]
You can use:

```
cloudcmd --no-cache --save --no-server
```

To prevent such situations in future.
