### ISSUE TITLE
DepracationWarning os.tmpdir()

### ISSUE THREAD

**Issue by Radoslaw-K** [coderaiser/cloudcmd#180]
* **Version** (`cloudcmd -v`):  Unknown
* **NPM Version** `npm -v`:  1.4.21
* **Node Version** `node -v`: 8.11.1
* **OS** (`uname -a` on Linux): Raspberry Pi
* **Browser name/version**: Firefox
* **Used Command Line Parameters**:  sudo npm i cloudcmd -g
* **Changed Config**:  Unknown

Can't install cloudcommander. More details in screenshot below:
https://downloads.intercomcdn.com/i/o/67512874/7666ebbbc67aed62aafe0645/image001.jpg

**Comment by coderaiser** [comment]
Please try to update `npm` with:

```sh
npm i npm -g
```

Your verson is `1.4.21` and last version is `6.1.0`.

And then try:

```sh
npm i cloudcmd -fg
```

Is it helps?

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity
