### ISSUE TITLE
Feature Request: Show current open file and status in editor.

### ISSUE THREAD

**Issue by emahuni** [coderaiser/cloudcmd#183]
* **Version** (`10.5.2`): 
* **Node Version** `9.11.1`: 
* **OS** (`Linux localhost 3.4.0-8115232 #1 SMP PREEMPT Wed Nov 30 19:38:32 KST 2016 armv7l Android` on Linux): 
* **Browser name/version**: 
* **Used Command Line Parameters**: 
* **Changed Config**: 

It's sometimes problematic when you don't remember which file you are looking at. This normally happens when using multiple windows and when you come back to the browser where cloudcmd is open, you actually have to close the file to know what you are looking at. Couldn't there be some form of menu bar, title and other simple editor like features to make this experience pleasent?

**Comment by coderaiser** [comment]
It is a good idea, I should think about it. It can be something like current messages: 
- `save: ok("file.txt")`
- `patch: ok("file.txt")`

But visible all the time.

**Comment by coderaiser** [comment]
Added ability to show file name in `Edit` and `View` with help of a flag `--show-file-name` with f04808c.

Landed in [v10.6.0](https://github.com/coderaiser/cloudcmd/releases/tag/v10.6.0).
