### ISSUE TITLE
DeepWord not showing saved changes

### ISSUE THREAD

**Issue by emahuni** [coderaiser/cloudcmd#184]
* **Version** (`10`): 
* **Node Version** `9.11`: 
* **OS** (`uname -a` on Linux): 
* **Browser name/version**: 
* **Used Command Line Parameters**: 
* **Changed Config**: 

Please see the issue I opened in Deepword repo
https://github.com/cloudcmd/deepword/issues/1

**Comment by coderaiser** [comment]
Thank you :), fixed in deepword@[3.0.9](https://github.com/cloudcmd/deepword/releases/tag/v3.0.9).
