### ISSUE TITLE
Font resource ignores prefix setting

### ISSUE THREAD

**Issue by csazku** [coderaiser/cloudcmd#185]
* **Version** : v10.5.2
* **Node Version** : v10.4.0
* **OS** : Ubuntu 16
* **Browser name/version**: Chrome  v68.0.3440.106
* **Used Command Line Parameters**: --prefix

The font resource ignores the prefix setting and loads directly form /dist
Ex.:
when using prefix **myprefix** the font tries to load from: mydomain.tld/dist/f67260a612bea821fdbf0ad2377ad1e5.woff2
istead of:
mydomain.tld/**myprefix**/dist/f67260a612bea821fdbf0ad2377ad1e5.woff2

**Comment by coderaiser** [comment]
Thank you :)
🔨Fixed with dd7e94c

**Comment by coderaiser** [comment]
✅ Landed in [v5.10.3](https://github.com/coderaiser/cloudcmd/releases/tag/v10.5.3)
