### ISSUE TITLE
error opening webpage

### ISSUE THREAD

**Issue by electather** [coderaiser/cloudcmd#186]
I receive this error every time I try to open the webpage
`ENOENT: no such file or directory, lstat '/usr/lib/node_modules/cloudcmd/download/'
`i tried changing root to /home/download/
but nothing changed. same for leaving it empty and just / 
I'm using pm2 for my projects so I used it for this one too

* **Version** (`v10.5.2`): 
* **Node Version** `v8.11.4`: 
* **OS** (`centos`): 
* **Browser chrome latest**: 
* **-a -u **-p *** --root /home/download/www --port 8050 --no-terminal -s**:

**Comment by electather** [comment]
running this
`cloudcmd --show-config --no-server --root /home/download/www | grep root`
resaluted in 
`| username        | root                           |
| root            | /home/download/www             |
| exportToken     | root                           |
| importToken     | root                           |
root: /home/download/www`
and there was no webservice
running 
`cloudcmd --show-config --port 8050 --root /home/download/www | grep root`
resaulted in 
`| username        | root                           |
| root            | /home/download/www             |
| exportToken     | root                           |
| importToken     | root                           |
root: /home/download/www`
and opening the webpage i get the following message 
`ENOENT: no such file or directory, lstat '/usr/lib/node_modules/cloudcmd/download/'`

**Comment by coderaiser** [comment]
Could you please tell me what `URL` are you using to open the web page? Is it `http://localhost:8000` or `http://localhost:8000/fs/downloads`?

Looks like you trying `http://localhost:8000/download` in this case it is correct behavior.

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity.
