### ISSUE TITLE
Doubled prefix for cloudcmd.common.js over https

### ISSUE THREAD

**Issue by csazku** [coderaiser/cloudcmd#188]
* **Version**: v10.6.0
* **Node Version**:  v10.4.0
* **OS**: Ubuntu 16
* **Browser name/version**: Chrome
* **Used Command Line Parameters**:  --prefix

I installed a haproxy with ssl in front of cloudcmd and now the prefix gets added twice when it's loading the cloudcmd.common.js file. It works fine on http. Also the certificate is a valid wildcard certificate for the domain.
Edit: I also have a redirect to https set up in haproxy.
The console is showing the following error:
load.js:121 GET hxxps://cloudcmd.dom.tld/**myprefix**/**myprefix**dist/cloudcmd.common.js net::ERR_ABORTED 404 (Not Found)
load.js:60 Uncaught (in promise) Error: file **myprefix**dist/cloudcmd.common.js could not be loaded
    at HTMLScriptElement.b (load.js:60)
sw.js:1 Uncaught (in promise) TypeError: Request failed

**Comment by coderaiser** [comment]
Thank you :) fixed with 99a93d7

**Comment by coderaiser** [comment]
✅ Landed in [v10.7.0](https://github.com/coderaiser/cloudcmd/releases/tag/v10.7.0)
