### ISSUE TITLE
ctrl-c console in cloudcmd does not interrupt many programs

### ISSUE THREAD

**Issue by ulno** [coderaiser/cloudcmd#190]
* **Version** (`v10.7.0`): 
* **Node Version** `v8.12`: 
* **OS** (`Linux ulnoiotgw 4.14.69-v7+ #1141 SMP Mon Sep 10 15:26:29 BST 2018 armv7l GNU/Linux`): 
* **Browser name/version**: Chromium, Chrome, Firefox
* **Used Command Line Parameters**: none - started as middleware
* **Changed Config**: interesting option might be `online=false`

Not sure if this belongs here or into https://github.com/replit-archive/jq-console
My problem is that several commands, I run in the console, can not be interrupted by ctrl-c.
For example:
```
python -c "import time; time.sleep(10)"
```

This can be interrupted in a usual console.

Any workaround for this (I have some pretty long running processes and really would like my students to run them via web in the console - and eventually abort them)?

**Comment by coderaiser** [comment]
I suggest you to use [terminal](https://github.com/cloudcmd/gritty) for this purpose, it is not bundled with `Cloud Commander`, but it is much more powerful then `console` which is just a `REPL`, and `terminal` is a terminal emulator.

You can find installation instruction in [Terminal](http://cloudcmd.io/#terminal) part of documentation.

Is it works for you?

**Comment by ulno** [comment]
I would love to use terminal (I can use it and ctrl-c works as expected in it), but the option to sync current folder to console is really nice. Any way to replicate that in terminal?

**Comment by coderaiser** [comment]
The thing is [gritty](https://github.com/cloudcmd/gritty/blob/v3.0.3/server/gritty.js#L62) just starts an application in `terminal` and then sends data there, and receives it from the `terminal`. And there is no way how to detect directory change. `gritty` uses [node-pty](https://github.com/Microsoft/node-pty) for this purpose and it is also do not provide a way to handle this. The only possible way is to parse all entered data in hope that if we found `cd some dir` it will be the command and not just the line in editor opened in `terminal`. `terminal` much more powerful and that is why it is more difficult.

Anyways there is [environment variables](http://cloudcmd.io/#environment-variables) you can use for navigation for example:

```
$coderaiser@cloudcmd:~/cloudcmd$ echo $ACTIVE_DIR
/home
$coderaiser@cloudcmd:~/cloudcmd$ cd $ACTIVE_DIR
$coderaiser@cloudcmd:~$ 
```

**Comment by ulno** [comment]
I wrote a little wrapper script. If a program is started through this, ctrl-c will definitely terminate it - also in the console. However, this script does not support data-input, so if the underlying program needs some data, it will be eaten by this script (improvements welcome).

I still prefer console for lots of programs as it allows my students to use standard copy functions of their respective systems to retrieve content.

```bash
#!/bin/bash
# name the script wrap
# wrap given command to trap ctrl-c and kill cleanly
# execute for example this way: ./wrap python -c "import time; time.sleep(10); print('python done')"

interrupt () {
    echo
    echo Interrupted, killing: $wrapped_id
}

trap interrupt INT TERM HUP

OUTPUT_FILE="$(mktemp /tmp/ctrl-c-wrap.XXXXXXXX)"

#echo -n "" > "$OUTPUT_FILE"
setsid tail -f "$OUTPUT_FILE" &
tail_id=$!

"$@" < /dev/null &>>"$OUTPUT_FILE" &
wrapped_id=$!
wait $wrapped_id

kill $wrapped_id &> /dev/null
sleep 0.5
kill -9 $wrapped_id &> /dev/null
sleep 0.1
kill $tail_id &> /dev/null
rm "$OUTPUT_FILE" &> /dev/null
```

**Comment by coderaiser** [comment]
Here is how it works from the [console](https://github.com/cloudcmd/console-io) perspecitive:
- [client side](https://github.com/cloudcmd/console-io/blob/v7.0.6/client/console.js#L339): when `Ctrl + c` kill.
- [server side](https://github.com/cloudcmd/console-io/blob/v7.0.6/server/index.js#L159) when receive kill call `spawn.kill`.

If you have an ideas how to fix this to work for you case pull requests are welcome :)

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity.
