### ISSUE TITLE
Tab indents in console - why not command completion

### ISSUE THREAD

**Issue by ulno** [coderaiser/cloudcmd#193]
* **Version** (`v10.7.0`): 
* **Node Version** `v8.12`: 
* **OS** (`Linux ulnoiotgw 4.14.69-v7+ #1141 SMP Mon Sep 10 15:26:29 BST 2018 armv7l GNU/Linux`): 
* **Browser name/version**: Chromium, Chrome, Firefox
* **Used Command Line Parameters**: none - started as middleware

Pressing tab in the console indents the command. The expected behavior would be command completion - is there a reason for the indentation behavior. Would it be hard to implement command completion?

**Comment by coderaiser** [comment]
The thing is [console](https://github.com/cloudcmd/console-io) it is just a [REPL](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop) this is possible but to complete command, all possible commands should be received to client side before, it is a great idea for a pull request :). 

To make this possible next things should be done (on unix):
- should be read env variable `$PATH`
- should be received all names of executable files from this directories in `$PATH`
- should be received all directory names when we write `cd`
- should be received all file names every time we press tab after command name
- should be read aliases for bash

For `windows` should be little bit different steps but similar.
All this stuff works in [terminal](https://github.com/cloudcmd/gritty).

Tab is default behavior of [jq-console](https://github.com/replit-archive/jq-console) and I think it can be overridden.

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity.
