### ISSUE TITLE
Single click opens file in new tab instead of selecting it

### ISSUE THREAD

**Issue by csazku** [coderaiser/cloudcmd#194]
* **Version** : v11.1.0
* **Node Version** : v10.11.0
* **OS** : Ubuntu 16 
* **Browser name/version**:  Chrome 69.0.3497.100
* **Used Command Line Parameters**: 
* **Changed Config**: 

As the tile says sometimes clicking on a file just opens it in a new tab, refreshing a few times solves it sometimes, but after changing directory the problem appears again. I'm accessing cloudcmd over https.

The browser's console displays the following errors:
 cloudcmd: sw: install: cloudcmd: Thu Sep 27 2018 18:13:33 GMT+0300 (Eastern European Summer Time)
sw.js:1 Uncaught (in promise) TypeError: Request failed
VM82 cloudcmd.js:1 cloudcmd: sw: updated
currify.js:35 cloudcmd: sw: install: cloudcmd: Thu Sep 27 2018 18:13:33 GMT+0300 (Eastern European Summer Time)
cloudcmd.js:58 cloudcmd: sw: updated
cloudcmd.js:61 Uncaught (in promise) TypeError: window.CloudCmd is not a function
    at VM82 cloudcmd.js:1
    at Generator.next (<anonymous>)
    at n (VM82 cloudcmd.js:1)
    at u (VM82 cloudcmd.js:1)
sw.js:1 Uncaught (in promise) TypeError: Request failed
﻿

​

**Comment by csazku** [comment]
I tried clearing site data/using Incognito mode but it didn't help.
I can't seem to reproduce it on the demo sites.
Forgot to mention I'm using the prefix and the auth settings, could those cause the problem?

**Comment by coderaiser** [comment]
`prefix` and `auth` settings should not cause the problem. Please try to update to [v11.2.0](https://github.com/coderaiser/cloudcmd/releases/tag/v11.2.0) maybe this will fix things up.

**Comment by coderaiser** [comment]
Could you please tell me why do you use `prefix`?

**Comment by csazku** [comment]
Found the problem:
Since it was a pain to proxy the request for the favicon.ico i just refused it with 503, turns out not being able to load that messed up something.
It worked fine up to v10.6 or v10.7 without the favicon

**Comment by csazku** [comment]
As for you question, I run multiple instances of cloudcmd each with a different linux user/port/homedir and I use the prefix to proxy the incoming connection on port 80/443 to the right cloudcmd instance.

**Comment by coderaiser** [comment]
Thank you 👍, fixed with 421b860, landed in [v11.2.1](https://github.com/coderaiser/cloudcmd/releases/tag/v11.2.1).
