### ISSUE TITLE
wrong ServiceWorker script path when using prefix

### ISSUE THREAD

**Issue by panlina** [coderaiser/cloudcmd#195]
Hi,
I'm using cloudcmd behind a proxy, so I set `prefix` to `"/cloudcmd"`, then I found that the browser console gave an error saying:

> `Failed to register a ServiceWorker: The origin of the provided scriptURL ('https://cloudcmd') does not match the current origin`

Digging into the source I found this line of code:
https://github.com/coderaiser/cloudcmd/blob/15abceefeb4ee3b7548307f9bcf87df12aa843e3/client/sw/register.js#L9

From example code in this repo I believe `prefix` is supposed to contain the leading slash(`/`). If that's true, `prefix` will become `"//cloudcmd/"` and the script path to register will become `"//cloudcmd/sw.js"`:
https://github.com/coderaiser/cloudcmd/blob/15abceefeb4ee3b7548307f9bcf87df12aa843e3/client/sw/register.js#L22
That's exactly how the `'https://cloudcmd'` in the error message comes in. Obviously the intended path is `"/cloudcmd/sw.js"`, so I believe `` `/${prefix}/` `` should be `` `${prefix}/` ``.
Am I right?

**Comment by coderaiser** [comment]
Yes you right, thank you :), fixed with b5f9261, landed in [v11.2.2](https://github.com/coderaiser/cloudcmd/releases/tag/v11.2.2) 🎉

**Comment by panlina** [comment]
It's fixed. Thanks for your quick fix. 😄
