### ISSUE TITLE
Getting error while trying to start cloudcmd on Raspberry-Pi

### ISSUE THREAD

**Issue by prashantkt10** [coderaiser/cloudcmd#196]
I want to have cloudcmd on Raspberry-Pi, the cloudcmd is throwing an exception on firing 'cloudcmd' command. Here is the exception:

`url: http://localhost:8066/
(node:4154) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/usr/local/lib/node_modules/cloudcmd/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
(node:4154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4154) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

* **Version** (`cloudcmd -v`): v11.3.0 
* **Node Version** `node -v`: v8.12.0
* **OS** (`uname -a` on Linux): Linux raspberrypi 4.14.69-v7+ #1141 SMP Mon Sep 10 15:26:29 BST 2018 armv7l GNU/Linux
* **Browser name/version**: NA
* **Used Command Line Parameters**: sudo cloudcmd --port 8066 --auth 
* **Changed Config**: NA

**Comment by coderaiser** [comment]
Thank you :). The thing is in [Cloud Commander v11](https://github.com/coderaiser/cloudcmd/releases/tag/v11.0.0) default behavior became to set `open` option by default. It is mean when you starting `Cloud Commander` it tries to open browser window. 

In [v11.3.1](https://github.com/coderaiser/cloudcmd/releases/tag/v11.3.1) this message became more user friendly :). Could you please update to `v11.3.1` and try run `cloudcmd` again. Could you please show me what you see?

To disable opening a browser every time you start `cloudcmd` run:

```
cloudcmd --no-open --save
```

Is it helped?

**Comment by prashantkt10** [comment]
Hey, thanx for quickly responding and acting on to the issue.
I updated to 11.4.0 and got this message on running `cloudcmd` command.
`url: http://localhost:8000/`
`cloudcmd --open: Exited with code 3`

But after giving this command `cloudcmd --no-open --save`, it started working.
Thanx @coderaiser :)
