### ISSUE TITLE
Cannot start since last update

### ISSUE THREAD

**Issue by silkyclouds** [coderaiser/cloudcmd#197]
I am running cloudcommander from a docker container and since last update it keeps restarting again and again : 

here is what logs shows : 

root@phospho:/opt/docker/medias# docker logs cloudcommander
url: http://localhost:8000/
cloudcmd --open: Exited with code 3
url: http://localhost:8000/
cloudcmd --open: Exited with code 3
url: http://localhost:8000/
cloudcmd --open: Exited with code 3
url: http://localhost:8000/
cloudcmd --open: Exited with code 3
url: http://localhost:8000/
cloudcmd --open: Exited with code 3

Any clue what's happening ?

**Comment by coderaiser** [comment]
This is related to #196, on [Cloud Commander v11](https://github.com/coderaiser/cloudcmd/releases/tag/v11.0.0) `open` is set by default.
You should disable this option with command line parameter:

```
cloudcmd --no-open --save
```

Or environment variable `CLOUDCMD_OPEN`:

```
CLOUDCMD_OPEN=false cloudcmd
```

**Comment by coderaiser** [comment]
Fixed docker image, with env variable `cloudcmd_open` in 51c7e41.

**Comment by silkyclouds** [comment]
OK so this will be needed only once at each cloud commander docker container update ? or at each container start ?

**Comment by silkyclouds** [comment]
> Fixed docker image, with env variable `cloudcmd_open` in [51c7e41](https://github.com/coderaiser/cloudcmd/commit/51c7e414ff64456ad2f288eb3ac023976cbad423).

Damn that was fast !!! Thank you so much !

**Comment by coderaiser** [comment]
Landed in [v11.4.1](https://github.com/coderaiser/cloudcmd/releases/tag/v11.4.1)  🎉 :)
