### ISSUE TITLE
Do you have `regeneratorRuntime is not defined` when starting console?

### ISSUE THREAD

**Issue by panlina** [coderaiser/cloudcmd#199]
* **Version** (`cloudcmd -v`): v11.1.0, v11.2.1, v11.2.2, v11.5.3
* **Browser name/version**: Chrome
* **Used Command Line Parameters**: (no arguments)

I just installed the above versions, and run `cloudcmd`, then open the browser and press the console button. The console failed to popup. From devtool it shows:
`regeneratorRuntime is not defined`
in `console.js`.

Don't you get this?

**Comment by panlina** [comment]
Oh guess what, I just installed console-io and launched it alone and there's the same issue. It should be the issue with console-io. The way I repro'ed it is just install latest console-io globally and run `console` directly.

**Comment by coderaiser** [comment]
Thank you :), fixed with https://github.com/cloudcmd/console-io/commit/3d6d7e5b661ae27def9cc48f005390eeb4c65850, landed in [console-io v9.0.1](https://github.com/cloudcmd/console-io/releases/tag/v9.0.1)

Please reinstall `Cloud Commander` with : 

```
npm i cloudcmd -g
```

**Comment by coderaiser** [comment]
Thank you :), fixed with https://github.com/cloudcmd/console-io/commit/3d6d7e5b661ae27def9cc48f005390eeb4c65850, landed in [console-io v9.0.1](https://github.com/cloudcmd/console-io/releases/tag/v9.0.1)

Please reinstall `Cloud Commander` with : 

```
npm i cloudcmd -g
```

**Comment by panlina** [comment]
Thanks for your quick fix, as always. 😄
