### ISSUE TITLE
Right-click to edit saves changes to the wrong file

### ISSUE THREAD

**Issue by davoustp** [coderaiser/cloudcmd#202]
* **Version** (`cloudcmd -v`): 11.2.3 (Docker image tag: 11.2.3-alpine)
* **Node Version** `node -v`: v10.11.0
* **OS** (`uname -a` on Linux): Linux b5098967c6fe 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 Linux
* **Browser name/version**: Google Chrome 69.0.3497.100 (macOS High Sierra 10.13.6 (17G65))
* **Used Command Line Parameters**: None
* **Changed Config**: None

### Problem description:
When a file is first selected then bringing the contextual menu (mouse right-click) to edit it, then the UI asks for confirmation to persist the performed changes to the wrong file, read: not the file which was initially selected for edition.

### How to reproduce:
* Through Cloud Cmd, create an empty directory, and three empty files `A.txt`, `B.txt`, and `C.txt` in it
* Right-click on file **`A.txt`**, then click Edit - edition popup shows
* Enter anything, then close it (using Esc)
=> The UI asks confirmation with message: _Do you want to save changes to `C.txt`_?
If you confirm, this is file _`C.txt`_ which is indeed modified.

It looks like the menu item selection event propagates to the underlying file items underneath and changes the current selection.

**Comment by coderaiser** [comment]
Thank you :), fixed with coderaiser/supermenu@89de761.

**Comment by coderaiser** [comment]
Landed in [v11.5.4](https://github.com/coderaiser/cloudcmd/releases/tag/v11.5.4) 🎉.

**Comment by davoustp** [comment]
Fix confirmed! Thanks a lot for the very quick turnaround.
(am still wondering why I was running such an old version... sorry about that).
