### ISSUE TITLE
sugestion rclone

### ISSUE THREAD

**Issue by mzramna** [coderaiser/cloudcmd#204]
you could implement a thing like rclone into this aplication,something like rclone-browser(https://martins.ninja/RcloneBrowser/) has done but an webui instead of an desktop aplication

**Comment by mzramna** [comment]
i will not pretend to know how hard is to do something like that,but since this has been done once i think it could be used into your project , since this is like the upload to cloud button that you had put into your code,and with your already done system this could be an excelent and unique interface like that

**Comment by coderaiser** [comment]
It is an interesting idea, the only problem with `RcloneBrowser` looks like it is written on `C++`, not `javascript` :). Could you please tell me what features of `rlcone` you like the most that is missing in `Cloud Commander`. I never used `rclone`, so it is really interesting for me.

This functionality could be implemented in some form in a future :).

**Comment by mzramna** [comment]
briefly rclone is a way to manage online services like google drive,ftp,sftp,mega and much others online services,it could just mount as an folder or could upload/download files from the online service like it is local , the project is opensource so you could even look the source code if you want , but it is not necessary, the official website is this: https://rclone.org/

**Comment by coderaiser** [comment]
I'll think about it, thank you :).
