### ISSUE TITLE
[discuss continued] how to eliminate manual socket.io initialization

### ISSUE THREAD

**Issue by panlina** [coderaiser/cloudcmd#205]
Hi,

Previously in #200 we already discussed the `prefix` thing, and that led us to [the proposal of a separate `.listen` method](https://github.com/coderaiser/cloudcmd/issues/200#issuecomment-432335975).

Today I'm learning WebSocket and that gives me some idea.

In a app that uses socket.io, there're 2 servers, serving different requests, 1 for http requests, and 1 for socket.io requests. The `http.createServer` creates the http one, so the other is left to be created some where. Exposing `.listen` is a direct way, but that is letting the user control the detail. The better way is to do this automatically. We can let the middleware initiate the socket.io stuff, just like http initiates the WebSocket communication.

The difficulty is that socket.io requires a http `Server` object to initialize, while we do not have it the moment the middleware is constructed. However, the `Server` object is accessible to the middleware when a request actually happens. I saw it in [this SO answer](https://stackoverflow.com/questions/20548921/access-to-http-server-object-in-node-js-express/20549297#20549297). With this the trick is obvious. We can lazy-initialize socket.io server in the middleware.

I've forked your `console-io` and did an experiment. After the redesign, no manual `.listen` call is needed, and the `server` option is not needed also. You can take a look.

The fork is https://github.com/panlina/console-io.

I've only tried with express 4.

The trick is based on a property that is not documented, and it is warned that it may be dropped in future release, but at least it will work in express 3 and 4, and the advantage it brings is big. Still need to weigh if it is doable.

**Comment by coderaiser** [comment]
That is interesting I'll take a look.

**Comment by panlina** [comment]
And 1 more point against this is: if you have plan to support cloudcmd run on connect or Koa in the future, it may be valueless. ☹️

**Comment by coderaiser** [comment]
So what you propose to do is add one time condition according to [stackoverflow](https://stackoverflow.com/questions/20548921/access-to-http-server-object-in-node-js-express/20549297#20549297):

```js
 var listening = false;
    router.use((req, res, next) => {
        if (!listening) {
            options.server = req.socket.server;
            module.exports.listen(options);
            listening = true;
        }
        next();
    })
```
This looks like a hack 🙂, and not really obvious, but `API` can be simplified a lot, instead of:

```js
   app .use('/', webconsole({
        server,
        online,
    })).use(express.static(DIR));
    
    webconsole.listen({
        server
    });
```
Consumers can use:

```js
  app .use('/', webconsole({
        online,
    })).use(express.static(DIR));
```

But socket server will be initiated on a first request and this can led to slowdown connection.
Have you tried it? Is it much slower or tolerably?

**Comment by coderaiser** [comment]
One more thing that should be considered, is `socket` is reused in [every connected middleware](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/server/cloudcmd.js#L139), so we need to provide `socket` object, and now `listen` method used for this purpose.

**Comment by panlina** [comment]
Being busy these days. I'll give an initial response first. Socket server being initiated on a first request is not a problem I think. I've only tried during development and it didn't show impact. It only affects the first connection anyway. I think it's ok for a admin console app.

Why is the line you showed a similar thing? 😕  I only see a line configuring `prefix`.

**Comment by coderaiser** [comment]
> Why is the line you showed a similar thing? 😕 I only see a line configuring prefix.

You right, similarity in this line only in setting prefix on a request, but web sockets connection initiated in different place.

```js
config('prefix', prefixer(request.baseUrl));
```

**Comment by coderaiser** [comment]
Closed due to [the need of reuse socket object in the middleware](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/server/cloudcmd.js#L139).

Also support of [express v5](https://expressjs.com/en/guide/migrating-5.html) is very important, so we can wait wile it released, or if it's important to you we can proceed in [console-io repo](https://github.com/cloudcmd/console-io) if you test how it works with `express v5 alpha`.
