### ISSUE TITLE
Simultaneous copy jobs failing to copy all files

### ISSUE THREAD

**Issue by Waxyen** [coderaiser/cloudcmd#209]
* **Version** (`cloudcmd -v`): `v11.8.3`
* **Node Version** `node -v`: `v11.4.0`
* **OS** (`uname -a` on Linux): `Linux lavie-server 4.15.0-42-generic #45~16.04.1-Ubuntu SMP Mon Nov 19 13:02:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* **Browser name/version**: `Google Chrome Version 71.0.3578.80 (Official Build) (64-bit)`
* **Used Command Line Parameters**: `/usr/local/bin/cloudcmd --no-open --root /home/media/new/ -c /opt/cloudcmd/config.json`
* **Changed Config**: 

```
{
    "name": "CloudCMD",
    "auth": false,
    "username": "a username",
    "password": "a password",
    "algo": "sha512WithRSAEncryption",
    "editor": "edward",
    "packer": "tar",
    "diff": true,
    "zip" : false,
    "buffer": true,
    "dirStorage": false,
    "online": false,
    "open": false,
    "keysPanel": false,
    "port": 14000,
    "ip": null,
    "root": "/home/media/new",
    "prefix": "",
    "prefixSocket": "",
    "progress": true,
    "contact": false,
    "confirmCopy": true,
    "confirmMove": true,
    "configDialog": false,
    "configAuth": false,
    "oneFilePanel": false,
    "console": false,
    "syncConsolePath": false,
    "terminal": false,
    "terminalPath": "",
    "terminalCommand": "",
    "terminalAutoRestart": true,
    "showConfig": false,
    "showFileName": false,
    "vim": false,
    "columns": "name-size-date-owner-mode",
    "export": false,
    "exportToken": "root",
    "import": false,
    "importToken": "root",
    "importUrl": "http://localhost:14000",
    "importListen": false,
    "log": true,
    "dropbox": false,
    "dropboxToken": ""
}
```
Thanks for building such a great file manager / editor!

Yesterday, I was copying about 10 music albums from my laptop (MacOS 10.14.1) + Chrome. I dragged and dropped them into cloudcmd. I did it via Wi-Fi, which was not very fast at the time, so the copy job took a while per album. I dragged and dropped them one by one, so in the end I had 10 different copy jobs running. When they all finished, about half of the albums did not contain all the songs that should have copied.

When having multiple copy jobs running at the same time, files get skipped. The files that were copied, seemed to have fully copied, so no half songs in my albums.

PS: I've got the root also in the command line parameters, because it didn't get picked up from the config, in case you're wondering.

**Comment by coderaiser** [comment]
Thank you for such detailed information. Mechanism of simultaneous copy not very good displayed in UI, but on a server side everything should work good.

Could you please tell me did you drag files from `finder`? So it was uploading to remote linux server from mac os, right? Problem can be somewhere in [client/dom/directory.js](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/client/dom/directory.js#L16)

**Comment by Waxyen** [comment]
Thank you for your response! I'm sorry mine is a bit late, it's due to the holidays.

Correct, I dragged files from a MacOS Finder window, straight into the browser windows with CloudCMD running on a Linux server.

It is possible that the copy jobs get cancelled due to a slow connection, it does it in a weird way though. Take a music album for example. One of them had 10 songs, clearly marked by an index number 1 - 10. Sometimes it copies song 1, 2, 3, 5, 9, 10, sometimes others, but always skipping songs in between. 

I have tried to recreate the issue, but I could not do it. I tried it the exact same way as I did the first time: from an external harddrive from my MacOS finder window to CloudCMD, also from my internal harddrive directly and both from a Wi-Fi connection. Also, I tried a stable ethernet connection. The only thing that might not be the same: I re-located an access point that was too close to another, and was making the Wi-Fi network slow and interfered with it. So it might actually have been the Wi-Fi connection.

That being said. Isn't it a good idea to build a queue of sorts, where one item gets copied at the time, where the timeout does not trigger when the copy job is running already, however slow? This way, the overall progress in percentages should be easier to show (it now jumps around for every copy job that is running).

**Comment by coderaiser** [comment]
Yes it is a very good idea 🙂, it can be added in [client/dom/directory](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/client/dom/directory.js#L75-L81). And take all names, and then upload them one-by-one, and if error occurs stop process, or suggest to repeat uploading.

**Comment by Waxyen** [comment]
Yeah exactly! If one part of one copy job fails, it can suggest options to the user. I think it should continue other copy jobs, since they don't affect each other, because they are separate copy jobs.

If there is a queue, it might even be nice to show what is in there to the viewer, but that is even more something for the future. I know how busy it can be as a developer, and everything needs to be tested. I don't want to put any pressure on you. I don't have much time myself to have a go at it. This project seems interesting enough to be doing that though.

**Comment by coderaiser** [comment]
That's a great idea for a pull request 🙂, will see maybe someone will take it 😉.

**Comment by PowerOlive** [comment]
... terminal can do it

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝

**Comment by Argonaut13** [comment]
This issue still persists five years later. Uploading large number of files just refuses to upload most of them, very frustrating when trying to migrate a directory from my local machine to Cloud Commander

**Comment by coderaiser** [comment]
Are you up to make PR to improve things?
