### ISSUE TITLE
Can't view files on Windows

### ISSUE THREAD

**Issue by Adrek** [coderaiser/cloudcmd#212]
* **Version** (`cloudcmd -v`): 11.8.3
* **Node Version** `node -v`: v10.14.1
* **OS** (`uname -a` on Linux): Windows 10 - Version 1809
* **Browser name/version**: Firefox and Chrome
* **Used Command Line Parameters**: cloudcmd
* **Changed Config**: 

Hello everyone and congratulations for this great project

I just installed Cloud Commander in Windows to visualize my local files inside my PC, and according to the tutorial it says that when I run the command **cloudcmd** I should appear in a visual way the files, however only the discs appear but I can not enter any .

I double click on any of the local disks and nothing happens. If I right click on a disk and select "View", I get the message "_EISDIR: illegal operation on a directory, read_".
[https://imgur.com/a/WqV1vF9](https://imgur.com/a/WqV1vF9)

I do not know if it does not work in Windows, only in Linux, or suddenly I'm skipping a step.

Also, thank you very much for your support

**Comment by coderaiser** [comment]
Fixed with help of [tolerant-readdir](https://github.com/coderaiser/readify/blob/v6.0.4/lib/tolerant-readdir.js) in [readify@6.04](https://github.com/coderaiser/readify/releases/tag/v6.0.4).
Please re-install `Cloud Commander` with:

```sh
npm i cloudcmd -g
```

Is it helped?

**Comment by Adrek** [comment]
Great, now I can see the files. Thank you very much for your enormous work.
