### ISSUE TITLE
Feature Request:  Change font size dynamically

### ISSUE THREAD

**Issue by 8nrGDjC5NgWS** [coderaiser/cloudcmd#213]
* **Version** (`cloudcmd -v`): v11.8.3
* **Node Version** `node -v`: v11.8.3
* **OS** (`uname -a` on Linux): Linux cloudcmd 4.14.82-gentoo-20181125-1328 #1 SMP Sun Nov 25 13:33:05 CST 2018 x86_64 GNU/Linux
* **Browser name/version**: Chromium Version 70.0.3538.67 (Developer Build) (64-bit)
* **Used Command Line Parameters**: --root /data --prefix cloudcmd --no-open --terminal --terminal-path gritty --no-console
* **Changed Config**:   (Don't know what this is)

I would like to see an option somewhere where I can override the default font size with a custom smaller font size.  Currently, the only way I can see how to do this is to modify the original source files and re-build the app? (but I don't know how to do that either)

The default font size 16, is pretty big on my screen.   And is way way way to big on my phone.  It's like looking at the app through a magnifying glass.

**Comment by 8nrGDjC5NgWS** [comment]
Oops... Node version is   v11.3.0

**Comment by coderaiser** [comment]
That's a good idea. First thing you can do is edit file [css/style.css](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/css/style.css#L14) and set smaller font-size.
Then you can run (in cloned repo with installed `npm` dependencies) run:

```
npm run build:start:dev
```

And check result in your browser.
To have ability dynamically change font-size it's value should be read from `json/config.json` and then dynamically added from client or server side. I think better to do this from server side.

It can be added to [html/index.html](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/html/index.html#L15-L17) and then rendered in [server/route.js](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/server/route.js#L160-L168).

**Comment by coderaiser** [comment]
> And is way way way to big on my phone. It's like looking at the app through a magnifying glass.

Maybe it is because font-size became `26px` in a small screens, you can change it to smaller value in [css/query.css](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/css/query.css#L97).

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
