### ISSUE TITLE
Chrome 71 does not display anything on first open.

### ISSUE THREAD

**Issue by 8nrGDjC5NgWS** [coderaiser/cloudcmd#214]
* **Version** (`cloudcmd -v`): v11.8.3
* **Node Version** `node -v`: v11.3.0
* **OS** (`uname -a` on Linux): Linux cloudcmd 4.14.82-gentoo-20181125-1328 #1 SMP Sun Nov 25 13:33:05 CST 2018 x86_64 GNU/Linux
* **Browser name/version**: Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* **Used Command Line Parameters**: --root /data --prefix cloudcmd --no-open --terminal --terminal-path gritty --no-console
* **Changed Config**:   (Not sure what this is)

Chrome browser, version 71, on both Windows and Android....  When I first go to terminal (Shift + ~), nothing appears.  I have to close (Shift + Escape) and re-open (Shift + ~) the terminal, in order to get anything to display.  All the data entered in the first open is still there in the second open.

This does not happen on Chromium browser, version 70, on Linux.  It also did not happen in Chrome browser on Android (before I updated it today.  I do not know which version it was on before I updated it).

Therefore, I suspect that something change in Chrome version 71 that makes the first open of terminal to not display any data.

**Comment by coderaiser** [comment]
Yes, there is such a thing, looks like something have changed in chrome after `v70`, I have no idea what can it be  🤷🏽‍♂️, in firefox everything works good. Actually this looks like a bug of chrome.

**Comment by coderaiser** [comment]
Landed in [v11.8.4](https://github.com/coderaiser/cloudcmd/releases/tag/v11.8.4) 🎉.
