### ISSUE TITLE
Feature request - Terminal - Support for bash shortcuts

### ISSUE THREAD

**Issue by 8nrGDjC5NgWS** [coderaiser/cloudcmd#215]
* **Version** (`cloudcmd -v`): v11.8.3
* **Node Version** `node -v`: v11.3.0
* **OS** (`uname -a` on Linux): Linux cloudcmd 4.14.82-gentoo-20181125-1328 #1 SMP Sun Nov 25 13:33:05 CST 2018 x86_64 GNU/Linux
* **Browser name/version**: Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* **Used Command Line Parameters**: --root /data --prefix cloudcmd --no-open --terminal --terminal-path gritty --no-console
* **Changed Config**: (Not sure what this is)

Is it possible to have support for the bash shortcuts when in terminal?  I.e.   Ctrl-w, Ctrl-a, Ctrl-e, Ctrl-k, etc?

I discovered that Ctrl-w closes completely the browser tab instead of deleting the last word, as I had expected.

**Comment by coderaiser** [comment]
That's possible, file `client/modules/terminal` should be edited for this purpose, it can be something like this on `open`:

```js
window.addEventListener('keydown', (e) => {
    const W = 87; 
    if (e.ctrlKey && e.keyCode === W)
        e.preventDefault();
});
```

And `window.removeEventListener('keydown')` on close.

**Comment by coderaiser** [comment]
Also you can add `preventDefault` to [client/key/index.js](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/client/key/index.js#L407-L413) and add`W` to [client/key/key.js](https://github.com/coderaiser/cloudcmd/blob/master/client/key/key.js#L51).

**Comment by coderaiser** [comment]
Closed due to inability to handle `Ctrl` + `W` with help of `preventDefault`. Could be revised when `xterm` will have ability to remap keys in https://github.com/xtermjs/xterm.js/issues/487#issuecomment-273887525.
