### ISSUE TITLE
Issue executing commands in console when default root was changed and path sync is turned on

### ISSUE THREAD

**Issue by godfuture** [coderaiser/cloudcmd#216]
I am using the docker container and have set the default path for new sessions. This works fine. The web gui starts at the desired location. The new default is then displayed as root "/". And here the problem starts. When using path sync for console, every command will fail. I have changed the working dir to default with "cd". The commands from this position are working then.

* **Version** (`cloudcmd -v`): docker 11.8.3-alpine
* **Node Version** `node -v`: 
* **OS** (`uname -a` on Linux): 
* **Browser name/version**: 
* **Used Command Line Parameters**: 
* **Changed Config**:

**Comment by coderaiser** [comment]
The thing is [console](https://github.com/cloudcmd/console-io) has no idea what the `root` is, you can disable `sync-console-path` option.

>  I have changed the working dir to default with "cd"

Have you used `alias`? or just changed dir one time with `cd`?

**Comment by godfuture** [comment]
Only one time "cd" without any further parameters. Do you think both in the same time won't be possible?

**Comment by coderaiser** [comment]
I think it is possible, but should be added support of `root` to [console-io](https://github.com/cloudcmd/console-io/blob/v10.0.1/server/index.js#L129).

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
