### ISSUE TITLE
find -empty does neiter work in console nor in terminal

### ISSUE THREAD

**Issue by godfuture** [coderaiser/cloudcmd#217]
I am using the docker container and try to remove empty folders in batch. Therefore I need the tool find. Unfortunately I can't use -empty option. I always get the help output instead the result. Without -empty it works just fine.

* **Version** (`cloudcmd -v`): docker 11.8.3-alpine
* **Node Version** `node -v`: 
* **OS** (`uname -a` on Linux): 
* **Browser name/version**: 
* **Used Command Line Parameters**: 
* **Changed Config**:

**Comment by coderaiser** [comment]
Looks like `find` in `alpine linux` has no `-empty` option, try to use `debian`-based docker images with:

```
docker run -t --rm -v ~:/root -v /:/mnt/fs -w=/root -p 8000:8000 coderaiser/cloudcmd
```

Is it helps?

**Comment by coderaiser** [comment]
This is an official `alpine` image from [node.js team](https://github.com/nodejs/docker-node), they are using [latest alpine v3.8](https://github.com/nodejs/docker-node/blob/master/11/alpine/Dockerfile) you can [ask maintainers of docker images for alpine linux](https://github.com/gliderlabs/docker-alpine/issues) about it.
