### ISSUE TITLE
Add authorization info

### ISSUE THREAD

**Issue by coderaiser** [coderaiser/cloudcmd#219]
Would be great to add information about authorization and generation of password hash described in
https://github.com/coderaiser/cloudcmd/pull/218#issuecomment-453543401 to [Authorization](https://github.com/coderaiser/cloudcmd/blob/master/HELP.md#authorization) part of `HELP.md`.

It is related to #72, #147.

**Comment by lukalafaye** [comment]
They were overwritten and the password was hashed. However, the username and password did not work when I tried to sign in on the service (after restarting it). I tried several times, getting the same error.

**Comment by coderaiser** [comment]
How do you start `Cloud Commander`?

**Comment by lukalafaye** [comment]
I started `cloudcmd` executing `/usr/bin/cloudcmd`. I also tried reinstalling the package with npm and there were no changes

**Comment by coderaiser** [comment]
What browser do you use? Is it works now?

**Comment by stingrayai** [comment]
same issue when trying to read username/password from config.json.

**Comment by coderaiser** [comment]
@stingrayai could you please provide more details :)
