### ISSUE TITLE
Cloud Commander cannot read ##files

### ISSUE THREAD

**Issue by arch1mede** [coderaiser/cloudcmd#223]
I am running thelounge (irc client) and I am in a ##channel, it cannot read the ##log file, gives a read error

ENOENT: no such file or directory, scandir '/etc/thelounge/logs/arch1mede/freenode-30e2-46e3-9a9a-dc0876b7aadd/#'

* **Version** (`cloudcmd -v`): v11.8.3
* **Node Version** `node -v`: v8.10.0
* **OS** (`uname -a` on Linux): Linux ubuntu 4.15.0-43-generic
* **Browser name/version**: Chrome Version 71.0.3578.98
* **Used Command Line Parameters**: 
* **Changed Config**:

**Comment by coderaiser** [comment]
Thank you, it is look like a bug

**Comment by coderaiser** [comment]
Looks like the problem in [client/dom/rest.js](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/client/dom/rest.js#L188). `#` sign replaced only ones, but all `#` signs should be replaced. Would be great to move it out to a function, and create file `rest.spec.js` with a test of this function similar to [common/cloudfunc.spec.js](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/common/cloudfunc.spec.js#L9)

**Comment by arch1mede** [comment]
Well this file is named '##some irc channel log' and it's displaying #some irc channel log in the window

Without the extra # and '

**Comment by coderaiser** [comment]
Landed in [v11.8.4](https://github.com/coderaiser/cloudcmd/releases/tag/v11.8.4) 🎉.
