### ISSUE TITLE
No icons, double click is not recognized

### ISSUE THREAD

**Issue by sparx82** [coderaiser/cloudcmd#224]
Hi

I really love CloudCmd and use it almost daily. But starting a some versions ago (sorry, don't remember which one, but a couple of month ago), I have a strange issue. I open CloudCmd and then double click on a directory (CloudCmd root is /). The directory opens and then I click on the two dots to go back again. Now, all icons are disappeared and when i double click on a directoy, nothing happens. This only happens with the root directory (/), if I go deeper, I can go back and forth without problems, but as soon as I open the root directory again, the icons are gone and no double click is recognized. The only thing I could do is to refresh the page (F5). Then the icons are there again and it works. 

* **Version** (`cloudcmd -v`): 11.8.3
* **Node Version** `node -v`: 11.8.0
* **OS** (`uname -a` on Linux): Linux DebianNAS 4.19.0-0.bpo.1-amd64 #1 SMP Debian 4.19.12-1~bpo9+1 (2018-12-30) x86_64 GNU/Linux
* **Browser name/version**:  Google Chrome Version 71.0.3578.98 (does NOT happen with IE, but also with Chrome Browser on my Android device)
* **Used Command Line Parameters**: none
* **Changed Config**: 

```
{
    "name"              : "",
    "auth"              : true,
    "username"          : xyz,
    "password"          : xyz,
    "algo"              : "sha512WithRSAEncryption",
    "editor"            : "edward",
    "packer"            : "tar",
    "diff"              : true,
    "zip"               : true,
    "buffer"            : true,
    "dirStorage"        : true,
    "online"            : true,
    "open"              : false,
    "oneFilePanel"      : true,
    "keysPanel"         : true,
    "port"              : 8003,
    "ip"                : null,
    "root"              : "/",
    "prefix"            : "", 
    "progress"          : true,
    "confirmCopy"       : true,
    "confirmMove"       : true,
    "showConfig"        : false,
    "contact"           : true,
    "configDialog"      : true,
    "console"           : true,
    "syncConsolePath"   : false,
    "terminal"          : false,
    "terminalPath"      : "/",
    "vim"               : false,
    "columns"           : "name-size-date-owner-mode"
}

```

**Comment by coderaiser** [comment]
Hi,
Very pleasant to read this 🙂.

This can be related to service workers. You can try this things:
- open `Cloud Commander` in incognito mode, is it reproduced?
- open console, is it shows something?
- try to remove all service workers in `Chrome Developer Tools` (`Application` -> `Clear Storage`)

Is it helps?

**Comment by sparx82** [comment]
Unfortunately none of these help (and the console stays completely empty). But what I just found out: If I0m at the non-working state and I hit the reload button the icons appear and the double click works again. But not only for this time but forever. Even if I go up and down the directory tree...

**Comment by coderaiser** [comment]
Could you please try [demo](https://cloudcmd.herokuapp.com/), is it works in the same way for you?

**Comment by sparx82** [comment]
I don't have this problem there, this works perfectly!

**Comment by coderaiser** [comment]
OK, if you on `Application` click `Clear Storage` and then reload the page, it will log information from `Service Worker`, could you please try this on a `demo` and `your instance`.

**Comment by Waxyen** [comment]
How have you currently installed CloudCMD? I have it running inside a docker container, which is running like a charm.

I have built my own docker image for it, because I want to run CloudCMD as a specific user (needs it for file access). Maybe you can give that a shot?

```
FROM node

RUN groupadd -r files && useradd -r -u 1002 -g files files &&\
    npm i cloudcmd -g && \
    chown -R files:files /var/log

USER media

CMD cloudcmd --no-open --root /mnt/fs -c /config/config.json
```

PS: I have specified the `root` and `config` in the CMD, because it does not pick it up somehow. Need to dive into it further, but for now I'm happy.

**Comment by coderaiser** [comment]
I deploy with help of something like this [Heroku Deploy](http://cloudcmd.io/#deploy) it is a clean install of `master` branch.

Yes everything works good on a fresh install, have you tried it?
What with service workers? You can also try open your instance with a different browser.

It should not relate to configuration change you made.

**Comment by sparx82** [comment]
> OK, if you on `Application` click `Clear Storage` and then reload the page, it will log information from `Service Worker`, could you please try this on a `demo` and `your instance`.

Can do that, but where do I see the logged information? What do you need?

**Comment by coderaiser** [comment]
Here is how it looks:
<img width="521" alt="screen shot 2019-01-30 at 5 10 32 pm" src="https://user-images.githubusercontent.com/1573141/51990607-0ea53f00-24b2-11e9-8c91-69f282d30b4f.png">

Look at `Developer Tools Console`.

**Comment by sparx82** [comment]
Ok, I was looking there but was not sure because it looks similar. Your demo:

![image](https://user-images.githubusercontent.com/17567952/51991255-009ff000-24ab-11e9-99fc-dc40d6552d66.png)

My installation:

![image](https://user-images.githubusercontent.com/17567952/51991053-8ec7a680-24aa-11e9-9073-525b54055fd5.png)

**Comment by coderaiser** [comment]
OK, looks like `Servise Worker` installed correctly. Could you plese reload page, keeping `Console` open, check is Network Tab has red colored items, and attach a screenshot of a Cloud Commander page without icons.

**Comment by sparx82** [comment]
- Console stays completely empty
- Network tab shows no red items:
![image](https://user-images.githubusercontent.com/17567952/52033258-a2175800-2524-11e9-948e-a1861415a6a9.png)

Screenshot of CloudCmd if working:

![image](https://user-images.githubusercontent.com/17567952/52033290-beb39000-2524-11e9-9e03-2b6ffc1c4b23.png)

And with disappeared icon:

![image](https://user-images.githubusercontent.com/17567952/52033303-d3902380-2524-11e9-995c-09fd75bf7f38.png)

**Comment by coderaiser** [comment]
That is very strange, could you please try `firefox` is it behave in a same way?

**Comment by sparx82** [comment]
Same issue with Firefox. Only IE seems to not have this problem here.

**Comment by coderaiser** [comment]
I can't reproduce this on a fresh install of `Cloud Commander`, could you make a fresh install and check it.

**Comment by coderaiser** [comment]
Run `npm i cloudcmd -g` this will be enough.

**Comment by sparx82** [comment]
`root@xyz:~# npm i cloudcmd -g`
`/usr/bin/cloudcmd -> /usr/lib/node_modules/cloudcmd/bin/cloudcmd.js`
`+ cloudcmd@11.8.3`
`updated 5 packages in 52.866s`

And this has no effect (still the same issue),

**Comment by coderaiser** [comment]
Could you please tell me name of a directory that breaks all the things?

**Comment by coderaiser** [comment]
Did something change with update `Cloud Commander` to [v11.8.5](https://github.com/coderaiser/cloudcmd/releases/tag/v11.8.5)?

**Comment by ulno** [comment]
Problem is gone for me. Just upgraded and icon issues are gone.
