### ISSUE TITLE
ARM64 / AARCH64

### ISSUE THREAD

**Issue by D4rkSl4ve** [coderaiser/cloudcmd#226]
Wondering if you are planning on having your Cloud Commander working on the ARM64 / AARCH64 type CPUs?  If you already have some, please point me to it.

**Comment by coderaiser** [comment]
`Cloud Commanders` works on top of `node.js`, I think should be node binaries compiled for `arm64`, you can try [node-linux-arm64](https://www.npmjs.com/package/node-linux-arm64), for example.

Is it works for you?

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity.
