### ISSUE TITLE
Cloudcommander does not default to cloudcmd.json

### ISSUE THREAD

**Issue by ShalokShalom** [coderaiser/cloudcmd#227]
* **Version** (`cloudcmd -v`):  11.8.4
* **Node Version** `node -v`: 10.15.1
* **OS** (`uname -a` on Linux): 4.9.130 Debian
* **Browser name/version**: Firefox 64
* **Used Command Line Parameters**: -c
* **Changed Config**: yes

I change my config in ~./.cloudcmd.json and Cloudcommand refuses to accept it. 
I start the app with -c and specify the path, which works.

find . -name .cloudcmd.json finds only this single config file. 

Solved for me, just a feedback, thanks :)

**Comment by coderaiser** [comment]
How did you change config of `Cloud Commander`?

**Comment by ShalokShalom** [comment]
I use an editor? And before that, I think my colleague used the build in F10 function.

**Comment by coderaiser** [comment]
I can't reproduce this.
