### ISSUE TITLE
Did I broke something?   Is it not just me?

### ISSUE THREAD

**Issue by randomaustralian** [coderaiser/cloudcmd#228]
is it not just me or did i break something?

Using current CentOS Release.
cloudcmd worked right before i performed a "npm i cloudcmd -g"
so i tried a "--forced" tag and its still not working.

> [root@houston ~]# npm i cloudcmd -g --force
> npm WARN using --force I sure hope you know what you are doing.
> /usr/bin/cloudcmd -> /usr/lib/node_modules/cloudcmd/bin/cloudcmd.js
> /usr/lib
> └── cloudcmd@11.8.4
> 
> [root@houston ~]# cloudcmd
> /usr/lib/node_modules/cloudcmd/server/config.js:55
>     ...rootConfig,
>     ^^^
> 
> SyntaxError: Unexpected token ...
>     at createScript (vm.js:56:10)
>     at Object.runInThisContext (vm.js:97:10)
>     at Module._compile (module.js:549:28)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
>     at Module.require (module.js:504:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/usr/lib/node_modules/cloudcmd/bin/cloudcmd.js:12:16)
> [root@houston ~]#

**Comment by coderaiser** [comment]
Could you please tell me what version of `node.js` are you using?

```sh
node -v
```

**Comment by randomaustralian** [comment]
yum update seems to think its the latest version.

> [root@houston ~]# node -v
<  v6.16.0
> [root@houston ~]#

**Comment by coderaiser** [comment]
Please update to node `v10`, or at least node `v8` https://github.com/coderaiser/cloudcmd/issues/206#issuecomment-441188410.

**Comment by randomaustralian** [comment]
i used this to install the repo...

https://linuxize.com/post/how-to-install-node-js-on-centos-7/

**Comment by coderaiser** [comment]
You better use [nvm](https://linuxize.com/post/how-to-install-node-js-on-centos-7/#2-install-node-js-using-nvm).

**Comment by randomaustralian** [comment]
its working again so i'm happy
