### ISSUE TITLE
Missing config file

### ISSUE THREAD

**Issue by ShalokShalom** [coderaiser/cloudcmd#229]
After installing NodeJS from the EPEL repository, appears no cloudcmd.json

CentOS 7

**Comment by coderaiser** [comment]
Did you install `Cloud Commander` or `node.js`? Are you talking about `~/.cloudcmd.json`? Does `node.js` installer remove `.cloudcmd.json`?

**Comment by coderaiser** [comment]
`~/.cloudcmd.json` created only when you change any options, there is no such file by default.

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity.

**Comment by ShalokShalom** [comment]
I am talking about Cloud commander, obviously. And yes, I was talking about .cloudcmd.json, your only config file, so far as I am instructed. There should be one by default, IMHO.
