### ISSUE TITLE
Broken UI, plugins.js blocked (behind NGINX reverse proxy)

### ISSUE THREAD

**Issue by Hyldig** [coderaiser/cloudcmd#230]
* **Version**: 11.8.4
* **Node Version**: 10.15.1
* **OS**: Ubuntu 18.04 (Proxmox LXC)
* **Browser name/version**: Chrome 72

CloudCMD running behind NGINX reverse proxy, attached is configuration. Excact same configuration used on other services without issues (Proxmox WEB UI, Home assistant, NextCloud). Attached is NGINX config.

Accessing the service directly on IP:8000 is working fine.

Accessing through a NGINX Reverse proxy is giving the following error in Chrome dev console, and UI is broken. (clicking buttons, dosn't fold out settings correctly)
"Refused to execute script from 'https://***DOMAIN***/plugins.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled."

[nginx.txt](https://github.com/coderaiser/cloudcmd/files/2884715/nginx.txt)

**Comment by coderaiser** [comment]
Thank you 🙂, fixed with e4caeb6. Landed in [v11.8.5](https://github.com/coderaiser/cloudcmd/releases/tag/v11.8.5).

**Comment by Hyldig** [comment]
Thank you, can confirm working :)

**Comment by coderaiser** [comment]
That's great 🙂
