### ISSUE TITLE
Feature request - batch file rename

### ISSUE THREAD

**Issue by pbtsrc** [coderaiser/cloudcmd#231]
Batch/multi/bulk file rename. Personally I need to add counters (001, 002, ...) to file names, but it  would be nice to have other common multi-rename features (timestamps, string substitutions, etc) .

**Comment by coderaiser** [comment]
That's an interesting and very useful idea. I should think about it. Meanwhile you can bulk rename files with help of an editor, using: `Ctrl + M`.

**Comment by coderaiser** [comment]
Added ability to use batch file rename in [v12.1.0](https://github.com/coderaiser/cloudcmd/releases/tag/v12.1.0) 🎉.

How is it works for you 🙂?
