### ISSUE TITLE
More detailed progress dialog

### ISSUE THREAD

**Issue by bhaal2** [coderaiser/cloudcmd#232]
* **Version** (`cloudcmd -v`): v11.8.5
* **Node Version** `node -v`: 8.10
* **OS** (`uname -a` on Linux): Ubuntu
* **Browser name/version**: Chrome 70.0.3538.77
* **Used Command Line Parameters**: 
* **Changed Config**: 

Feature request:

Hi there, I just found this software and was quite excited about it, I use MC quite a lot to move large amounts of data between hard drives on remote machines.  It's a pain to ssh in etc.  So what I was hoping for with cloudcmd was that when I was copying files etc, I'd get a more detailed dialog of whats happening, similar to what MC shows.  And it would be a good idea if this dialog would survive a page refresh, like after the computer has been asleep.  Sometimes when I am moving data between drives it can take many hours.  Hopefully this is something which can be considered.  Thanks

I am not familiar with nodeJS so am not in a position to help at the moment.

**Comment by coderaiser** [comment]
This is a very good idea, a lot technical designs should be made to make it possible.  I'll think about it.

**Comment by coderaiser** [comment]
Landed in [v12.0.0](https://github.com/coderaiser/cloudcmd/releases/tag/v12.0.0) 🎉.
