### ISSUE TITLE
Feature Request: Access Control (Read/Delete/Move/Rename etc...)

### ISSUE THREAD

**Issue by yafacex** [coderaiser/cloudcmd#233]
I send this url to people to see,but afraid of something to be deleted.

**Comment by coderaiser** [comment]
That's interesting, but requires a lot modifications. Need help with this.

**Comment by coderaiser** [comment]
Do you have any ideas how it should look like?

**Comment by PowerOlive** [comment]
there should be password

**Comment by PowerOlive** [comment]
that's what actually ftp does
not by http
:)

**Comment by coderaiser** [comment]
@PowerOlive there is ability to set `username` and `password`, I'm talking about `UI`. 
How and where should be configured `Access Control`.

**Comment by PowerOlive** [comment]
a level db would be nice

**Comment by PowerOlive** [comment]
i mean level database access
so it can also use search for files

**Comment by coderaiser** [comment]
@PowerOlive do you mean [leveldb](https://github.com/google/leveldb)? How do you think it should sync with a file system?

**Comment by PowerOlive** [comment]
:) i am not familar with database

**Comment by PowerOlive** [comment]
i think the minio.io like object hosting would be nice

**Comment by PowerOlive** [comment]
cloudcmd should have not only cmd
but focus on cloud i think

**Comment by PowerOlive** [comment]
is it possible to add more user
with different permission
like
public can download files from /public
admin can do anything
there's only one user now?

**Comment by PowerOlive** [comment]
so now cloudcmd show a box to let me enter password
will it possible to change how that work?

**Comment by PowerOlive** [comment]
like giving a html like owncloud or nextcloud

**Comment by PowerOlive** [comment]
no js is the advantage of the cloudcmd

**Comment by PowerOlive** [comment]
that solve it?

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
