### ISSUE TITLE
Error on copy/delete

### ISSUE THREAD

**Issue by csazku** [coderaiser/cloudcmd#234]
* **Version**:  v12.0.0
* **Node Version**: v10.11.0
* **OS** : ubuntu 16
* **Browser name/version**: Chrome 73.0.3683.86
* **Used Command Line Parameters**:  --prefix
* **Changed Config**: 

I get the following error when copying/deleting files/folders:

`Error: ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/cloudcmd/node_modules/@cloudcmd/fileop/socket.io/?EIO=3&transport=polling&t=MdYczWi'`

**Comment by coderaiser** [comment]
Looks like it is relates to `service workers`. [Clear application storage](https://github.com/coderaiser/cloudcmd/issues/224#issuecomment-458951967) and reload the page. Is it helps?

**Comment by csazku** [comment]
Tried clearing the application storage and running in an incognito window but I still get the same error.

**Comment by coderaiser** [comment]
Can you reproduce this on demo site: https://cloudcmd.herokuapp.com/ ?

**Comment by csazku** [comment]
Works fine on that one.
Also forgot to mention I'm using the `--port` parameter as well (sorry about that).

**Comment by coderaiser** [comment]
`port` should not related to this problem. Could you please try another browser, `chrome canary` or `firefox`. I think the problem is `cache of service worker`.

**Comment by csazku** [comment]
Tried in firefox 66.0.2 the error is still there.
Installed cloudcmd on my local machine started it up with no parameters it's still the same.
The request (`http://localhost:8000/fileop/socket.io/?EIO=3&transport=polling&t=MddvScF`) returns `HTTP 404`
and the following error appears in the terminal: 
`Error: ENOENT: no such file or directory, stat '/usr/lib/node_modules/cloudcmd/node_modules/@cloudcmd/fileop/socket.io/?EIO=3&transport=polling&t=MddvScF'`

**Comment by coderaiser** [comment]
Could you please update to `v12.0.2`?

**Comment by csazku** [comment]
Did it, the problem is still there.
Also the `-v` flag reports v12.0.0 instead of v12.0.2.

**Comment by coderaiser** [comment]
So it's not `v12.0.2` if `-v` flag reports `v12.0.0`. Please reinstall with:

```sh
npm i cloudcmd@latest --force
```

**Comment by csazku** [comment]
```
root@cloudcmd:~# npm i cloudcmd@latest -g --force
npm WARN using --force I sure hope you know what you are doing.
/usr/local/bin/cloudcmd -> /usr/local/lib/node_modules/cloudcmd/bin/cloudcmd.js
+ cloudcmd@12.0.0
updated 1 package in 3.872s
root@cloudcmd:~# cloudcmd -v
v12.0.0
```

also tried downloading the release from github:
```
root@cloudcmd:~# tar -xzf cloudcmd-v12.0.2.tar.gz
root@cloudcmd:~# cloudcmd-v12.0.2/bin/cloudcmd.js -v
v12.0.0
```

**Comment by coderaiser** [comment]
You right, there was a problem with `npm publish`, please try again to install `Cloud Commander`.

**Comment by csazku** [comment]
It's working now.
Thank you.
