### ISSUE TITLE
V12 on iPad unable to navigate into folders

### ISSUE THREAD

**Issue by lignumaqua** [coderaiser/cloudcmd#235]
* **Version** : 12.0 
* **Node Version** `node -v`: n/a
* **OS** : Any
* **Browser name/version**: Safari on iPad
* **Used Command Line Parameters**: 
* **Changed Config**: 

There seems to have been a major change in V12 that breaks CloudCommander in Safari on an iPad. When you tap a folder to open it, instead you get a window showing a JSON file describing the folder instead. This happens not only in my local version but also in the two demo versions on the GitHub page. It isn’t possible to navigate at all. 

If I had to guess I would suspect the change that edits a file when return is pressed is interpreted incorrectly in a touch enabled UI. Reverting to 11.8.6 fixes the problem. 

CloudCommander is great for remote access to a server on an iPad. Many thanks for all the work you put into it.

**Comment by coderaiser** [comment]
Thank you 🙂, fixed with 46102d1, landed in [v12.0.1](https://github.com/coderaiser/cloudcmd/releases/tag/v12.0.1) 🎉

**Comment by lignumaqua** [comment]
Thanks for the extremely rapid response. Partly fixed! I can now navigate into folders, but any click on a file or anywhere that isn’t a folder, brings up a pop-up window saying "No file selected!"

I suspect the same issue. Any touch is being interpreted as pressing return, and it tries to open a file for viewing. However nothing is selected. In fact it isn’t possible to select anything. 

Automatic responses like this are really tricky to make work on a touch UI.

**Comment by coderaiser** [comment]
Thanks a lot for you feedback 🙂, fixed with 813f1c7, landed in [v12.0.2](https://github.com/coderaiser/cloudcmd/releases/tag/v12.0.2) 🎉.

Is it works for you?

**Comment by lignumaqua** [comment]
Thanks! Better, but not correct. You can now select a file but it opens immediately. It isn’t possible to just select a file for copying without also opening it. 

The way touch works with folders is, first touch selects, then second touch opens. That works well. I guess the same logic could work with files? First touch selects, second touch opens. 

Or, alternatively, could this entire feature be completely disabled for touch? It worked well before.  :-)

**Comment by coderaiser** [comment]
> Thanks! Better, but not correct. You can now select a file but it opens immediately. It isn’t possible to just select a file for copying without also opening it.

This should be fixed in `v12.0.2`. Can you reproduce this behavior on https://cloudcmd.herokuapp.com/?

**Comment by lignumaqua** [comment]
Now works as expected on herokuapp.com. Thanks!
