### ISSUE TITLE
hi the hereoku app.json needs update

### ISSUE THREAD

**Issue by PowerOlive** [coderaiser/cloudcmd#236]
using heroku button

**Comment by PowerOlive** [comment]
The content of app.json is not valid; please see app.json Schema for more information.

The file does not contain a valid JSON entity.

**Comment by PowerOlive** [comment]
also what the fuck https://cloudcmd.herokuapp.com/index.html shows pornhub

**Comment by PowerOlive** [comment]
https://cloudcmd.now.sh/index.html

**Comment by coderaiser** [comment]
I see `ENOENT: no such file or directory, lstat '/home/nowuser/src/index.html'`

**Comment by coderaiser** [comment]
Fixed `deploy to heroku button`, please try again.
Is it helped?

**Comment by PowerOlive** [comment]
yes it is
