### ISSUE TITLE
Filestack - WebDav see folders as files

### ISSUE THREAD

**Issue by Nuke142** [coderaiser/cloudcmd#242]
I can not enter to folders , when i click it's starting upload folder as 0kb file
<a href="https://ibb.co/DGwS6Kd"><img src="https://i.ibb.co/DGwS6Kd/scr1.png" alt="scr1" border="0"></a> <a href="https://ibb.co/W05Wx3h"><img src="https://i.ibb.co/W05Wx3h/scr2.png" alt="scr2" border="0"></a>

**Comment by coderaiser** [comment]
Looks like it is a bug of `filestack`.

**Comment by Nuke142** [comment]
closed? any chance it can be fixed? may be new version of filestack?
