### ISSUE TITLE
First copy after startup fails

### ISSUE THREAD

**Issue by csazku** [coderaiser/cloudcmd#251]
* **Version**: v12.6.2
* **Node Version**: v10.16.0
* **OS** (`uname -a` on Linux): Ubuntu 18
* **Browser name/version**: 75.0.3770.142

After starting up cloudcmd the the first time I try to copy a file/folder the "in progress" icon shows up  but the file/folder doesn't get copied over, all copy operations after the first one seem to work fine. 
Tested it with the default settings.

**Comment by coderaiser** [comment]
Thank you 🙂, it looks like a bug.

**Comment by coderaiser** [comment]
Landed in [12.6.3](https://github.com/coderaiser/cloudcmd/releases/tag/v12.6.3) 🎉.
