### ISSUE TITLE
Disable F1 help button?

### ISSUE THREAD

**Issue by caracal7** [coderaiser/cloudcmd#252]
Is it possible?

**Comment by coderaiser** [comment]
No, but it's a good idea for a pull request, it can be made similar to https://github.com/coderaiser/cloudcmd/commit/9963577a6536674eb7bf2a2a570c1f2b9dc5990c.
Why do you need it?

**Comment by caracal7** [comment]
In my case the browser doesn't have access outside domain and without pictures the help looks ugly 🤗 Any copyrights is not a problem but I need to avoid outside link.

**Comment by coderaiser** [comment]
I'll close this for now, feel free to reopen when you need.
