### ISSUE TITLE
Progress bar not showing on first operation after startup

### ISSUE THREAD

**Issue by csazku** [coderaiser/cloudcmd#253]
* **Version** : v13.4.0
* **Node Version** : v10.16.3
* **OS** : Ubuntu 18
* **Browser name/version**: Chrome 76.0.3809.132

After starting up cloudcmd on the first copy/extract/pack operation the progress bar does not how up, only the icon next to the path on top.
When deleting files/folders it shows up properly even if it's the first thing I do after startup.
Could not test move because I don't have a setup with multiple hard drives.

**Comment by coderaiser** [comment]
That's OK, it's made by design, progressive enhancement. Maybe in the future something will be changed (that's a good idea for a pull request).

**Comment by csazku** [comment]
Sorry to return to this but in some cases this might be a bigger problem than just the progress bar not showing up.
For example I use cloudcmd behind a reverse proxy and if the first thing I do is pack a larger folder (happens a lot in my case) I usually get a request timeout/bad gateway error.
Tried using higher timeout values on the proxy but that is not a reliable solution since the time it takes for the response to arrive depends on the folder size/server load/etc.

**Comment by coderaiser** [comment]
@csazku I agree with you, this should be handled in other more reliable way, this is how it work right now, on connect `REST API`:
https://github.com/coderaiser/cloudcmd/blob/089bdc64a0395e435be2f2fb34a3c69652784a1d/client/modules/operation/index.js#L36-L41

changed to `websocket`: https://github.com/coderaiser/cloudcmd/blob/089bdc64a0395e435be2f2fb34a3c69652784a1d/client/modules/operation/index.js#L90-L183.

I'll think how to improve this logic, but one thing is for sure, is connection should be done much earlier, somewhere here:
https://github.com/coderaiser/cloudcmd/blob/089bdc64a0395e435be2f2fb34a3c69652784a1d/client/client.js#L138-L168

**Comment by coderaiser** [comment]
Landed ability to always show progress bar, even on first operation in Cloud Commander [v14.0.0](https://github.com/coderaiser/cloudcmd/releases/tag/v14.0.0) 🎉
