### ISSUE TITLE
Unable to change directory with dirStorage: true

### ISSUE THREAD

**Issue by csazku** [coderaiser/cloudcmd#255]
* **Version** : v14.0.1 
* **Node Version** : v12.10.0
* **OS** : Ubuntu 18 
* **Browser name/version**: Chrome 77.0.3865.90
* **Changed Config**: dirStorage

Setting `dirStorage` to `true` makes changing directory just display the progress icon and not do anything else. Leaving it on `false` makes everything work as intended.
In production I have it on `false`, discovered it by chance when testing the 14.0.1 build.

**Comment by coderaiser** [comment]
Landed in [v14.0.2](https://github.com/coderaiser/cloudcmd/releases/tag/v14.0.2). Is it works for you?

**Comment by csazku** [comment]
Yes, it's working.
Thanks.
