### ISSUE TITLE
feature request: support .webm files? 

### ISSUE THREAD

**Issue by knguyen0105** [coderaiser/cloudcmd#256]
Is it difficult to support view .webm files? I have a some video files I need to manage on my servers but currently it only supports .mp4. Thanks.

**Comment by coderaiser** [comment]
Could you please attach here `.webm` file? As I understood it developed by Google, and should be supported by Chrome, so I think it is possible to add support of such files :).

**Comment by knguyen0105** [comment]
Example: https://i.4cdn.org/gif/1569889096765.webm  

Can't attach since github doesn't support attaching `.webm`. Currently, cloudcmd treats `.webm` like binary file and doesn't play.

**Comment by coderaiser** [comment]
Landed in [v14.1.0](https://github.com/coderaiser/cloudcmd/releases/tag/v14.1.0) 🎉.
