### ISSUE TITLE
file editing

### ISSUE THREAD

**Issue by Michal2323** [coderaiser/cloudcmd#257]
After upgrade to new version editing file doesnt work.

* **Version** (`14.1.0.`): 
* **Node Version** `12.10`: 
* **OS** (`Debian 10` on Linux): 
* **Browser:** Chrome/77.0.3865.90
* **Used Command Line Parameters**: 
* **Changed Config**:

**Comment by AndreGeng** [comment]
editing file functionality has stop working at my side since v12.2.0
**Node Version**: `v10.16.0`
**OS**: `mac` 10.14.6
**Browser**: `77.0.3865.90`

**Comment by hanspalsson** [comment]
Edward seems broken, Dword and Deepword works fine. V14.1.0. Debian 8/Chrome.

**Comment by coderaiser** [comment]
Thank you, fixed in [edward v11.2.3](https://github.com/cloudcmd/edward/releases/tag/v11.2.3).
Please reinstall `Cloud Commander`.

Is it works for you?

**Comment by Michal2323** [comment]
its works. thx
