### ISSUE TITLE
file editing

### ISSUE THREAD

**Issue by JuanRamino** [coderaiser/cloudcmd#262]
Hi,

After updating to 14.1.2 from an old version. I can't edit a json file in this situation:
- First time I edit a file, it works.
- Second time (and so on) it does not work, no console error.
- If I delete local storage data, editing that file works.

Also when I can't edit a file if I view it I see [Object, Object]

It happen with both editors, edward and dword

Thank you

* **version 14.1.2** 
* **node 10.x** 
* **Alpine Linux** 
* **Chrome 77 and Firefox 69**:

**Comment by coderaiser** [comment]
I can't reproduce this. Could you please try to do the same on [demo](https://cloudcmd.herokuapp.com) `/tmp` directory.

**Comment by JuanRamino** [comment]
I do it and it does not work.
I edit changes.json at https://cloudcmd.herokuapp.com/fs/tmp/ischanged/29929/ 
After, I try to edit it again but editor does not open.

Thanks

**Comment by coderaiser** [comment]
Could you please tell me how do you open an editor?

**Comment by JuanRamino** [comment]
Sure, right click on the file name in the list  and then another one on _edit_
I've tried with 2 different laptops with the same result.
The only way to use the editor again is to clear the browser local storage.

**Comment by elcascador62** [comment]
I have same problem with version 14.1.0 on ARM no probleme on x86 virtual machine

**Comment by elcascador62** [comment]
for my case I have just rebuild my docker container with last version of cloud commander and now it's editing works

**Comment by coderaiser** [comment]
Closed due to inability to reproduce.
