### ISSUE TITLE
Feature request: Healthcheck endpoint

### ISSUE THREAD

**Issue by lukasmrtvy** [coderaiser/cloudcmd#265]
Would be nice to have healthcheck endpoint that returns OK/KO if application is running or not. ( Even 200 status code would be enough )
Thanks

**Comment by coderaiser** [comment]
What a great idea for a pull requests :)

**Comment by coderaiser** [comment]
Right now, you can use `/api/v1` url as a health check, is it OK for you :)?

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
