### ISSUE TITLE
Cannot start Cloudcmd on pi

### ISSUE THREAD

**Issue by gareth-halbert** [coderaiser/cloudcmd#266]
I have been trying to get cloud commander running via dataplicty wormhole.I have been following the instructions at: https://docs.dataplicity.com/docs/share-files-with-wormhole 
I have been successful in all steps down to 'Run cloud commander' using _**sudo cloudcmd --port 80 --auth**_ when I run this command I get the following error:

pi@poct-gateway-031900005a:/ $ sudo cloudcmd --port 80 --auth
sudo: unable to resolve host poct-gateway-031900005a
/usr/lib/node_modules/cloudcmd/node_modules/pullout/lib/pullout.js:9
for await (const chunk of stream)
^^^^^
SyntaxError: Unexpected reserved word
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:617:28)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/usr/lib/node_modules/cloudcmd/server/config.js:19:17)
pi@poct-gateway-031900005a:/ $ 

Here are my system details as requested:
* **Version** (`cloudcmd -v`):  **_Gives above error when attempting to run_** 
* **Node Version** `node -v`:  **_v8.16.2_**
* **OS** (`uname -a` on Linux):  **_Raspbian GNU/Linux 9 (stretch)_**
* **Browser name/version**:  **_N/A_**
* **Used Command Line Parameters**: 
* **Changed Config**:

**Comment by coderaiser** [comment]
Look, you should update `node` to `v10` or `v12` according to realease notes of [Cloud Commander v14](https://github.com/coderaiser/cloudcmd/releases/tag/v14.0.0). Is it works for you?

**Comment by gareth-halbert** [comment]
Hello coderaiser, thank you so much for your help. I have reinstalled node V10 and I can now access Cloude Commmander.
