### ISSUE TITLE
Control+Left Click open files in new tab (firefox and chrome)

### ISSUE THREAD

**Issue by jvalrog** [coderaiser/cloudcmd#269]
* **Version** (`cloudcmd -v`): docker (latest)
* **Node Version** `node -v`: 14.2.1
* **OS** (`uname -a` on Linux): Ubuntu 18.04
* **Browser name/version**: Firefox 72 and Chrome 79
* **Used Command Line Parameters**: None
* **Changed Config**: None

When I try to select multiple files with Control + Left mouse button, the files are being opened in new tabs.

This happens in both Firefox and Chrome.

I'm using the latest docker image.

**Comment by coderaiser** [comment]
Hi, @jvalrog :), could you please tell me what behavior do you expect? Could you please clarify what version of `node.js` are you using? There is no version `14` :), it should [came up in April](https://nodejs.org/en/about/releases/).

**Comment by jvalrog** [comment]
Hi, you're right, **14.2.1** is the cloudcmd version.

Nodejs is version **13.5.0**.

The problem I found is selecting multiple files with Control + LMB. I want to select those files, not to open them in new tabs.

How do you select multiple files that are not contiguous with the mouse?

**Comment by coderaiser** [comment]
You can use `Shift + Up`/`Shift + Down` or `Space` button, but your point has sense. This is a very good idea for a Pull Request :).

**Comment by coderaiser** [comment]
Landed in [v14.3.0](https://github.com/coderaiser/cloudcmd/releases/tag/v14.3.0) :tada: Is it works for you?
