### ISSUE TITLE
Contact form can't be closed

### ISSUE THREAD

**Issue by tedbeer** [coderaiser/cloudcmd#27]
Cloudcmd ver 2.5.0
Once the Contact form is opened it can't be closed without sending. It can be minimized but there is no way to close it.

**Comment by coderaiser** [comment]
Fixed in https://github.com/coderaiser/cloudcmd/commit/3b546f92ac5bcd6ccd377bca0583e025c8d18776. Now you will have ability to close the window with help of `Esc` button.

**Comment by coderaiser** [comment]
Landed in [v2.5.1](https://github.com/coderaiser/cloudcmd/releases/tag/v2.5.1).
