### ISSUE TITLE
Download resume support broken

### ISSUE THREAD

**Issue by alexandergre** [coderaiser/cloudcmd#270]
* **Version** (`cloudcmd -v`): v14.2.1
* **Node Version** `node -v`: v13.5.0
* **OS** (`uname -a` on Linux): Debian 4.19.12-1~bpo9+1 (2018-12-30) x86_64 GNU/Linux
* **Browser name/version**: Chrome latest
* **Used Command Line Parameters**: none
* **Changed Config**: none

Ever since installing the latest cloudcmd resuming when downloading files is no longer working, which also breaks download accelerators support. I'm unsure which version is broken but it used to work fine for me around 6 months ago.

**Comment by coderaiser** [comment]
Could you please tell me what do you use for downloading with resume?

**Comment by alexandergre** [comment]
I use Chrono download manager for Chrome and uGet. 
I have tried downloading a smaller file - 112MB instead of 11GB, and the download manager correctly reported download size:
![image](https://user-images.githubusercontent.com/31637335/72266301-2dc0c080-3672-11ea-97d2-ddbaf82c1a06.png)

**Comment by alexandergre** [comment]
I have checked the headers and it appears that on the larger download cloudcmd uses chunked transfer encoding:
![image](https://user-images.githubusercontent.com/31637335/72267037-788f0800-3673-11ea-9e4b-a36ed0df350f.png)

**Comment by coderaiser** [comment]
Could you please check if [v14.4.0](https://github.com/coderaiser/cloudcmd/releases/tag/v14.4.0) works for you?

**Comment by alexandergre** [comment]
Hi, tested the latest version (14.5.1) and it looks like the issue is fixed, thanks!
