### ISSUE TITLE
Editor causes immediate crash

### ISSUE THREAD

**Issue by brandond** [coderaiser/cloudcmd#278]
* **Version** (`cloudcmd -v`): v14.3.4
* **Node Version** `node -v`: n/a
* **OS** (`uname -a` on Linux): Tested on Ubuntu and CentOS
* **Browser name/version**: Firefox, Chrome
* **Used Command Line Parameters**:   docker run --rm -it -v ~:/root -v /:/mnt/fs -w=/root -p 8000:8000 coderaiser/cloudcmd:latest-alpine (also tried with latest, same result)
* **Changed Config**: n/a

Any attempt to edit a file results in a crash and container exit:
```
ENOENT: no such file or directory, open '/root/.edward.json' Promise {
  <rejected> [Error: ENOENT: no such file or directory, open '/root/.edward.json'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/root/.edward.json'
  }
}
```

The file that it attempts to open varies depending on what editor you pick, but since none of these files exist on my system, it always crashes.

**Comment by brandond** [comment]
Just tried coderaiser/cloudcmd:14.3.3-alpine and it works fine, so something in the most recent round of package updates seems to have broken it.

**Comment by Frepke** [comment]
> 
> 
> Just tried coderaiser/cloudcmd:14.3.3-alpine and it works fine, so something in the most recent round of package updates seems to have broken it.

+1

**Comment by coderaiser** [comment]
Just updated docker image, please try to pull again. Is it helped?

**Comment by Frepke** [comment]
> 
> 
> Just updated docker image, please try to pull again. Is it helped?
> This is related to #277.

Just pulled the latest version, but unfortunately de editor (deepword in my case) doesn't open anything.

next errors appear in the logfile:

ENOENT: no such file or directory, open '/root/.deepword.json' Promise {
  <rejected> [Error: ENOENT: no such file or directory, open '/root/.deepword.json'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/root/.deepword.json'
  }
}

**Comment by coderaiser** [comment]
Fixed with https://github.com/cloudcmd/deepword/commit/9a4bd71a78a241dbcc7b943c0e89eec2ee34bd96, and updated docker images. Is it works for you now?

**Comment by Frepke** [comment]
> 
> 
> Fixed with [cloudcmd/deepword@9a4bd71](https://github.com/cloudcmd/deepword/commit/9a4bd71a78a241dbcc7b943c0e89eec2ee34bd96), and updated docker images. Is it works for you now?

Yes, editor is working again.

For me this problem is solved, thanks.

**Comment by coderaiser** [comment]
@brandond is it works for you :)?

**Comment by brandond** [comment]
lgtm
