### ISSUE TITLE
Space key does not work as expected

### ISSUE THREAD

**Issue by tedbeer** [coderaiser/cloudcmd#28]
Cloudcmd v.2.5.0
I looked at the source code and see that Space key should work as Pause/Resume button.
In Chrome it does not work in this way.
How to reproduce:
 - open cloud commander
 - find video file and click it
 - click F3 screen button using mouse(!)
A media player is started. But F3 still has a focus and the Space key reloads the file viewer.
If media file viewer is triggered by hardware F3 key it works as expected.

**Comment by coderaiser** [comment]
Thank you, fixed in https://github.com/coderaiser/cloudcmd/commit/c60c87fef628c1748b0e6ca920181cf1fffd5db2.

**Comment by coderaiser** [comment]
Landed in [v2.5.1](https://github.com/coderaiser/cloudcmd/releases/tag/v2.5.1).
