### ISSUE TITLE
Docker: docker:build doesn't compile the client code 

### ISSUE THREAD

**Issue by kimwnasptd** [coderaiser/cloudcmd#282]
First of all thank you for this software, its list of supported features and UX are awesome!

When I create the docker image from a clean clone and try to run it I get the following error message:
```sh
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/usr/src/app/dist/columns'
    at Object.readdirSync (fs.js:887:3)
    at Object.<anonymous> (/usr/src/app/server/columns.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/src/app/server/validate.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:1151:30) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/usr/src/app/dist/columns'
}
```
It complains that the directory `dist/columns` doesn't exist. After taking a look at the `docker/Dockerfile` I noticed that it doesn't have a layer for building the client code, and produce the `dist` directory. I guess that for building the docker images you have some CI job that first builds the JavaScript artifacts in `dist` dir and the run the `npm run docker:build`?

I would be happy to submit a PR for making a multistage build Dockerfile that could also compile the client code.

This change could also simplify existing CI solutions since the docker build process won't have any dependencies to run.

The commands I used for running the image are the following:
```sh
git clone https://github.com/coderaiser/cloudcmd
cd cloudcmd
npm i
npm run docker:build
docker run coderaiser/cloudcmd:14.3.6-x64
```

* **Version** (`cloudcmd -v`): 
* **Node Version** `node -v`: 12.0.0
* **OS** (`uname -a` on Linux): Linux bebop 5.3.0-42-generic #34~18.04.1-Ubuntu
* **Browser name/version**: 
* **Used Command Line Parameters**: 
* **Changed Config**:

**Comment by coderaiser** [comment]
The thing is you need to run:
```sh
npm run build
```

To build frontend :). Is it helped?

If you want to help, would be great if you help with this https://github.com/coderaiser/cloudcmd/pull/268
