### ISSUE TITLE
crash six minutes after launch when not connected to internet (but DNS resolution available)

### ISSUE THREAD

**Issue by Daniel-Valentine** [coderaiser/cloudcmd#286]
# Setup

I've deployed Cloud Commander on a Docker containe based on [coderaiser/cloudcmd:latest](https://hub.docker.com/layers/coderaiser/cloudcmd/latest/images/sha256-1f7420899226221f8d8764a1eaf5a15e10434823e56f1403aedb0f6d96931cba) (latest as of the timestamp of this issue). I have not extended the image. I've restricted the container to an internal network, which means any connection to a host outside this network will fail. The container is still able to resolve domain names in spite of it being on an internal network.

* **Version** (`cloudcmd -v`): `v14.3.9` (per Docker container)
* **Node Version** `node -v`: `v12.16.2`(per Docker container)
* **OS** (`uname -a` on Linux): `Linux [hostname redacted] 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux` (per Docker container)
* **Browser name/version**: n/a
* **Used Command Line Parameters**: none
* **Changed Config**:
```json
{
	"name" : "[redacted]",
	"auth" : true,
	"username" : "[redacted]",
	"password" : "[redacted]",
	"algo" : "sha512WithRSAEncryption",
	"root" : "[redacted]",
	"showConfig" : true,
	"oneFilePanel" : true,
	"log" : true,
	"contact" : false,
	"importListen" : true,
	"online" : false,
	"configAuth" : false
}
```

# Description

I've set up Cloud Commander in a Docker container on an internal network (i.e. no internet access). Roughly 6 minutes after launch, the Cloud Commander exits with a non-zero code and an error message (see below) after failing to connect to a remote address. These crashes occur independently of whether or not I'm connected to Cloud Command via a browser.

It appears that Cloud Commander is making a connection to `registry.npmjs.org` which times out. The container was able to resolve the domain to `104.16.21.35`. I don't know if this would have any relevance to the crash here since I don't know if the crash would be any different if the container could not do DNS queries. I will see if disabling DNS resolution makes a difference.

```node
connect ETIMEDOUT 104.16.21.35:443 Promise {
  <rejected> GotError [RequestError]: connect ETIMEDOUT 104.16.21.35:443
      at ClientRequest.<anonymous> (/usr/src/app/node_modules/package-json/node_modules/got/source/request-as-event-emitter.js:178:14)
      at Object.onceWrapper (events.js:417:26)
      at ClientRequest.emit (events.js:322:22)
      at ClientRequest.origin.emit (/usr/src/app/node_modules/package-json/node_modules/@szmarczak/http-timer/source/index.js:37:11)
      at TLSSocket.socketErrorListener (_http_client.js:426:9)
      at TLSSocket.emit (events.js:310:20)
      at emitErrorNT (internal/streams/destroy.js:92:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    name: 'RequestError',
    code: 'ETIMEDOUT',
    host: undefined,
    hostname: 'registry.npmjs.org',
    method: 'GET',
    path: '/cloudcmd',
    socketPath: undefined,
    protocol: 'https:',
    url: 'https://registry.npmjs.org/cloudcmd',
    gotOptions: {
      path: '/cloudcmd',
      protocol: 'https:',
      hostname: 'registry.npmjs.org',
      hash: '',
      search: '',
      pathname: '/cloudcmd',
      href: 'https://registry.npmjs.org/cloudcmd',
      retry: [Object],
      headers: [Object],
      hooks: [Object],
      decompress: true,
      throwHttpErrors: true,
      followRedirect: true,
      stream: false,
      form: false,
      json: true,
      cache: false,
      useElectronNet: false,
      agent: [Agent],
      method: 'GET',
      forceRefresh: true
    }
  }
}
```

**Comment by coderaiser** [comment]
The thing is `Cloud Commander` is checking for update just after start, but of course it should not crash if can't check update. I will think about it.

**Comment by peasoupio** [comment]
I've got a similar error but connected to the Internet.

## Setup
I'm using the same hardware/middle (Docker) configuration as @Daniel-Valentine.
I've got no specific "app" configuration.

## Description
It was working properly 4 days ago.
It stopped working 23 hours ago (when running a new container).

I suspect I was having the issue since I started using `Cloud Commander`, but it used to be swallowed/non-blocking. Symptom-wise, it could also explain @Daniel-Valentine error.

Interesting note: I did a `curl registry.npmjs.org` (same network configuration) in another container and I received a proper response.

Thanks for your help and your work :)

Here's the log: 
```
url: http://localhost:8000/
unable to get local issuer certificate Promise {
  <rejected> GotError [RequestError]: unable to get local issuer certificate
      at ClientRequest.<anonymous> (/usr/src/app/node_modules/package-json/node_modules/got/source/request-as-event-emitter.js:178:14)
      at Object.onceWrapper (events.js:417:26)
      at ClientRequest.emit (events.js:322:22)
      at ClientRequest.origin.emit (/usr/src/app/node_modules/package-json/node_modules/@szmarczak/http-timer/source/index.js:37:11)
      at TLSSocket.socketErrorListener (_http_client.js:426:9)
      at TLSSocket.emit (events.js:310:20)
      at emitErrorNT (internal/streams/destroy.js:92:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    name: 'RequestError',
    code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
    host: undefined,
    hostname: 'registry.npmjs.org',
    method: 'GET',
    path: '/cloudcmd',
    socketPath: undefined,
    protocol: 'https:',
    url: 'https://registry.npmjs.org/cloudcmd',
    gotOptions: {
      path: '/cloudcmd',
      protocol: 'https:',
      hostname: 'registry.npmjs.org',
      hash: '',
      search: '',
      pathname: '/cloudcmd',
      href: 'https://registry.npmjs.org/cloudcmd',
      retry: [Object],
      headers: [Object],
      hooks: [Object],
      decompress: true,
      throwHttpErrors: true,
      followRedirect: true,
      stream: false,
      form: false,
      json: true,
      cache: false,
      useElectronNet: false,
      agent: [Agent],
      method: 'GET'
    }
  }
}
```

**Comment by coderaiser** [comment]
Fixed with 545b5a513535dd11af505458b9744610b3a29692, landed in [v14.3.10](https://github.com/coderaiser/cloudcmd/releases/tag/v14.3.10) :tada: 
Is it works for you :)?

**Comment by peasoupio** [comment]
It works for me! Thanks a lot.

**Comment by Daniel-Valentine** [comment]
@coderaiser: Works on my end as well. Thanks for the quick fix.
