### ISSUE TITLE
Deployment error Status: no matching manifest for linux/arm64/v8 in the manifest list entries, Code: 1

### ISSUE THREAD

**Issue by hemertje** [coderaiser/cloudcmd#288]
* **Version** (`cloudcmd -v`): 
* **Node Version** `node -v`: 
* **OS** (`uname -a` on Linux): 
* **Browser name/version**: 
* **Used Command Line Parameters**: 
* **Changed Config**: 

Running Portainer 1.23.2 on OpenMediaVault 5 installed on a Rockpro64 
https://github.com/ayufan-rock64/linux-build/releases/tag/0.10.9

Under Portainer - Stacks add "cloudcmd". and

version: '2'
services:
  web:
    ports:
      - 8000:8000
    volumes:
      - ~:/root
      - /:/mnt/fs
    image: coderaiser/cloudcmd

After running "deploy the stack" getting this error:

Deployment error Status: no matching manifest for linux/arm64/v8 in the manifest list entries, Code: 1

root@NAS-rockpro64:~# docker info  -f '{{.OSType}}/{{.Architecture}}'
linux/aarch64

**Comment by hemertje** [comment]
root@NAS-rockpro64:~# cloudcmd -v
cloudcmd: command not found
root@NAS-rockpro64:~# node -v

Command 'node' not found, but can be installed with:

apt install nodejs

root@NAS-rockpro64:~# uname -a
Linux NAS-rockpro64 5.6.0-1132-ayufan-g81043e6e109a #ayufan SMP Tue Apr 7 10:07:35 UTC 2020 aarch64 GNU/Linux
root@NAS-rockpro64:~#

**Comment by coderaiser** [comment]
Looks like it's related to https://github.com/coderaiser/cloudcmd/pull/268, @tea-mo903 could you please help with this :)?

**Comment by tea-mo903** [comment]
Hi @hemertje ,

there is currently still an issue with the `arm` based images. Could you please try to `ssh`into your system and do a plain `docker pull coderaiser/cloudcmd` without using the Web-UI of `portainer`? And provide us with the corresponding logs please.

Cheers!

**Comment by hemertje** [comment]
Hi @coderaiser & @tea-mo903 ,

I'm not a coder or expert with Rockpro64 or OpenmediaVault.

Will help you guys where I can!

`root@NAS-rockpro64:~# docker pull coderaiser/cloudcmd
Using default tag: latest
latest: Pulling from coderaiser/cloudcmd
no matching manifest for linux/arm64/v8 in the manifest list entries
root@NAS-rockpro64:~# `

**Comment by tea-mo903** [comment]
@hemertje, okay it seems that is not able to resolve your `os-architecture` with regards to the required `docker` image. Could you please try using this image instead:
`docker pull team0/rpi-cloudcmd`

If you are running a `docker-compose` stack you can also refer to this example:
https://github.com/tea-mo903/rpi-nas/blob/master/docker-compose.yml#L49

Cheers!

**Comment by hemertje** [comment]
`root@NAS-rockpro64:~# docker pull team0/rpi-cloudcmd
Using default tag: latest
latest: Pulling from team0/rpi-cloudcmd
588374d57fdb: Pull complete 
639a9452afb2: Pull complete 
d202122715db: Extracting  33.03MB/43.37MB
da48f7ce5483: Download complete 
fe39b5f50779: Download complete 
061299929871: Download complete 
a968ae35a20b: Download complete 
c7f3cd03f130: Downloading  60.54MB/90.21MB
cd5e06c64d10: Downloading   40.2MB/46.54MB
c8bc06d7c17b: Download complete 
`

`root@NAS-rockpro64:~# docker pull team0/rpi-cloudcmd
Using default tag: latest
latest: Pulling from team0/rpi-cloudcmd
588374d57fdb: Pull complete 
639a9452afb2: Pull complete 
d202122715db: Pull complete 
da48f7ce5483: Pull complete 
fe39b5f50779: Pull complete 
061299929871: Pull complete 
a968ae35a20b: Pull complete 
c7f3cd03f130: Pull complete 
cd5e06c64d10: Pull complete 
c8bc06d7c17b: Pull complete 
958e08a1f201: Pull complete 
Digest: sha256:90bdf620184a59d6fc9cd12fc8c97d8b6726cae88a84679c49f98b6de3427db9
Status: Downloaded newer image for team0/rpi-cloudcmd:latest
docker.io/team0/rpi-cloudcmd:latest
root@NAS-rockpro64:~# `

**Comment by hemertje** [comment]
> @hemertje, okay it seems that is not able to resolve your `os-architecture` with regards to the required `docker` image. Could you please try using this image instead:
> `docker pull team0/rpi-cloudcmd`
> 
> If you are running a `docker-compose` stack you can also refer to this example:
> https://github.com/tea-mo903/rpi-nas/blob/master/docker-compose.yml#L49
> 
> Cheers!

you mean this 151 lines code in the web editor and then run the "deploy the stack"?

**Comment by tea-mo903** [comment]
@hemertje okay that looks better! You can try starting the container now, this can be also done by `portainer` if you prefer that over the `shell`.

Btw I am also running `cloudcmd` on an OpenMediaVault setup. You can also refer to my `docker-compose` if you want to tweak you `NAS` a little more:
https://github.com/tea-mo903/rpi-nas

**Comment by tea-mo903** [comment]
> > @hemertje, okay it seems that is not able to resolve your `os-architecture` with regards to the required `docker` image. Could you please try using this image instead:
> > `docker pull team0/rpi-cloudcmd`
> > If you are running a `docker-compose` stack you can also refer to this example:
> > https://github.com/tea-mo903/rpi-nas/blob/master/docker-compose.yml#L49
> > Cheers!
> 
> you mean this 151 lines code in the web editor and then run the "deploy the stack"?

Exactly, you can try using this `image` in `portainer`.

**Comment by hemertje** [comment]
<img width="662" alt="Schermafbeelding 2020-04-27 om 13 01 05" src="https://user-images.githubusercontent.com/45018786/80365506-ff18cf80-8887-11ea-85e4-d2e0ae9389f6.png">


getting an error: 
Deployment error
Volume "grafana-storage" needs to be recreated - driver has changed

**Comment by hemertje** [comment]
> @hemertje okay that looks better! You can try starting the container now, this can be also done by `portainer` if you prefer that over the `shell`.
> 
> Btw I am also running `cloudcmd` on an OpenMediaVault setup. You can also refer to my `docker-compose` if your want to tweak you `NAS` a little more:
> https://github.com/tea-mo903/rpi-nas

will have a look later...
just started with rockpro64 and OMV ;)

**Comment by hemertje** [comment]
Grafana is running under containers
<img width="1302" alt="Schermafbeelding 2020-04-27 om 13 10 57" src="https://user-images.githubusercontent.com/45018786/80367350-39d03700-888b-11ea-9620-63407cc18a43.png">

**Comment by hemertje** [comment]
under stacks I see cloudcmd running
<img width="1305" alt="Schermafbeelding 2020-04-27 om 14 42 29" src="https://user-images.githubusercontent.com/45018786/80373498-743ed180-8895-11ea-8b94-5c452a04fa3d.png">

**Comment by tea-mo903** [comment]
> <img alt="Schermafbeelding 2020-04-27 om 13 01 05" width="662" src="https://user-images.githubusercontent.com/45018786/80365506-ff18cf80-8887-11ea-85e4-d2e0ae9389f6.png">
> 
> getting an error:
> Deployment error
> Volume "grafana-storage" needs to be recreated - driver has changed

In order to not overcomplify everything, I would recommed you to only run `cloudcmd` first. So not directly running the entire `docker-compose` stack, which I linked above.

1. Open Portainer and start the container with the image `team0/cloudcmd`
should look like this:
<img width="2734" alt="image" src="https://user-images.githubusercontent.com/11437666/80374568-2034ec80-8897-11ea-82e1-783007723568.png">

*BUT*  make sure than you before stopped all other services, which you have started with the `compose`before, because it could block some running ports.

2. If this runs smoothly, than you can try adding some other services in order to extend your NAS setup.

**Comment by hemertje** [comment]
seems it runs under port 3000, but how to login?

<img width="375" alt="Schermafbeelding 2020-04-27 om 18 26 13" src="https://user-images.githubusercontent.com/45018786/80396259-add30500-88b4-11ea-8ded-4058b1c0fc34.png">

**Comment by tea-mo903** [comment]
> seems it runs under port 3000, but how to login?
> 
> <img alt="Schermafbeelding 2020-04-27 om 18 26 13" width="375" src="https://user-images.githubusercontent.com/45018786/80396259-add30500-88b4-11ea-8ded-4058b1c0fc34.png">

I think you are mixing things up a little! This is Grafana, a monitoring tool. It is **not related** to `cloudcmd` at all. Could you please `stop` all containers in your stack and `remove` them. So that you can start fresh and only run `cloudcmd`. All other containers are not important for now.

## Cleanup

1. Open Portainer 
2. Click "Containers" (left side)
3. Select all container **except** Portainer itself!
4. Click "Stop"
5. Click "Remove" (so that you dont have any legacy to deal with)

Should look sth. like this:
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/11437666/80399059-e1b02980-88b8-11ea-827b-0807ae37b2cc.png">

## Setup cloudcmd

1. Click "Containers" (if not still there)
2. Click "Add Container"
3. Fill out the form as the following screenshot
<img width="2991" alt="image" src="https://user-images.githubusercontent.com/11437666/80399484-8c284c80-88b9-11ea-98d3-af12856452f9.png">

**KEEP IN MIND** this will run `cloudcmd` under port `8008` on your `rockpro64`

Hope this clears the page for you :)

**Comment by tea-mo903** [comment]
@hemertje  could you please give a feedback, so that we know whether we can close this issue?

**Comment by hemertje** [comment]
> 1. container with the image `team0/cloudcmd`

there wasn't a container with the image team0/cloudcmd
will try your new howto

**Comment by hemertje** [comment]
> @hemertje could you please give a feedback, so that we know whether we can close this issue?

ofcourse, just found time to sit back and try out, got it running , thx!

<img width="1428" alt="Schermafbeelding 2020-04-28 om 19 55 57" src="https://user-images.githubusercontent.com/45018786/80520928-759df600-898a-11ea-8db1-91ab6025dc67.png">

**Comment by hemertje** [comment]
how to get a user link in the OMV GUI?

**Comment by hemertje** [comment]
> Btw I am also running `cloudcmd` on an OpenMediaVault setup. You can also refer to my `docker-compose` if your want to tweak you `NAS` a little more:
> https://github.com/tea-mo903/rpi-nas

think I understand what you are doing with the above "docker-compose"
Is there a website with some background information or howto explained what is exactly does?

**Comment by hemertje** [comment]
hhmmm cloudcmd running, but can't find my 'data' drive

<img width="702" alt="Schermafbeelding 2020-04-28 om 20 07 58" src="https://user-images.githubusercontent.com/45018786/80521902-0fb26e00-898c-11ea-8f89-b551f73ef662.png">
<img width="1155" alt="Schermafbeelding 2020-04-28 om 20 07 10" src="https://user-images.githubusercontent.com/45018786/80521908-1214c800-898c-11ea-9c11-8793434b7c93.png">

**Comment by tea-mo903** [comment]
> hhmmm cloudcmd running, but can't find my 'data' drive
> 
> <img alt="Schermafbeelding 2020-04-28 om 20 07 58" width="702" src="https://user-images.githubusercontent.com/45018786/80521902-0fb26e00-898c-11ea-8f89-b551f73ef662.png">
> 
> <img alt="Schermafbeelding 2020-04-28 om 20 07 10" width="1155" src="https://user-images.githubusercontent.com/45018786/80521908-1214c800-898c-11ea-9c11-8793434b7c93.png">

Great that it worked out.

Regarding your screenshot, the drives you are looking for are mounted under `/mnt/fs/srv/`. So you have to click on `..` and then `mnt/fs/srv/`. 
Should as the follows:
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/11437666/80525511-a6355e00-8991-11ea-9d31-c4e44cf13214.png">

**Comment by tea-mo903** [comment]
@hemertje Can we now close this issue then?

**Comment by hemertje** [comment]
yes was looking first under 'mount' but strange it is empty 
<img width="702" alt="Schermafbeelding 2020-04-28 om 20 56 13" src="https://user-images.githubusercontent.com/45018786/80526278-cc0f3280-8992-11ea-96c7-0c860638acaf.png">

**Comment by hemertje** [comment]
can you give me a hint to install 'heimdall' ?
I am reading here https://hub.docker.com/r/linuxserver/heimdall/
and here: https://www.youtube.com/watch?v=jS4oiJcrrR4

but the way Docker works and everywhere is explained changed, now it's confusing me to easily add stuff...?

do I read to 'add stack' 
with: https://hub.docker.com/r/linuxserver/heimdall/

docker compose code?

version: "2.1"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

**Comment by tea-mo903** [comment]
1. Could you please close this issue now. All Questions you are having, are not related to `cloudcmd`. 

2. In order to install another container such as `heimdall` you do the same like you did, when starting the container of `cloudcmd`. Just that you need to 
- depend on the [following image](https://github.com/tea-mo903/rpi-nas/blob/master/docker-compose.yml#L5)
- change the values for the placeholder in [PUID](https://github.com/tea-mo903/rpi-nas/blob/master/docker-compose.yml#L8), [PGID](https://github.com/tea-mo903/rpi-nas/blob/master/docker-compose.yml#L9) and [volumes](https://github.com/tea-mo903/rpi-nas/blob/master/docker-compose.yml#L12)

Furthermore I guess, it will help you reading a little more about `docker`, so that you understand the details better :)

**Comment by hemertje** [comment]
Will look further... hard to find where to start ;)

Danke, thank you!

Grussen aus Holland, Greetings...

**Comment by tea-mo903** [comment]
@hemertje you are welcome

**Comment by tea-mo903** [comment]
@coderaiser can you close the issue then?

**Comment by hemertje** [comment]
closed by Hemertje

**Comment by coderaiser** [comment]
@tea-mo903 thanks a lot for help :)
