### ISSUE TITLE
Rename with same name delete file/folder

### ISSUE THREAD

**Issue by renaudjx** [coderaiser/cloudcmd#289]
* **Version** (`cloudcmd -v`): 14.5.1
* **Node Version** `node -v`: 14.1.0
* **OS** (`uname -a` on Linux): Linux 8a8f68df404d 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 GNU/Linux
* **Browser name/version**: Chrome Version 81.0.4044.138 (Official Build) (64-bit)
* **Used Command Line Parameters**: 
* **Changed Config**: 

Hello, I notice that when I rename a file or folder with the same name of anoter file/folder in the same directory one of these file/folder disapear without any warrant and I don't know where to retrieve it.
![2020-05-16_18-45-24](https://user-images.githubusercontent.com/51540139/82125388-f9871900-97a5-11ea-9f05-df706807ea36.gif)

**Comment by coderaiser** [comment]
Is it works in the same way when new file has the same name as existing file or a directory? What behavior do you expect to see?

**Comment by coderaiser** [comment]
As I see it works only for case when you rename filled directory with a name of an empty directory, is it a big deal :)?

**Comment by renaudjx** [comment]
I agree for folders it's totally normal but for files I think data loss could occur
![2020-05-17_22-42-16](https://user-images.githubusercontent.com/51540139/82159716-9a520300-9890-11ea-82ae-831f56c6a461.gif)
.

**Comment by coderaiser** [comment]
I see, this have sense. That's a good idea for a PR :)

**Comment by coderaiser** [comment]
Landed in [v14.6.0](https://github.com/coderaiser/cloudcmd/releases/tag/v14.6.0) 🎉Is it works for you :)?

**Comment by renaudjx** [comment]
That's great !! well done ! However in my mind I was thinking more of totally forbid renaming with existing name and not be able to overwrite existing files by pressing enter, for safety reasons (just like in finder in mac). But that's only details. Thanks ! :)
![2020-05-20_20-01-09](https://user-images.githubusercontent.com/51540139/82480971-e42b2b00-9ad4-11ea-9d99-c45350c37628.gif)
