### ISSUE TITLE
Images with upper case extension are not recognized as images

### ISSUE THREAD

**Issue by tedbeer** [coderaiser/cloudcmd#29]
Images with upper case extension are not recognized as images. Try to preview an image with .JPG extension. It's shown not as an image but as a binary file.

**Comment by coderaiser** [comment]
Thank you, fixed in https://github.com/coderaiser/cloudcmd/commit/86273c129e167cc6a2a13e248e956627c5f47791.

**Comment by coderaiser** [comment]
Landed in [v2.5.1](https://github.com/coderaiser/cloudcmd/releases/tag/v2.5.1).
