### ISSUE TITLE
Modifiacations after editing files aren't always saved.

### ISSUE THREAD

**Issue by Frepke** [coderaiser/cloudcmd#290]
* **Version** (`latest dockerversion V14.6.0`): 
* **OS** (`#1 SMP PVE 5.4.41-1 (Fri, 15 May 2020 15:06:08 +0200) x86_64 GNU/Linux`): 

First of all, thanks for your great container. It's great looking an very functional for me.
I use cloudcmd in docker for a while now. But when I edit a file (most of the time .txt or .yml) and save this file, the modifications aren't always saved. When I reopen the file, the modifications are gone (there are also no modifications when I open the file with nano). The problem occurs with all of the three editors available.

kr.,
Frepke

**Comment by coderaiser** [comment]
Could you please tell me if you have any errors in console of browser you use?

**Comment by Frepke** [comment]
> 
> 
> Could you please tell me if you have any errors in console of browser you use?

You mean an error when saving or something? No, I've no errors at all in my browsers (Firefox/Chrome/Edge on Windows and Firefox/Safari on MacOS (always updated to the latest versions).

**Comment by coderaiser** [comment]
Do you see message `save: ok("file name")` on top of an editor? When you press `Ctrl` + `S` buttons.

**Comment by Frepke** [comment]
> Do you see message `save: ok("file name")` on top of an editor? When you press `Ctrl` + `S` buttons.

The first time I see `patch: ok`, the second time I see `save: ok`
Normally I click the X in the ricgt upper corner, then a popup appears where I can click OK to save.

**Comment by coderaiser** [comment]
I can't reproduce this, could you please tell me is date of modification of file changing after message occurs?

**Comment by Frepke** [comment]
The problem is, it doesn't happen all the time.
I'll try to give you more information when the problem occurs.

**Comment by Frepke** [comment]
I think I found my problem.
When I've a session open in Safari (in this case) and my macbook is going to sleep (close the lid), then after using the macbook again with the same cloudcmd session in the opened safari tab nothing is saved after editing (timestamp doesn't change), even when I click the refresh button in cloudcmd nothings saved. I've to open a new tab with cloudcmd or refresh the tab with F5 (cmd + R).

**Comment by coderaiser** [comment]
@Frepke that’s interesting, I’ll think about it, looks like it relates to websockets.

**Comment by Frepke** [comment]
> @Frepke that’s interesting, I’ll think about it, looks like it relates to websockets.

Can you reproduce it this way also?

**Comment by coderaiser** [comment]
I still can't reproduce. Could you please try to use chrome or firefox for this purpose?

**Comment by Frepke** [comment]
> I still can't reproduce. Could you please try to use chrome or firefox for this purpose?

I checked it simultaneous on my macbook, one session in safari and one session in firefox.
The problem only appears in safari and NOT in firefox. The mentioned browsers in the first message aren't all problematic at the moment and maybe never were :(

**Comment by coderaiser** [comment]
Looks likes it’s a safari bug, can you reproduce this in chrome :)?

**Comment by Frepke** [comment]
> 
> 
> Looks likes it’s a safari bug, can you reproduce this in chrome :)?

Chrome doesn't have the problem either (checked on Macbook)

**Comment by coderaiser** [comment]
Closed because this is a bug in Safari.
