### ISSUE TITLE
JSON file error

### ISSUE THREAD

**Issue by YunlongJiao-B** [coderaiser/cloudcmd#294]
a json file will show： [object Object] after edit.(save in localStorage)
when i clear localStorage, it will be ok.

**Comment by coderaiser** [comment]
Thank you :), fixed with d181b84, landed in [v14.9.2](https://github.com/coderaiser/cloudcmd/releases/tag/v14.9.2) :tada: 
Is it works for you?

**Comment by YunlongJiao-B** [comment]
It works.Thank you!
