### ISSUE TITLE
feat: dark theme

### ISSUE THREAD

**Issue by maximousblk** [coderaiser/cloudcmd#296]
This won't really a be big thing for most people but would certainly be a nice-to-have.

**Comment by coderaiser** [comment]
Are you up for a PR with this :)?

**Comment by maximousblk** [comment]
Sorry, I've been busy lately and can't really work on this for now. But I'll consider it if i'm free sometime 😃

**Comment by Mayuresh0072** [comment]
I can work on this . Please Assign me @coderaiser @maximousblk

**Comment by coderaiser** [comment]
@maximousblk any progress on this?

**Comment by maximousblk** [comment]
sorry, I have since stopped using this project 😢 (ftp is fine)

**Comment by coderaiser** [comment]
Related to #332
