### ISSUE TITLE
Total Available Disk Space

### ISSUE THREAD

**Issue by Daxcor69** [coderaiser/cloudcmd#298]
I would love to see a way to show the user how much disk space they have left.   

i.e.
You have used 32 gigs of a 60 gig storage space.

This would be very helpful.

This is an awesome product.

Brad

**Comment by coderaiser** [comment]
The thing is you can have a lot different storages, and there is different ways to determine available free space on them. For example on `linux`, you can use `df -h` command on `console` or `terminal` to see disk usage on all connected storages. On `windows` you can use [du](https://www.windows-commandline.com/windows-disk-usage/) for the similar purpose.

So I don't quite understand in what another way you want to observe this information if there is already a way to accomplish this using terminal :).

**Comment by Daxcor69** [comment]
You are right, I could have elaborated.  I am using the app strictly as a file manager, not allowing any kind of terminal or console access.  The application is running as a side car to a main application that requires files to be uploaded and downloaded.  This is all running in a kubernetes environment with a fixed block volume size via PVC.  The pvc will error out with "out of space" kind of error and will notify the users that the space is full.  I was hoping to have some kind of indicator in the client to show how much disk space was used or left so that the end user can be proactive with the space allotment instead of waiting for the "disk full" error.  You are correct there are work arounds, this seemed like it was the easiest for me, and the most readily visible to the end users.  Thank you for considering my request.

I do have another question, I am trying to figure out how to provision resources for this application with respect to CPU and memory requirements.  Currently I have it running on a single vcpu and 1 gig of ram node and it struggles to upload anything bigger than 1 meg file.  The upload progress bar just freezes so I am guessing that it is running out of resources.   So in kubernetes 1000m = 1 core, so what would you recommend for your application?

**Comment by coderaiser** [comment]
About your case with information about size it can be handled with help of using `user menu` with `terminal` (the simplest) or with backend part which do the same :).

About freeze on uploading 1 Meg file looks like you should configure `ingress`. Could you reproduce this in local environment?

**Comment by LunaticProgrammer** [comment]
if you're really considering this and want a status of disk available and used we can use the df on linux and du on windows and  then the output we got from the terminal we can parse it and can change in into a graphical form on GUI hope i made sense.

**Comment by Daxcor69** [comment]
Hi, yeah that makes sense. It is not a big deal at this point. I am early in my development stage and that is a minor detail. I first have to figure out why I can't upload a file no bigger than a meg.  I am learning kubernetes and docker containers at the same time, so there is a lot of room for a miss configuration.  You mentioned ingress.  I didn't see any settings that would make sense to this error.  I haven't had time to do any testing other than just launching the app in a container.  I will work on it and let you know if I am still having issues.
