### ISSUE TITLE
Chinese translation on "http://cloudcmd.io/"

### ISSUE THREAD

**Issue by j35tor** [coderaiser/cloudcmd#301]
Hello coderaier,

Thanks for making cloudcmd for us, and it really helpful.
I am interested to contribute the project back by doing Chinese translation on the "http://cloudcmd.io/", say using the endpoint 
hk.cloudcmd.io.

Is it sound good to you?  If that is cool, Please advise how I can merge the Chinese translation that fit to your git.
Cheers,

**Comment by coderaiser** [comment]
Hi @j35tor what a nice idea :). You can copy files from https://github.com/cloudcmd/ru (excluding version files, they will be generated on each release) and update `index.md` with `HELP.md` content. Call the repo `hk` and move it to `cloudcmd` organization, you will have write access to this translation repo to have ability to update it’s content when `HELP.md` is changed.

**Comment by j35tor** [comment]
Hello, @coderaiser, Thanks for your reply.  I am working on the translation.  When I directly edit on the index.md; I have also setup a json file that map the "labels" as individual object (ru/en/hk).   Maybe  this json mapping file will help other peoples to translate cloudcmd to different lang (say German).  What would you say?  Cheers,   ;)   
//====
[cloudcmd_hk_json.txt](https://github.com/coderaiser/cloudcmd/files/5382345/cloudcmd_hk_json.txt)

**Comment by coderaiser** [comment]
@j35tor that’s an interesting idea :), but what with resulting markdown file, is it supports `json` files?

**Comment by j35tor** [comment]
Hi, @coderaiser,  maybe my previous inputs confused you.  What I mean is, embedding the markdown file with some anchors/placeholders like "obj1",  then merge the markdown file with the json file like 👇 

{
"obj1":{"ru":"Главная","en":"Home","hk":"主頁"},"
obj2":{"ru":"Блог","en":"Blog","hk":"博客"}," 
...}
Anyway, I will keep on working on the markdown file as a simpler approach (even the progress is a bit slow as I have other headache to deal with 😅

**Comment by coderaiser** [comment]
@j35tor, do you have any progress on this?

**Comment by j35tor** [comment]
Hello again @coderaiser,  Thanks for your follow-up.  Unfortunately, I am currently being haunted by a family matter and hopefully it will be resolved at the end of Jan 2021.  I think I can resume my translation work by that time.  For your information,  my previous suspended work had done around 40%.

**Comment by j35tor** [comment]
Dear @coderaiser, just a quick update: my family issue has been settled (eventually 😅), and I am now resuming the work.  I will let you know once get the thing done.   Thanks for your understanding.

**Comment by coderaiser** [comment]
@j35tor , OK, no problem :).

**Comment by coderaiser** [comment]
Any progress on this?
