### ISSUE TITLE
No service workers!

### ISSUE THREAD

**Issue by boazmvx** [coderaiser/cloudcmd#305]
Hi there 
Trying to run on rpi zero w, getting error: No service workers!

* **Version** (`cloudcmd -v`): v14.9.3
* **Node Version** `node -v`: v14.15.1
* **OS** (`uname -a` on Linux): Linux raspberrypi 5.4.51+
* **Browser name/version**: 
* **Used Command Line Parameters**: --no-open 
* **Changed Config**:

**Comment by coderaiser** [comment]
@boazmvx could you please tell me where do you see this error, and how did you installed `Cloud Commander`?

**Comment by boazmvx** [comment]
Hi 
installed vie npm: npm install -g cloudcmd
then run:
cloudcmd --no-open

got output:
url: http://localhost:8000/

and after a second get this message:
No free workers! Promise { <rejected> 'No free workers!' }

and the app exited

for a moment i could brwose to port 8000 and see the folder content 

hope it helps
thanks!

**Comment by coderaiser** [comment]
Could you please try to run `Cloud Commander` with `env` variable `THREAD_IT_COUNT=0`:

```
THREAD_IT_COUNT=0 cloudcmd --no-open
```

What do you see now?

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
