### ISSUE TITLE
Bandwidth Logging

### ISSUE THREAD

**Issue by Daxcor69** [coderaiser/cloudcmd#306]
I am going to use cloudcmd as middleware. Is there a way to log bandwidth or amount of bytes rx and tx to a specific directory?  I need to monitor usage to make sure there isn't abuse.  I wont be using authentication, but specifying a root(home dir) for each user.  So if it a log file, then I need to log the directory as well, because I can identify the user by the name of the home dir.  Thanks for the consideration.

Brad

**Comment by coderaiser** [comment]
Hi Brad, there is no such feature as logging right now, but that's a good idea for a Pull Request :).

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
