### ISSUE TITLE
Is it possible to exclude .{hidden}  from file/dir list?

### ISSUE THREAD

**Issue by Daxcor69** [coderaiser/cloudcmd#307]
Is it possible to exclude . files from the list of dir and files?

**Comment by coderaiser** [comment]
No, but it's a good idea for a pull request :). And first place for this could be [readify](https://github.com/coderaiser/readify).

**Comment by Daxcor69** [comment]
I would love to help in the project. I am just not a strong nodejs coder yet. I would be afraid of putting my hacked code into something that others would use.  I will have a look and see what the code looks like maybe it is easy.

**Comment by coderaiser** [comment]
Ok,
- [ ] we can start from making `raw` boolean, not string `type="raw"` (it's not really hard, there is plenty tests);
- [ ] then we can introduce new boolean option `dot`, which is enabled by default, but, can be disabled;
- [ ] `readify` used by `flop`, this change will be [pretty simple](https://github.com/coderaiser/flop/blob/v8.1.0/lib/flop.js#L51-L52);
- [ ] then [restafary](https://github.com/coderaiser/node-restafary/blob/v8.2.7/server/fs/get.js#L16-L20) should be updated;
- [ ] then [client side](https://github.com/coderaiser/cloudcmd/blob/v14.9.3/client/client.js#L330-L351) should be updated;
- [ ] then we can add new option `showHiddenFiles` to [Cloud Commander's config](https://github.com/coderaiser/cloudcmd/blob/v14.9.3/json/config.json).

**Comment by coderaiser** [comment]
Just landed ability to hide dot files in [Cloud Commander v18.1.0](https://github.com/coderaiser/cloudcmd/releases/tag/v18.1.0) 🎉. Is it works for you?
