### ISSUE TITLE
Following symlinks in cloud commander?

### ISSUE THREAD

**Issue by vinhdizzo** [coderaiser/cloudcmd#308]
Hi, this is not a bug report.  I just started an instance of Cloud Commander on docker.  I mapped a few folders from the host onto the container.  I can access the files fine.  I do have some symbolic links in my directories that goes to other paths on the host OS.  Was wondering if there is an option to follow those symlinks in Cloud Commander?  Right now, they show up as files empty files on Cloud Commander.

Thank you!

**Comment by coderaiser** [comment]
Could you please provide path examples of mapped directories and paths symlinks refer to, you can use `ls -lha` for this purpose. `Cloud Commander` supports symlinks to directories, but if symlink path not exists on file system of running docker container, it will definitely showed as a file.

**Comment by vinhdizzo** [comment]
On the host OS, I have the following in `/`:
```
lrwxrwxrwx   1 root root   57 Aug 12 14:32 lariat -> /srv/dev-disk-by-id-ata-ST4000DM000-1F2168_W3006CCQ-part1
```

Docker maps host to container: `/lariat` -> `/lariat`.

In the container, this shows up in `/`:
```
drwxrwsrwx   7 nobody users   4.0K Oct  3 20:04 lariat
```

**Comment by coderaiser** [comment]
If docker will give you access to symlink content it will be security breach.
