### ISSUE TITLE
Версия

### ISSUE THREAD

**Issue by zedzhen** [coderaiser/cloudcmd#312]
На сайте нет информации о новых версиях, а также устаревшая версия параметров.

**Comment by coderaiser** [comment]
Речь идет об [истории версий](http://ru.cloudcmd.io/#%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D1%8F-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B9) на русскоязычной версии сайта?
У меня нет возможности ее поддерживать, буду рад любой помощи :).

**Comment by zedzhen** [comment]
Да.
У меня есть желание и возможность обновить и стараться поддерживать актуальной информацию на русской версии сайта.

**Comment by coderaiser** [comment]
В репозитории [cloudcmd/ru](https://github.com/cloudcmd/ru/blob/master/index.md) находится черновая версия русскоязычного сайта, а [тут](https://github.com/coderaiser/cloudcmd/wiki/ru.cloudcmd.io) список непереведенных правок. Пул риквесты приветствуются :).

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
