### ISSUE TITLE
Bug: Firefox thinks files are named "",

### ISSUE THREAD

**Issue by whitespine** [coderaiser/cloudcmd#313]
When manipulating certain files in firefox (either via right click or hotkeys, doesn't seem to matter), cloudcmd seems to lose track of the files actual name.
See the following screenshot, the result of dragging the file "KICK.png" from the left pane to the right pane.
![image](https://user-images.githubusercontent.com/16845226/104833718-cdf28c00-5868-11eb-84f3-1f1e67fd7011.png).

Attempting to continue this operation will instead copy the entire folder containing KICK. Deleteing one of these strange files will delete the whole folder (rip my files).

Behavior varies between files, between refreshes, and even over the course of repeated delete-cancel cycles of the same file without refreshing the page.

Here dragging NEUTRAL.png from left to right produces a valid prompt:
![image](https://user-images.githubusercontent.com/16845226/104833883-08105d80-586a-11eb-8c8a-dbf0e8b02d76.png)

And moments later it ceases to work:
![image](https://user-images.githubusercontent.com/16845226/104833900-18283d00-586a-11eb-9d5b-e48e37c57760.png)

Seems to trend unerringly towards everything showing up as "".

Same site works fine on Chrome. Error only in firefox.
Erroneous firefox behavior persists even in incognito tab, and after having cleared cache on the site.

Console is filled with the following error:
`e.classList is undefined`
Unclear if it is related. Does not show up in chrome, so maybe?

* **Version**: v15.2.0
* **Node Version** `node -v`: 14.15.4
* **OS** (`uname -a` on Linux): `Linux localhost 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* **Browser name/version**: Firefox 84.0.2
* **Used Command Line Parameters**:  none (see config changes below / attached file)
* **Changed Config**: 
```
{
    "name": "Tartarus!",
    "auth": true,
    "username": "root",
    "password": "redacted",
     ...
    "editor": "dword",
     ...
    "port": 40100,
     ...
    "root": "/home/tartarus",
    "prefix": "/tartarusfiles",
     ...
    "contact": false,
     ...
    "configDialog": false,
     ...
    "showConfig": false,
}
```

**Comment by whitespine** [comment]
Update I found immediately after: The file element "title" html attributes appear to be getting cleared somehow.

**Comment by whitespine** [comment]
Update 2: After once again turning off all addons and turning them on one by one, it turns out it was the `Imagus` firefox extension causing the issue. Evidently it was overriding the title attribute to make its own custom image subtitles or something like that, I have no idea. Considering the popularity of the extension, it might be wise to use a less possibly-affected parameter, like `data-filename`, to figure out what files are being manipulated, rather than `title`.

**Comment by coderaiser** [comment]
Thank you for report :). The thing is `title` is useful from user perspective and from `Cloud Commander` internals as well.
> Considering the popularity of the extension, it might be wise to use a less possibly-affected parameter, like data-filename, to figure out what files are being manipulated, rather than title.

Actually [setCurrentName](https://github.com/coderaiser/cloudcmd/blob/master/client/dom/current-file.js#L33-L48) already uses `data-name=js-name-`.
And [getCurrentName](https://github.com/coderaiser/cloudcmd/blob/master/client/dom/current-file.js#L55-L68) works with `title` but can also use `data-name`.

There is already test for [setCurrentName](https://github.com/coderaiser/cloudcmd/blob/master/client/dom/current-file.spec.js#L13-L33), would be amazing to have a test for `getCurrentName` to avoid regressions.

Fixing this is a good idea for a pull request :). Are you in?

**Comment by whitespine** [comment]
I am sorta neck deep in another project right now 😅, but I could maybe give it a shot? I think I'm unclear what the intended behavior is, though. Is it to change getCurrentName to use data-name? Or is it just to make a test for getCurrentName (in which case, is data-name meant to be checked?)

**Comment by coderaiser** [comment]
> I am sorta neck deep in another project right now 😅,
So do I 🙂 .

Create two functions:

```js  
const createNameAttribute = (a) => `js-file-${btoa(encodeURI(a))}`;
   
const parseNameAttribute = (a) => a.replace(`js-file-, '');
```

And use `createNameAttribute` in `setCurrentName` and `parseNameAttribute` in `getCurrentName`:

```diff
module.exports.getCurrentName = (currentFile) => {
    const current = currentFile || DOM.getCurrentFile();
    
    if (!current)
        return '';
      
+      const attribute = current.getAttribute('data-name');  
+      return parseNameAttribute(attribute);

-    const link = DOM.getCurrentLink(current);
- 
-    if (!link)
-        return '';
-    
-    return decode(link.title)
-        .replace(NBSP_REG, SPACE);
};
```

**Comment by whitespine** [comment]
Been stuck for a few hours on a small problem, that I don't really know how to resolve.
The logic changes seem to work just fine - the bug no longer manifests in firefox. However, I've been unable to get a test case working, largely because of the following issue. This code:
```
current.setAttribute('data-name', this.createNameAttribute(name));
console.log("Set current name: ", this.createNameAttribute(name));
console.log("Retrieving: ", current.getAttribute('data-name'));
```

produces this output:
```
Set current name:  js-file-aGVsbG8lMjB3b3JsZC50eHQ=
Retrieving:  undefined
```
Do you have any suggestions about how to actually test getCurrentName, when `getAttribute` doesn't seem to behave properly in tests?

**Comment by coderaiser** [comment]
Make a PR, I'll take a look.
