### ISSUE TITLE
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

### ISSUE THREAD

**Issue by doublethinkio** [coderaiser/cloudcmd#317]
* **Version** (`cloudcmd -v`):  v15.3.3
* **Node Version** `node -v`:  v14.15.4
* **OS** (`uname -a` on Linux):  windows 10
* **Browser name/version**:  chrome
* **Used Command Line Parameters**:   cloudcmd --port 2021
* **Changed Config**:  none

```
Received protocol 'c:' Promise {
  <rejected> Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
      at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:782:11)
      at Loader.resolve (internal/modules/esm/loader.js:86:40)
      at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
      at Loader.import (internal/modules/esm/loader.js:165:28)
      at importModuleDynamically (internal/modules/cjs/loader.js:1006:27)
      at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
      at C:\Users\backtolife\AppData\Local\Yarn\Data\global\node_modules\simport\simport.js:22:26
      at validateRoot (file:///C:/Users/backtolife/AppData/Local/Yarn/Data/global/node_modules/cloudcmd/bin/cloudcmd.mjs:224:28)
      at main (file:///C:/Users/backtolife/AppData/Local/Yarn/Data/global/node_modules/cloudcmd/bin/cloudcmd.mjs:206:11) {
    code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
  }
}
```

see: https://github.com/nodejs/node/issues/31710

**Comment by coderaiser** [comment]
Thanks a lot :). Fixed with [simport v1.0.6](https://github.com/coderaiser/simport/releases/tag/v1.0.6). 
Could you please reinstall `Cloud Commander` with:

```sh
npm i cloudcmd -g
```

Is it works for you? 

If not, please check `simport` version in:
```
C:\Users\backtolife\AppData\Local\Yarn\Data\global\node_modules\simport\package.json
```

**Comment by coderaiser** [comment]
Landed in [v15.4.1](https://github.com/coderaiser/cloudcmd/releases/tag/v15.4.1) 🎉

**Comment by doublethinkio** [comment]
> 非常感谢 ：）。已通过[simport v1.0.6修复](https://github.com/coderaiser/simport/releases/tag/v1.0.6)。
> 您可以重新安装以下内容吗`Cloud Commander`？
> 
> ```shell
> npm i cloudcmd -g
> ```
> 
> 对你有用吗？
> 
> 如果不是，请检查以下`simport`版本：
> 
> ```
> C:\Users\backtolife\AppData\Local\Yarn\Data\global\node_modules\simport\package.json
> ```

![image](https://user-images.githubusercontent.com/24669431/105463730-74a4b580-5ccb-11eb-86d4-0015d0df764e.png)

It can run now, but the file list is empty

**Comment by coderaiser** [comment]
Could you please open `console` and check if it has errors? What version do you using right now?

**Comment by doublethinkio** [comment]
![image](https://user-images.githubusercontent.com/24669431/105535676-1b1fa380-5d2a-11eb-8de4-b463c9e06bff.png)
![image](https://user-images.githubusercontent.com/24669431/105535729-31c5fa80-5d2a-11eb-8e9a-05cfd82a04c2.png)

**Comment by coderaiser** [comment]
Could you open url `http://localhost:8000/fs/c/`?

**Comment by doublethinkio** [comment]
> http://localhost:8000/fs/c/

The file list appears after the path is completed. Thank you for your reminder.

**Comment by coderaiser** [comment]
I close it for now, the bug in header is fixed and other I can’t reproduce. Write if you have more info.
