### ISSUE TITLE
Error "ENOENT: no such file or directory, scandir" when accessing /mnt/fs/

### ISSUE THREAD

**Issue by Teraskull** [coderaiser/cloudcmd#318]
* **Docker image v15.4.3** (`cloudcmd -v`): 
* **5.9.0-0.bpo.5-amd64 #1 SMP Debian 5.9.15-1~bpo10+1 (2020-12-31) x86_64 GNU/Linux** (`uname -a` on Linux): 
* **Edge Dev**

![Screenshot 2021-01-26 000101](https://user-images.githubusercontent.com/24798198/105777020-f1ed5600-5f69-11eb-9e1a-cbd2824ec006.png)
![Screenshot 2021-01-26 000118](https://user-images.githubusercontent.com/24798198/105777022-f285ec80-5f69-11eb-82e8-2c0d499f6509.png)

**Comment by Teraskull** [comment]
Just tested and confirmed, that there is no issue on v15.4.1

**Comment by coderaiser** [comment]
Thanks a lot, fixed with 39bce2a, landed in [win32 v5.1.11](https://github.com/coderaiser/win32/releases/tag/v5.1.11) 🎉 .
Please re-install `Cloud Commander`. Is it works for you?

**Comment by Teraskull** [comment]
Thanks a lot! Will test once the docker image will be available to pull.

**Comment by coderaiser** [comment]
Landed in [v15.4.4](https://github.com/coderaiser/cloudcmd/releases/tag/v15.4.4) 🚀 .

**Comment by Teraskull** [comment]
Looks like everything is working on v15.4.4, thanks again!
