### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by mhbates** [coderaiser/cloudcmd#319]
This happens when I try to create a directory.

* **Version** (`cloudcmd -v`):  Docker, 20.10.2, build 2291f61
* **Node Version** `node -v`: 15.7.0
* **OS** (`uname -a` on Linux): Debian Buster
* **Browser name/version**: Firefox 85
* **Used Command Line Parameters**:  	

> -v /home/$USER/cloudcmd/config:/root \\
> 	-v /:/mnt/fs \\
> 	-p 8000:8000 \\
> 	-u 1000 \

![image](https://user-images.githubusercontent.com/18390027/106373401-de593b00-632d-11eb-8f24-78edb619cf83.png)

**Comment by coderaiser** [comment]
Thanks a lot :), fixed with [redzip v1.6.4](https://github.com/coderaiser/redzip/releases/tag/v1.6.4), landed in [v15.5.1](https://github.com/coderaiser/cloudcmd/releases/tag/v15.5.1) 🎉 .

Is it works for you?

**Comment by mhbates** [comment]
Fixed, thank you
