### ISSUE TITLE
Корневой каталог

### ISSUE THREAD

**Issue by wormen** [coderaiser/cloudcmd#32]
Здравствуйте
у меня такой вопрос ... у меня есть единый каталог для хранения файлов, но для определенных пользователей, нужно указать, какой у них каталог является корневым

в описании параметров, вижу. что есть параметр <b>--root</b> который указывает корневой каталог для файлового менеджера

есть ли у вас поддержка динамической смены корневого каталога? т.е. для каждого пользователя, так сказать он должен выставляться на лету, в соответствии с настройками системы, и при этом в самом ФМ авторизация должна быть отключена

**Comment by coderaiser** [comment]
Динамической смены нет, но есть настройка для каждого пользователя.

Вы можете создать файл `.cloudcmd.json` в домашнем каталоге пользователя и там прописать корневой каталог в параметре `root`.

Во-время запуска `Cloud Commander` смотрит на параметры командной строки, если не находит нужных, читает настройки из файла в домашнем каталоге, а если и там не находит нужных данных - берет параметры по-умолчанию.

**Comment by wormen** [comment]
дело в том, что авторизация из системы тут не актуальна, т.к. по факту приложение работает от одного пользователя

**Comment by coderaiser** [comment]
>для каждого пользователя, так сказать он должен выставляться на лету, в соответствии с настройками системы, и при этом в самом ФМ авторизация должна быть отключена

Как тогда должен подхватываться путь к корневому каталогу, на основании каких данных?
И каких настроек системы, если пользователь один?

**Comment by wormen** [comment]
так как я вставляю это в движок, то есть данные пользователя, а там уже есть все необходимое, включая пути к нужному каталогу

**Comment by coderaiser** [comment]
У вас движок на `node.js` написан? Вы можете попробовать использовать Cloud Commander, как `middleware`. Большая часть работы уже проделана, осталось адаптировать пару моментов под ваши нужды, и вы сможете динамически подставлять нужную директорию.

**Comment by wormen** [comment]
да, двига на ноде
про middleware можно подробнее?

**Comment by coderaiser** [comment]
Приблизительно, как [здесь](https://github.com/cloudcmd/edward "Edward"), но с небольшим допиливанием. Если у вас получатся хорошие результаты - я смогу влить это в основную кодовую базу. И любой сможет использовать `Cloud Commander` как `middleware`. Я думаю это не плохо.

Вот неплохая статья на эту тему: [Writing Middleware for Connect / Express.js](http://www.hacksparrow.com/how-to-write-midddleware-for-connect-express-js.html "Writing Middleware for Connect / Express.js").

**Comment by wormen** [comment]
просьба тут пока не закрыть, .... будет еще что написать

**Comment by wormen** [comment]
с помощью `middleware` у меня сейчас внедрить не получится, так как шаблонизатор в ФМ конфликтует с angular

поэтому, как изначально и планировал, будет вставка из iframe ... и вот тут, было бы неплохо, чтобы в ФМ можно было передавать параметры через GET

но как я понял, сейчас это не реализовано, но лишним точно не будет

**Comment by coderaiser** [comment]
**REST** описан [тут](https://github.com/coderaiser/node-restafary).
Вы можете вносить предложения основываясь на таблице текущих **CRUD**-операций.

**Comment by coderaiser** [comment]
Closed due to long time of inactivity.
