### ISSUE TITLE
Bottom Buttons Don't (always) Work

### ISSUE THREAD

**Issue by frakman1** [coderaiser/cloudcmd#321]
* **Version** (`cloudcmd -v`): v15.5.1
* **Node Version** `node -v`: v15.7.0
* **OS** (`uname -a` on Linux): Linux 70504fae93ac 4.19.107-Unraid #1 SMP Thu Mar 5 13:55:57 PST 2020 x86_64 GNU/Linux
* **Browser name/version**: Chome Version 88.0.4324.96 (Official Build) (x86_64)
* **Used Command Line Parameters**: 
```bash
docker run -d --name='CloudCommander' --net='bridge' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'HOME'='/root' -p '8765:8000/tcp' -v '/<my-path>/':'/UNRAID':'rw' -v '/mnt/user/appdata/cloudcmd':'/root':'rw' -u 99:100 'coderaiser/cloudcmd'
```

When connecting to the IP:Port location, everything works fine.
When connecting remotely via `subdomain.domain.com` behind reverse proxy, most functionality works (file browsing, upload and download etc) but none of the bottom panel buttons work. Clicking on them does nothing. If I have auth enabled, it goes into a never ending loop of asking for username/password all the time.

**Comment by coderaiser** [comment]
Do you have any errors in `Chrome Developer Tools` `Console` and `Network Panel`?

**Comment by frakman1** [comment]
I am no longer able to reproduce this error since moving to 15.5.2
I use Nginx Proxy Manager (NPM).
There is an issue when enabling HTTP authorization in both NPM and Cloud Commander's 'auth' option. It goes into a never ending loop but that could be a different problem. For now, I can just disable HTTP auth for that domain in NPM and enable it in Cloud Commander and it works that way.
