### ISSUE TITLE
CloudCmd - Win 10

### ISSUE THREAD

**Issue by pzGrant** [coderaiser/cloudcmd#327]
First, let me start by telling you how much I love this app. It is INCREDIBLE! I used it on an old OMV headless server to move files at home.

However, I'm now trying to use it on Windows 10, but when I attempt to launch the .exe, a terminal windows opens/closes immediately, and ... nothing happens.

I'd be really grateful for any advice on installation/requirements to get cloudcmd up and running on this Win 10 server (again, just a home hobby project).

Thanks so much for your skill, work, and for sharing.

Regards
Paul

* **Version** (`cloudcmd -v`): 
* **Node Version** `node -v`: 
* **OS** (`uname -a` on Linux): 
* **Browser name/version**: 
* **Used Command Line Parameters**: 
* **Changed Config**:

**Comment by coderaiser** [comment]
Hi Paul, I glad that `Cloud Commander` is useful for you :).
Could you please tell me what `exe` are you launching? And what version of `node.js` are you using?

**Comment by pzGrant** [comment]
Hi there.

The .exe is the 14.9.3-win-x64 standalone.

I have tried it with nodejs:

4.15.5 x64 and 15.8.0 x64

With the latest nodejs I can launch a cloudcmd from Power Shell, but it
doesn't show any drives.

The cloudcmd standalone exe exhibits the same behaviour with either nodejs
- a terminal windows flashes up then closes.

Thanks for your help!

Regards
Paul

From the Mind of pZg

**Comment by coderaiser** [comment]
Please install [nodejs](https://nodejs.org/en/) and Cloud Commander, using:

```
npm i cloudcmd -g
```

Standalone no longer supported because they do not supports latest JavaScript features.

**Comment by pzGrant** [comment]
Hi.

I've done that, and cloudcmd starts 😁😁😁.

How do I add volumes to cloudcmd? I wish to add disks in the PC and a
network drive I have mounted.

Please forgive my inexperience in setti g this up. Thanks again for all
your help, I really do appreciate it.

Regards
Paul

From the Mind of pZg

**Comment by coderaiser** [comment]
`Cloud Commander` receives all volumes [this way](https://github.com/coderaiser/win32/blob/v5.2.0/lib/win32.js#L46):

```
wmic logicaldisk get name
```

Isn't it returns all mounted volumes? Could you please try it in `cmd.exe` or `powershell`?

**Comment by pzGrant** [comment]
That returns a list of the drives that are mounted.

C:
D:
E:
Z:

cloudcmd still opens with no directory/files.

Cheers.
Paul

From the Mind of pZg

**Comment by coderaiser** [comment]
Could you please make a screenshot? Also check what version you have installed (with `F1`)

**Comment by pzGrant** [comment]
Hey!

I'll grab them tomorrow.

Thanks so much for your patience and help.

Regards
Paul

From the Mind of pZg

**Comment by pzGrant** [comment]
Hey there.

I hope you had a nice evening.

I've attached some screenshots (well, pictures).

I *did* have success about 10 mins ago, I ran cloudcmd in PowerShell and it
populated the volumes. However, when I closed it in PS and re-ran it the
volumes were gone.

I get the same negative results in either PowerShell or Command Prompt.
Running either as Admin has no positive effect.

Regards
Paul

From the Mind of pZg

**Comment by coderaiser** [comment]
Hi Paul, I can’t find images you attached.

**Comment by pzGrant** [comment]
Hi there.

I hope you had a great weekend.

I think I forgot to attach the pics ... D'oh!

I've attached them. The cloudcmd version is 15.6.0

Cheers
Paul

From the Mind of pZg

**Comment by coderaiser** [comment]
Looks like when you using email client to attach images, they do not go to github issue  page :).

**Comment by pzGrant** [comment]
![IMG_20210214_123247_compress94](https://user-images.githubusercontent.com/45203255/108055392-d3015180-7047-11eb-8f33-16455b91aa87.jpg)
![IMG_20210214_123247_compress94](https://user-images.githubusercontent.com/45203255/108055414-dd235000-7047-11eb-9b07-7eb68ecaa4cc.jpg)
![IMG_20210214_123316_compress85](https://user-images.githubusercontent.com/45203255/108055420-ddbbe680-7047-11eb-86c8-ede24f0192b9.jpg)
![IMG_20210214_123544_compress50](https://user-images.githubusercontent.com/45203255/108055422-de547d00-7047-11eb-9812-698d45d5039d.jpg)

**Comment by RastaAlex** [comment]
Everything works well for me
![Снимок экрана (4)](https://user-images.githubusercontent.com/10198176/108175568-9b5ade00-7109-11eb-8d69-cf641e669ad6.png)
![Снимок экрана (5)](https://user-images.githubusercontent.com/10198176/108175593-a281ec00-7109-11eb-8585-2dcbb25c9d01.png)
![Снимок экрана (6)](https://user-images.githubusercontent.com/10198176/108175618-aada2700-7109-11eb-9ade-a2c1b8187098.png)

**Comment by coderaiser** [comment]
Closed due to inability to reproduce. @pzGrant feel free to add new details, do you have any changes with [v15.8.0](https://github.com/coderaiser/cloudcmd/releases/tag/v15.8.0)?
