### ISSUE TITLE
Права доступа

### ISSUE THREAD

**Issue by wormen** [coderaiser/cloudcmd#33]
Подскажите, каким образом в вашем ФМ можно изменить права доступа к файлам и каталогам? по этому поводу я вообще нигде никаких упоминаний не встретил, и функционала так же не вижу

**Comment by coderaiser** [comment]
Права доступа через интерфейс в данный момент нельзя изменить, поскольку подобный функционал может сильно отличатся на Windows и Linux (изнутри и снаружи). Вы можете использовать консоль для этих нужд.
Пул риквесты приветствуются.
Начать можно с модулей из npm. Вы встречали модули такого типа?

**Comment by wormen** [comment]
а в чем проблема, чтобы определить ОС? насколько знаю, это всего 2 строки кода, и на основе этого уже можно сделать реализацию .... хотя бы пока для  *nix систем

**Comment by wormen** [comment]
к слову про права доступа
http://ru.code-maven.com/system-information-about-a-file-or-directory-in-nodejs

**Comment by coderaiser** [comment]
Вы можете запилить стартовую реализацию отдельным модулем,  это будет отправной точкой.
У меня пока нет возможности реализовывать подобный функционал.

**Comment by wormen** [comment]
да, конечно, реализация разная, именно поэтому и нужно от платформы отталкиваться

**Comment by coderaiser** [comment]
Closed due to long time of inactivity.
