### ISSUE TITLE
UI crashes if a file contains special characters

### ISSUE THREAD

**Issue by derinbay** [coderaiser/cloudcmd#330]
* **Version** (`cloudcmd -v`): 15.7.1
* **OS** (`uname -a` on Linux): Raspbian, docker
* **Browser name/version**: Firefox, chrome

As a user, if I'm entering a folder and if that folder contains a file with turkish charachters (ü, ç, ş, ı etc.), the ui fails. It shows a blank screen as in screenshot.

<img width="1712" alt="Screen Shot 2021-02-26 at 18 58 22" src="https://user-images.githubusercontent.com/2565698/109323852-f9539800-7864-11eb-81eb-3a9ee67ba5cc.png">

**Comment by coderaiser** [comment]
Thanks a lot :). Fixed with https://github.com/coderaiser/node-restafary/commit/4ff904ccf7fc8f8799b567d983bb31230ac31a1a. Landed in [v15.8.1](https://github.com/coderaiser/cloudcmd/releases/tag/v15.8.1) 🎉 .

Is it works for you?

**Comment by derinbay** [comment]
Wow thanks for the fast fix.
Yeah, I've updated now and it seems that if fixed.
Thanks again, great work.
