### ISSUE TITLE
environment CLOUDCMD_PASSWORD strange behavior

### ISSUE THREAD

**Issue by OnBartt** [coderaiser/cloudcmd#331]
Hi, I run cloud commander via docker-compose  and found interisting 'thin'. When I use the following code:
```cloudcmd:
    image: "coderaiser/cloudcmd"
    container_name: "cloudcmd"
    volumes:
      - "/home:/home"
    environment:
      - "CLOUDCMD_AUTH=true"
      - "CLOUDCMD_USERNAME=name"
      - "CLOUDCMD_PASSWORD=$$..."
    labels:
    # enable this service in traefik
      - "traefik.enable=true"
      # create rule for cloudcmd-internal router
      - "traefik.http.routers.cloudcmd-internal.rule=Host(`domain`)"
      - "traefik.http.routers.cloudcmd-internal.entrypoints=my_point"
```
And run the commander online, the authentication needs a actual hash as the password and not the original word. Am I doing something wrong?

Thanks for feedback 

OnBartt

**Comment by coderaiser** [comment]
Environment variable needs password, to make hash from it.

**Comment by OnBartt** [comment]
Okey, I see. Thank you for the answer :)
