### ISSUE TITLE
Unable to navigate between folders

### ISSUE THREAD

**Issue by Dominiquini** [coderaiser/cloudcmd#333]
I was unable to navigate between folders. It looks like the directory tree is duplicated in some way!

![sAvFRrSGAy](https://user-images.githubusercontent.com/1180808/111262291-c4846680-8602-11eb-9032-03c1b0d1fe92.png)

* **Version** (`cloudcmd -v`): 15.9.1
* **Node Version** `node -v`: 15.7.0
* **OS** (`uname -a` on Linux):  Windows 10 x64 Version 20H2 (OS Build 19042.867)
* **Browser name/version**: Firefox 86.0.1
* **Used Command Line Parameters**: cloudcmd --open false --root "F:\Downloads"
* **Changed Config**: ---

Thanks

**Comment by coderaiser** [comment]
Looks like a bug in [win32](https://github.com/coderaiser/win32). Unfortunately I don't have `windows` to check this.

**Comment by coderaiser** [comment]
Fixed with df60dd7, landed in [v15.9.2](https://github.com/coderaiser/cloudcmd/releases/tag/v15.9.2) 🎉 .
Is it works for you?

**Comment by Dominiquini** [comment]
Hi,

I updated here and the same problem continues!

![uuo9BYciXz](https://user-images.githubusercontent.com/1180808/111345775-579dba80-865c-11eb-934a-79e55e155377.png)

Is there any information I can provide to help with this bug? 

Thanks.

**Comment by coderaiser** [comment]
You can support me on [patreon](https://www.patreon.com/coderaiser), so I can test `Cloud Commander` on [azure](https://azure.microsoft.com/en-us/) this can help a lot :).

Could you please re-install `Cloud Commander`, I just updated [win32](https://github.com/coderaiser/win32/releases/tag/v6.0.2), this can help.

**Comment by Dominiquini** [comment]
Hi,

I update again and is working now!

Thanks.
