### ISSUE TITLE
Error when uploading from cloud

### ISSUE THREAD

**Issue by Toomblr** [coderaiser/cloudcmd#336]
* **v15.9.2** (`cloudcmd -v`): 
* **15.11.0** `node -v`: 
* **Linux acd2f61292d6 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 GNU/Linux** (`uname -a` on Linux): 
* **Firefox 86.0.1 (64-bit)**: 

When rightclicking in a  folder, I normally could choose "upload from cloud". Today I noticed this resulted in this error:
 **App: AACq5fTfzRY2E_Rw_4kyaz exceeds the limit.**

**Comment by coderaiser** [comment]
That's right, here is the prices for [filestack](https://www.filestack.com/pricing/), you can subscribe to some of plans, or support me on [patreon](https://www.patreon.com/coderaiser), so I can increase limits :).
