### ISSUE TITLE
Интерфейс

### ISSUE THREAD

**Issue by wormen** [coderaiser/cloudcmd#34]
Подскажите, как я могу настроить интерфейс, так как мне нужно
например
1) убрать в футере некоторые кнопки. чтобы не было желания туда тыкнуть
2) отключить некоторые пункты контекстного меню

... еще, раз ФМ мультиязычный ... интересно, почему не реализованы локализации

**Comment by coderaiser** [comment]
1) Это вы можете сделать правкой [index.html](https://github.com/coderaiser/cloudcmd/blob/8df6e4dddd9b714d2a9e4b46511b3cce6f20a8bd/html/fs/index.html), пока-что такой потребности небыло.
2) Тут вы можете под свои нужны поправить [menu.js](https://github.com/coderaiser/cloudcmd/blob/8df6e4dddd9b714d2a9e4b46511b3cce6f20a8bd/lib/client/menu.js).

`Cloud Commander` не мультиязычный. Мультиязычная только документация [на сайте](http://cloudcmd.io "Cloud Commander").
К сожелению, у меня нет возможности поддерживать несколько локализаций в актуальном состоянии, в данный момент времени.

**Comment by wormen** [comment]
спасибо, понятно .... есть на эту тему несколько идей ...

**Comment by wormen** [comment]
... еще вопрос ... шаблошизатор самописный?

**Comment by coderaiser** [comment]
[Rendy](https://github.com/coderaiser/rendy "Rendy") - простейший шаблонизатор совместимый с  [handlebars](http://handlebarsjs.com "Handlebars"), [mustache](https://mustache.github.io "Mustache") и т.д.

**Comment by wormen** [comment]
в каких файлах я могу глянуть, как происходит взаимодействие с интерфейсом ... при беглом просмотре, пока не понял

**Comment by coderaiser** [comment]
Основные обработчики навешиваются в [lib/client/listeners.js](https://github.com/coderaiser/cloudcmd/blob/8a973691035e42beaaf6d92a7c26bc9c4fece6b8/lib/client/listeners.js).

**Comment by wormen** [comment]
а остальные?

**Comment by wormen** [comment]
тут тоже просьба пока не закрывать ... есть некоторые мысли по модификации интерфейса

**Comment by coderaiser** [comment]
> например контекстное меню
[onContextMenu](https://github.com/coderaiser/cloudcmd/blob/8a973691035e42beaaf6d92a7c26bc9c4fece6b8/lib/client/listeners.js#L176).

**Comment by wormen** [comment]
если я правильно понял, вышеуказанный шаблонизатор работает аналогично React? так как не вижу никаких запросов в браузере ... я полагаю что они происходят где-то в фоне ...

**Comment by coderaiser** [comment]
Нет, намного проще. `rendy` как и реакт работает и в браузере и в `node.js`.
На сервере код гененируется в файле [lib/server/route.js](https://github.com/coderaiser/cloudcmd/blob/748bb1b7b2d745b19a2f3bfb1804acb942c32660/lib/server/route.js#L197). А на клиенте в [lib/client.js](https://github.com/coderaiser/cloudcmd/blob/748bb1b7b2d745b19a2f3bfb1804acb942c32660/lib/client.js#L417).
Общий же код находится в [cloudfunc.js](https://github.com/coderaiser/cloudcmd/blob/748bb1b7b2d745b19a2f3bfb1804acb942c32660/lib/cloudfunc.js#L160).

**Comment by wormen** [comment]
в каком файле лучше подключать глобальную переменную? для внедрения локализаций. чтобы видно было как в серверной части, так и в клиентской

**Comment by coderaiser** [comment]
Можно в файле конфигурации [json/config.json](https://github.com/coderaiser/cloudcmd/blob/3c9c97560f6df87028530aec3ec717c0f55cb067/json/config) добавить поле `lang` у которого могут быть значения: "ua", "ru", "en".

**Comment by wormen** [comment]
я не про значения текущей локализации, а непосредственно сам языковой файл
например у меня это подключается так
> global.lang = require('./config/lang.js');

а уже в самом `lang.js` происходит необходимая обработка словаря и определение локализации, на основе того что юзер выбрал в интерфейсе, так как у каждого юзер может быть разная локализация

**Comment by coderaiser** [comment]
В таком случае можно использовать `lib/lang.js`, если код может работать и на клиенте, и на сервере (что предпочтительнее), либо `lib/server/lang.js`, если только на сервере.

**Comment by wormen** [comment]
если я положу файл сюда `lib/lang.js` это же еще не означает, что данные из него будет доступны и на сервере и на клиенте ... еще же и подключить нужно

**Comment by coderaiser** [comment]
А что в нем сейчас происходит? Подключить можна в `lib/server/route.js` и в `lib/client/cloudcmd.js`.

**Comment by wormen** [comment]
что происходит. я уже описал, я просто сделаю копию из того что у меня уже есть

**Comment by coderaiser** [comment]
Выложите код `lang.js` в [gist](https://gist.github.com). Я посмотрю что там и как.

**Comment by coderaiser** [comment]
Closed due to long time of inactivity.
