### ISSUE TITLE
Start cloudcmd on system startup

### ISSUE THREAD

**Issue by markkey014** [coderaiser/cloudcmd#347]
Not an issue actually, just want to share how I was able to add cloudcmd on systemd to start at boot especially for newbies like me since I was not able to find a guide on how to do it 

`sudo nano /etc/systemd/system/cloudcmd.service`

Dont forget to change YOUR_USER_HERE with your actual user

> [Unit]
Description=Cloud Commander
>
>[Service]
TimeoutStartSec=0
User=YOUR_USER_HERE
Restart=always
ExecStart=/usr/bin/cloudcmd
>
>[Install]
WantedBy=multi-user.target

once done, run the below commands to start and enable cloudcmd on boot

`sudo systemctl enable --now cloudcmd`
`sudo systemctl status cloudcmd`

now open your browser to url: http://localhost:8000/

**Comment by coderaiser** [comment]
Nice, it looks awesome), are you willing to make a PR into `HELP.md`?

**Comment by khevin014** [comment]
Hey bud, tried creating a PR. Not sure if I made it correctly since I'm not a pro :wink:

**Comment by coderaiser** [comment]
Merged as 262c72d 🎉 
Thanks a lot :)!
