### ISSUE TITLE
ENOENT errors

### ISSUE THREAD

**Issue by Artur4ikZX** [coderaiser/cloudcmd#349]
* **Version** (`cloudcmd -v`): latest
* **Node Version** `node -v`: 15.13.0
* **OS** (`uname -a` on Linux): Docker 5:20.10.7~3-0~debian-buster
* **Browser name/version**: Firefox 89.0
* **Used Command Line Parameters**: 
* **Changed Config**:

I can open or copy single files without problems, but as soon as I try to copy a directory, I have a series of “ENOENT” errors which prevent me from copying most of the files/directories.
Happened after clean install of a new OMV.

![Desktop Screenshot 2021 06 07 - 23 15 21 82](https://user-images.githubusercontent.com/11911711/121088876-a8016000-c7e6-11eb-86cc-441f93f70035.png)

BUT it works with coderaiser/cloudcmd:15.6.0 an older version of CloudCMD!

**Comment by Artur4ikZX** [comment]
No, I do not use symlinks.
I tried to copy/move some video/audio like mkv and flac files and the result is the same.
The error appearance only by copy/move directories.  

The person on Reddit had the same issue
[https://www.reddit.com/r/OpenMediaVault/comments/mjhvxo/enoent_errors_when_copying_files_with_cloud/](url)

**Comment by Artur4ikZX** [comment]
ok tried all versions from the last 15.9.4 to 15.7.0
and the first one that works for me is 15.6.0

**Comment by coderaiser** [comment]
Fixed with [redzip v2.1.2](https://github.com/coderaiser/readzip/releases/tag/v2.1.2) 🔨 .
Landed in [Cloud Commander v15.9.5](https://github.com/coderaiser/cloudcmd/releases/tag/v15.9.5) 🎉 .

Is it works for you?

**Comment by Artur4ikZX** [comment]
> 
> 
> Fixed with [redzip v2.1.2](https://github.com/coderaiser/readzip/releases/tag/v2.1.2) 🔨 .
> Landed in [Cloud Commander v15.9.5](https://github.com/coderaiser/cloudcmd/releases/tag/v15.9.5) 🎉 .
> 
> Is it works for you?

Yes! It works now!

Друже дуже дякую!
Усе робить тепер!
