### ISSUE TITLE
localStorage

### ISSUE THREAD

**Issue by wormen** [coderaiser/cloudcmd#35]
увидел, что для своей работы ФМ использует localStorage, не проще ли использовать для его работы sessionStorage? тогда не будет необходимости принудительно очищать историю, при заполнении localStorage

**Comment by coderaiser** [comment]
У вас часто возникает необходимость чистить `localStorage`?

**Comment by wormen** [comment]
лично у меня, да

**Comment by coderaiser** [comment]
Нужно подумать об этом. Достоинство `localStorage` перед `sessionStorage` для Cloud Commander - это возможность быстрее обрабатывать файлы, с помощью патчей. Нет необходимости, загружать одни и и теже файлы каждый раз после закрытия и открытия  вкладки. Это экономит трафик и делает приложенин отзывчивей.
Как часто приходится чистить `localStorage`? `sessionStorage` действительно решит проблему? Хранилище может и в нем переполнится, возможно его в любом случае нужно периодически чистить. Вы, кстати, каким образом чистите его?

**Comment by wormen** [comment]
разница между ними всего лишь только в том, что `sessionStorage` очищается автоматически, и все

бывает что и в день несколько раз чищу, а бывает раз в месяц ....
очистка производится из devtools

**Comment by coderaiser** [comment]
Очистить хранилище можно с помощью кнопки **Clear Storage** в левом верхнем углу каждой из панелей.

**Comment by wormen** [comment]
это я видел, но `localStorage` то сам по окончанию работы не очищается

**Comment by coderaiser** [comment]
Я написал выше плюсы этого.

**Comment by wormen** [comment]
плюсом было бы, если б для каждой панель сохранялся текущий открытый адрес, раз все сохраняется ... но я этого не увидел

**Comment by coderaiser** [comment]
Да, это было бы удобно, есть идеи по реализации?

**Comment by wormen** [comment]
так у тебя почти все готово для этого ... там всего-то нужно дописать, чтобы там панель которая в фокусе, сохраняла свой текущий адрес, ну а потом соответственно открывала его, при инициализации

**Comment by wormen** [comment]
ну и конечно нужно в деревьях, которые в `localStorage` так же дописать, к какой панели они относятся

**Comment by coderaiser** [comment]
Попробуй реализовать, я посмотрю что получится. Идея хорошая, но нужна грамотная реализация.

**Comment by wormen** [comment]
в каком файле сейчас описано сохранение в `localStorage`?

**Comment by coderaiser** [comment]
В файле `lib/client/store.js` описан универсальныф маханизм, через который все работает. А само сохранение и вычитка данных о содержимом каталога находится в `lib/client.js`.

**Comment by coderaiser** [comment]
Closed due to long time of inactivity.
