### ISSUE TITLE
How can I add a popup menu command 'Copy Link Address' like in browsers

### ISSUE THREAD

**Issue by avoitenko** [coderaiser/cloudcmd#351]
Hi.
I am using the latest version of cloudcmd.
But I cannot customize popup menu to add valuable feature.
Because I need to share link of certain file with my team.
Is there a way to add 'Copy Link Address' to the popup menu?
Thanks.

**Comment by coderaiser** [comment]
Hi, you can extend user menu for this purpose https://github.com/coderaiser/cloudcmd/issues/271#issuecomment-731757580
