### ISSUE TITLE
Only the API and auth under different users

### ISSUE THREAD

**Issue by Jebati** [coderaiser/cloudcmd#354]
A very cool project.

But is it possible to use it only as an API? I just want to make my own GUI.
Also, it would be great to be able to log in under different users from unix. So that --root stands for everyone as env.HOME.

**Comment by coderaiser** [comment]
Thank you! Yes you can use only `api`, most documented in [restafary](https://github.com/coderaiser/node-restafary) for authentication used `Basic Auth`.

`CLOUDCMD_ROOT` read from `env`, but it is read after start and I’m not sure you can change it later, but you can use `Cloud Commander` as [middleware](http://cloudcmd.io/#using-as-middleware) and add support for it.
