### ISSUE TITLE
Can't delete files

### ISSUE THREAD

**Issue by ShardanaSoft** [coderaiser/cloudcmd#355]
Hi and first of all , thanks for this amazing file manager. 

I'm not able to delete file or folders. I have not error in console,

I'm struggling with it. I'm using the very same code that use cloudcmd as middleware.

versions are:
    "cloudcmd": "^15.9.8",
    "express": "^4.17.1",
    "socket.io": "^4.2.0"

A prompt appear saying: 

         Cloud commander 
         ENOENT: "my file path"
          Continue?
```js
import http from 'http';
import cloudcmd from 'cloudcmd';
import {Server} from 'socket.io';
import express from 'express';

const app = express();

const port = 1337;
const prefix = '/';

const server = http.createServer(app);
const socket = new Server(server, {
    path: `${prefix}socket.io`,
});

const config = {
    name: 'cloudcmd :)',
};

const filePicker = {
    data: {
        FilePicker: {
            key: 'key',
        },
    },
};

// override option from json/modules.json
const modules = {
    filePicker,
};

const {
    createConfigManager,
    configPath,
} = cloudcmd;

const configManager = createConfigManager({
    configPath,
});

app.use(prefix, cloudcmd({
    socket, // used by Config, Edit (optional) and Console (required)
    config, // config data (optional)
    modules, // optional
    configManager, // optional
}));

server.listen(port);
```

**Comment by coderaiser** [comment]
Hi, could you please tell me did you change `~/.cloudcmd.json`? If you run `Cloud Commander` with `npx cloudcmd` you can delete files?

**Comment by ShardanaSoft** [comment]
I haven't neither created .cloudcmd.json, can this be the problem?

 I've run 
npx cloudcmd , and I can't delete
npx cloudcmd --root d: I've tested this too, (maybe it's admin privilege problem). Still nothing, it doesn't delete files.

I've tryied to install it globally. still nothing.

Node version: v14.15.0

I've tryied using console from web server, and I'm able to delete the files.

Using like middleware, I've saw the console log for every action I take (view, rename, .... ) and also network log.

When deleting nothing appear, neither errors. just the loading that keep going and never end.

I'll try uploading in heroku tomorrow. There are other tests I can do?

**Comment by coderaiser** [comment]
Could you please tell me what `OS` are you using? You can also try to use [fileop](https://github.com/cloudcmd/node-fileop) directly.

**Comment by ShardanaSoft** [comment]
I'm using win 10 home. 
I've tested it in ubuntu, same node version, 

> Node version: v14.15.0

and it work just fine. Asap I'll try fileop and upload in heroku

**Comment by ShardanaSoft** [comment]
it's perfect. I'm using on windows just for testing locally, but I m not planning to use it here in production. Do you want me to rename the issue or close it?

**Comment by coderaiser** [comment]
I have no ability to test `Cloud Commander` on `windows`, so if you have no idea why it’s didn’t work and don’t want to fix it, you can close 🤷

**Comment by ShardanaSoft** [comment]
I'll take a look in the week end, hope I can help 💪

**Comment by ShardanaSoft** [comment]
I'm not able to look up the error. sorry. Have no idea how it works. I'm not good enough. 
You can remove the middleware label, it's just window related issue.

Issue still here? want me to close it or leave?

**Comment by coderaiser** [comment]
Closed due to inability to reproduce 🤷‍♂️.

**Comment by ShardanaSoft** [comment]
Ok I think I got it.

 [redzip](https://github.com/coderaiser/redzip/blob/master/lib/local/index.js)

in this lib  try to remove a directory using fs module. (rmdir)

rmdir doesn't throw error with code ENOTDIR in windows (ENOENT)

So the test fails and it's not able to continue.

this test is not suitable for windows and this looks like a wontfix [issue](https://github.com/nodejs/node/issues/18014)

Opened a issue in [redzip](https://github.com/coderaiser/readzip/issues/1)
