### ISSUE TITLE
Authorization does not work

### ISSUE THREAD

**Issue by LumbermanSVO** [coderaiser/cloudcmd#356]
* **Version** (`cloudcmd -v`): 15.9.8 
* **Node Version** `node -v`: 16.13.0
* **OS** (`uname -a` on Linux): Linux CloudCommander 5.11.7-1-pve #1 SMP PVE 5.11.7-1~bpo10 (Thu, 18 Mar 2021 16:17:24 +0100) x86_64 GNU/Linux
* **Browser name/version**: Safari Version 15.0 (16612.1.29.41.4, 16612) on MacOS 11.6.1 (20G224)
* **Used Command Line Parameters**: 
* **Changed Config**: "auth": false,

Changing auth to true does force a login screen, but even with credentials that match the config file, I can NOT actually login.

**Comment by coderaiser** [comment]
I don’t quite understand what version of Cloud Commander are you using `v15.9.8` or `v5.11.7`. `v5.11.7` not supported, consider updating to latest version.

You mentioned that you changed `auth` to `false`, but it is disabled by default.

**Comment by coderaiser** [comment]
Closed due to lack of information.
