### ISSUE TITLE
Move and copy not working with latest Docker image

### ISSUE THREAD

**Issue by mhbates** [coderaiser/cloudcmd#358]
- **Version**: Latest Docker image released around 2021-11-21 or 2021-11-22, I'm assuming that's v15.9.9

The move and copy functions don't do anything. Rolling back to the 15.9.8 image fixes it.

**Comment by coderaiser** [comment]
Do you have any errors in the console of your browser?

**Comment by mhbates** [comment]
> Do you have any errors in the console of your browser?

Looks like just this:

![image](https://user-images.githubusercontent.com/18390027/144668815-1ba44fdd-1303-438b-b2e7-629363dc0ffe.png)

**Comment by frepke** [comment]
> - **Version**: Latest Docker image released around 2021-11-21 or 2021-11-22, I'm assuming that's v15.9.9
> 
> 
> 
> The move and copy functions don't do anything. Rolling back to the 15.9.8 image fixes it.

+1

**Comment by coderaiser** [comment]
Landed in [v15.9.10](https://github.com/coderaiser/cloudcmd/releases/tag/v15.9.10) 🎉 . Is it works for you?

**Comment by frepke** [comment]
I can confirm it's working for me, thanks.
