### ISSUE TITLE
Proxy to nginx is not working

### ISSUE THREAD

**Issue by satriyowibowo** [coderaiser/cloudcmd#36]
after creating nginx hostfile
this error appears on my browser

ENOENT, lstat '/usr/lib/node_modules/cloudcmd/manager'

and i can't find .cloudcmd.json file

**Comment by coderaiser** [comment]
What is `manager`? `Cloud Commander` have no dependencies with such name.
`.cloudcmd.json` is located in the [HOME](https://github.com/coderaiser/coderaiser.github.io/issues/3#issuecomment-105767990) directory.
Could you show me your hostfile?
What version of `Cloud Commander` are you use?

**Comment by satriyowibowo** [comment]
i don't know
just proxy cloudcmd with nginx
here is my nginx site block
i'm using easyengine btw
```
server {
    server_name fileman.mydomain.cctld

    access_log /var/log/nginx/fileman.mydomain.cctld.access.log rt_cache;
    error_log /var/log/nginx/fileman.mydomain.cctld.error.log;

    add_header X-Proxy-Cache $upstream_cache_status;
    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_redirect      off;
        proxy_set_header    Host            $host;
        proxy_set_header    X-Real-IP       $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```
nope
there is no .cloudcmd.json in my home folder
i'm using root as user
here is inside my home folder

```
root@hostname:~# echo $HOME
/root
root@hostname:~# cd /root
root@hostname:~# ls -alh
total 9.7M
drwx------   8 root root 4.0K May 27 22:42 .
drwxr-xr-x  21 root root 4.0K May 27 23:31 ..
-rw-r--r--   1 root root 9.3K Jun  2 04:52 .bash_history
-rw-r--r--   1 root root 3.1K Feb 19  2014 .bashrc
drwx------   2 root root 4.0K Apr 17  2014 .cache
drwx------   3 root root 4.0K May 25 23:22 .config
drwxr-xr-x   3 root root 4.0K May 25 09:35 dist
-rw-r--r--   1 root root  16K May 25 23:23 ee
-rw-r--r--   1 root root 9.6M Mar 17 01:26 Geekbench-3.3.2-Linux.tar.gz
-rw-r--r--   1 root root   57 May 25 23:25 .gitconfig
-rw-------   1 root root   11 Jun  2 08:22 .nano_history
drwxr-xr-x 496 root root  36K Jun  1 23:14 .npm
drwxr-xr-x   4 root root 4.0K May 27 23:53 .pm2
-rw-r--r--   1 root root  140 Feb 19  2014 .profile
-rw-------   1 root root 1.0K May 25 23:28 .rnd
-rw-r--r--   1 root root   66 May 26 01:40 .selected_editor
drwx------   2 root root 4.0K May 25 23:36 .ssh
```

i'm using version v3.0.2
```
root@hostname:~# cloudcmd -v
v3.0.2
root@hostname:~#
```
thanks

**Comment by coderaiser** [comment]
What is going on when you just start `Cloud Commander`. Is it works good?
Could you just start it, and open browser with url `http://127.0.0.1:8000` or `http://fileman.mydomain.cctld:8000`? 

Host file looks good, you could look at [this working example](https://github.com/coderaiser/nginx/blob/b3618dad8bad58aedffc7bef3d403aed91ba58d7/sites-available/tarzak.cloudcmd.io) that I'm use.

`.cloudcmd.json` would be saved in home directory in case you change something in options. If you use all default options it wouldn't be created.

**Comment by satriyowibowo** [comment]
problem solved
remove the cloudcmd and then reinstall it

is it possible to run cloudcmd using pm2 ?

**Comment by coderaiser** [comment]
I use `forever` for this purpose. But I think that should be no problem with `pm2`.
All you need to do is set path of Cloud Commander's file `bin/cloudcmd.js`.

If it located in `/usr/lib/node_modules/cloudcmd` all you need to do is execute next command:
```js
pm2 start /usr/lib/node_modules/cloudcmd/bin/cloudcmd.js
```
And that is it.

**Comment by satriyowibowo** [comment]
wow, it works great
thanks a lot :)

**Comment by coderaiser** [comment]
Always welcome :).
