### ISSUE TITLE
Cannot Build Docker - Latest Version

### ISSUE THREAD

**Issue by hernandito** [coderaiser/cloudcmd#367]
- **Version** (`cloudcmd -v`):
- **Node Version** `node -v`:
- **OS** (`uname -a` on Linux):
- **Browser name/version**:
- **Used Command Line Parameters**:
- **Changed Config**:

Hi,

I cloning Cloudcmd in order to make the css edits, per issue [https://github.com/coderaiser/cloudcmd/discussions/361](url).

I am trying to build a new Docker Hub repo with my edits but I am having problems. I have tried both the standard Dockerfile and the Dockerfile-alpine.

**FIRST ATTEMPT:**
In my terminal, I cd to the "docker" folder and I run:
 `docker build --no-cache -t cloudcommander .`

I get the below error message:
`failed to compute cache key: "/package.json" not found: not found`

So I copied package.json to to the "docker" folder and ran docker build again. I get a bunch of npm deprecated warnings; and the build completes without errors.

I then go to terminal and I type:
`docker run -dp 8000 cloudcommander`
I get the below error:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/src/app/bin/cloudcmd.mjs": stat /usr/src/app/bin/cloudcmd.mjs: no such file or directory: unknown.`

No luck so I try the Second Attempt

**SECOND ATTEMPT:**
I copy the Dockerfile to the root of the repo. I then cd to the **root** of the repo and run the docker build command.

The build finishes without errors. Then I run:
`docker run -dp 8000 cloudcommander`

The container then appears in Docker Desktop, but turned off. When I click on the docker it shows this as the error:
`/usr/bin/env: 'node\r': No such file or directory`

**THIRD ATTEMPT**
Next I renamed the `Dockerfile.alpine` to `Dockerfile` and copied to the root of the repo. I ran the `docker build `and `docker run ` without errors. On Docker Desktop I get the same error above.

I tried the same with the Alpine Dockerfile in the /docker folder and when going to Docker Desktop, I get this error message:
`Error invoking remote method 'docker-start-container': Error: (HTTP code 400) unexpected - OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/src/app/bin/cloudcmd.mjs": stat /usr/src/app/bin/cloudcmd.mjs: no such file or directory: unknown`

I am not sure what I am doing wrong to build the docker. 

Any advise?

Thank you.

H.

**Comment by coderaiser** [comment]
@timoknapp could you please help with this :)?

**Comment by timoknapp** [comment]
Hi @hernandito ,

Before building the Docker images, you have to build the project beforehand. In order to do this you need to execute the following commands:

```
# Install NPM packages
npm i redrun -g
npm install

# Build the artifact
redrun build

# Do ONE of the following:

# 1. Build the Docker images for multiple CPU Architecture
docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 --file docker/Dockerfile .
# This build an alpine based image
docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 --file docker/Dockerfile.alpine .

2. Build the Docker image only for the local environment
docker build --file docker/Dockerfile .
# This build an alpine based image
docker build --file docker/Dockerfile.alpine .
```

I hope this helps you out.

**Comment by hernandito** [comment]
Thank you timknapp!

i will give this a go.

**Comment by hernandito** [comment]
Hi,

When runing `npm install` I ran into two errors:

```

  gyp ERR! configure error
  gyp ERR! stack Error: EACCES: permission denied, mkdir '/mnt/unraidcache/cloudcommander/node_modules/node-pty/build'
  gyp ERR! System Linux 5.4.0-94-generic
  gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
  gyp ERR! cwd /mnt/unraidcache/cloudcommander/node_modules/node-pty
  gyp ERR! node -v v10.19.0
  gyp ERR! node-gyp -v v6.1.0
  gyp ERR! not ok
  npm WARN notsup Unsupported engine for gritty@6.1.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
  npm WARN notsup Not compatible with your version of node/npm: gritty@6.1.0
  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
  npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
  npm WARN postcss-modules-resolve-imports@1.3.0 requires a peer of postcss@^6.0.0 but none is installed. You must install peer dependencies yourself.
  
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! node-pty@0.10.1 install: `node scripts/install.js`
  npm ERR! Exit status 1
  npm ERR!
  npm ERR! Failed at the node-pty@0.10.1 install script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /root/.npm/_logs/2022-01-18T13_16_41_856Z-debug.log
```


This sounds like a permissions issue; but I ran this as sudo. I am using Ubuntu Server on a VM in my unRAID system. I also tried to solve it by manually creating the folders, but during the process, they get erased and it then tries to create again. In the unRAID CLI, I also ran a `chmod -R 777` to the repo folder.

The second error, I suspect it's caused because of the previous error.: 

```
    npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! node-pty@0.10.1 install: `node scripts/install.js`
  npm ERR! Exit status 1
  npm ERR!
  npm ERR! Failed at the node-pty@0.10.1 install script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /root/.npm/_logs/2022-01-18T13_16_41_856Z-debug.log
```


Any advice please?

Thank you.

**Comment by coderaiser** [comment]
@hernandito update version of node.js to `v12`, or `v14`, and better `v16`, `v10` is too old :).

**Comment by timoknapp** [comment]
> @coderaiser and @timoknapp this worked like a charm guys. Thank you for all the help. I will be adding some comments to a previous thread in Discussion. 
> 
> 
> 
> Thanks again.

@hernandito great that we could help you out 🙏
