### ISSUE TITLE
Button Not Properly Formatted

### ISSUE THREAD

**Issue by hernandito** [coderaiser/cloudcmd#368]
- **Version** (`cloudcmd -v`):
- **Node Version** `node -v`:
- **OS** (`uname -a` on Linux):
- **Browser name/version**:
- **Used Command Line Parameters**:
- **Changed Config**:

Hi Guys... small issue.

The formatting of the F7 button is not correct. It is missing the icon and the font does not match the other buttons.

![image](https://user-images.githubusercontent.com/787317/150356395-140452ca-9702-414a-9cbb-986cce21d7a7.png)

Thank you.

**Comment by coderaiser** [comment]
Thanks a lot :)! Landed in [v15.9.15](https://github.com/coderaiser/cloudcmd/releases/tag/v15.9.15) 🎉 .
Is it works for you?

**Comment by hernandito** [comment]
Terrific. Works perfect. Thank you!
