### ISSUE TITLE
Is there anyway to restore a deleted folder? 

### ISSUE THREAD

**Issue by ahmedelakkad** [coderaiser/cloudcmd#370]
- **OS**: OMV6 over Raspbian
- **Browser name/version**: Brave/Chrome

Is there any way I can restore a deleted by mistake folder?

Thanks!

**Comment by coderaiser** [comment]
`Cloud Commander` doesn’t provide recovery functions, when you remove a directory it works like `rm -rf`.

But you can use something like [foremost](https://www.section.io/engineering-education/recover-deleted-files-with-foremost/) for this purpose, as when you remove a file, only it’s name and location information removed, all content preserved. 

Until you write a new data of course, so try to avoid any manipulations with data, it will increase recovery chances.

**Comment by ahmedelakkad** [comment]
Thanks a lot! I will try it out.
