### ISSUE TITLE
online option invalid or wrong

### ISSUE THREAD

**Issue by wll8** [coderaiser/cloudcmd#374]
The default value of the online option is invalid

- **Version** (`cloudcmd -v`): v16.1.1
- **Node Version** `node -v`: v16.14.0
- **OS** (`uname -a` on Linux): `Linux *** 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- **Browser name/version**: chrome 102.0.5005.115 x64
- **Used Command Line Parameters**: cloudcmd
- **Changed Config**: no

## replay
Open the network console, click console in the web interface and view the network tab

![image](https://user-images.githubusercontent.com/28223260/173998733-5ce3fd36-d9a3-4e3d-95d1-0db324e7b175.png)

According to the docs, the default is not to load js from the cdn, 

``` txt
    "online"                : false,    // do not load js files from cdn
```

but `cloudcmd -o=false` is required for this to work.

## other
- [urls.css](https://github.com/coderaiser/cloudcmd/blob/8c59333a020aab6e8fa5496ab9760ae7c3fa698e/css/urls.css)

![image](https://user-images.githubusercontent.com/28223260/173999600-e5195cc8-a948-40ca-b27d-697ea12a7de8.png)

Can they be used without internet?

**Comment by coderaiser** [comment]
I can't reproduce this, when you use `--no-online`, here is what you should see, and this default behavior: 

![image](https://user-images.githubusercontent.com/1573141/174009868-c92c4f58-ce89-4f45-94c4-d01dbdc759c7.png)

> cloudcmd -o=false 

There is no such an option, `--online`, and `--no-online`.

About styles, as you see there is a bunch of urls with locals as well, so when there is no internet, local used.

> Can they be used without internet?

Yes! But why do you need it?
