### ISSUE TITLE
fix(restafary) onFS: Windows system access file error

### ISSUE THREAD

**Issue by wll8** [coderaiser/cloudcmd#378]
See: https://github.com/coderaiser/node-restafary/pull/2

![image](https://user-images.githubusercontent.com/28223260/174220294-3db06fa2-41d5-40fa-a4be-5e34b54208a9.png)

See: [restafary.js#L154](https://github.com/coderaiser/node-restafary/blob/a61dcd095028de1126db63c91ad9165deeb4395d/server/restafary.js#L154)

![image](https://user-images.githubusercontent.com/28223260/174220057-24e0f541-ceb0-4494-aabd-5695324b61a0.png)

- **Version** (`cloudcmd -v`): v16.1.1
- **Node Version** `node -v`: v16.14.0
- **OS** (`uname -a` on Linux): `win10x64`
- **Browser name/version**: chrome 102.0.5005.115 x64
- **Used Command Line Parameters**: cloudcmd
- **Changed Config**: no

**Comment by coderaiser** [comment]
Why do you have windows path on Linux?

**Comment by wll8** [comment]
Sorry, since I was testing on multiple systems at the time,

Caused me to forget to change the usage environment in the article.

I have now modified it.

Obviously, this problem is caused by using it on windows.

**Comment by coderaiser** [comment]
Necessary details are missing: what root was provided in config of Cloud Commander?
