### ISSUE TITLE
Limit path that is accessible

### ISSUE THREAD

**Issue by cjcdev** [coderaiser/cloudcmd#381]
Is it possible to limit the path that is accessible in cloudcmd? (ie, only to the volumes mounted?)
When running in docker, is it possible to not show the filesystem of the docker cointainer?

**Comment by coderaiser** [comment]
Use `——root` option or `CLOUDCMD_ROOT` env variable to set directory path to work with.

**Comment by cjcdev** [comment]
That worked, thank you.
