### ISSUE TITLE
Unique "ROOT" directory for each side of the 2 panel view

### ISSUE THREAD

**Issue by cjcdev** [coderaiser/cloudcmd#382]
Is it possible in the 2 panel view to have a unique "ROOT" for the left and right side?

**Comment by coderaiser** [comment]
No, root works for both panel.

**Comment by coderaiser** [comment]
So that’s not clear how to implement copy/move when roots are different, that’s nice idea, but requires research and significant changes since right now there is only one root. @cjcdev what is your use case ?
