### ISSUE TITLE
feat: a row at the top with Bookmarks/shortcuts to different folder locations

### ISSUE THREAD

**Issue by joggs** [coderaiser/cloudcmd#387]
- **Version** (`cloudcmd -v`):
- **Node Version** `node -v`:
- **OS** (`uname -a` on Linux):
- **Browser name/version**:
- **Used Command Line Parameters**:
- **Changed Config**:

Feature request:
a row at the top with Bookmarks/shortcuts to different folder locations, so you quickly can move between important file locations on your server

**Comment by coderaiser** [comment]
Nice idea! Are you up for a PR?

**Comment by joggs** [comment]
.js is not my cup of tea unfortunately. I just love cloudcmd and want to keep you busy :)

**Comment by coderaiser** [comment]
@joggs you can use [User Menu](https://cloudcmd.io/#user-menu) for this purpose, just create file `.cloudcmd.menu.js` with content:

```js
export default {
    'R - cd /': async ({CloudCmd}) => {
        CloudCmd.loadDir({
            path: '/'
        });
    },
    'H - cd ~': async ({CloudCmd}) => {
        CloudCmd.loadDir({
            path: '/Users/coderaiser'
        });
    },
}
```

After then when you press `F2` and then `R` you will go to root, and if you press `F2` and then `H` you will change directory of your active panel to home.

You can find more recipes in [User Menu Cookbook](https://github.com/coderaiser/cloudcmd/wiki/User-Menu-Cookbook).
