### ISSUE TITLE
Docker: Could not do a head request for "coderaiser/cloudcmd:latest-alpine"

### ISSUE THREAD

**Issue by mvantoor** [coderaiser/cloudcmd#388]
Hi there,

Since the release of v16.10.0 I am getting `Could not do a head request ...` warnings in Watchtower which I use to keep my docker containers up to date. The full warning is:
```
Could not do a head request for "coderaiser/cloudcmd:latest-alpine", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present"
```
There are more of these issues reported for other docker image repositories. I seems the new manifest format part of the new version of `docker buildx` is causing this. See [this](https://github.com/containrrr/watchtower/discussions/1529) discussion were the possible [workaround/solution](https://github.com/docker/buildx/issues/1509#issuecomment-1378538197) is mentioned  

I have disabled these warnings now via a configuration flag in Watchtower but it might be good to have this fixed in the Docker Image repository as well.

Thanks.

Best,
Maarten

- **Version** (`cloudcmd -v`): v16.10.0
- **Node Version** `node -v`: n.a.
- **OS** (`uname -a` on Linux): Docker version 20.10.22 on Debian 5.10.149-2
- **Browser name/version**: n.a.
- **Used Command Line Parameters**: n.a.
- **Changed Config**: n.a.

**Comment by coderaiser** [comment]
@timoknapp could you please help with this?

**Comment by coderaiser** [comment]
> I have disabled these warnings now via a configuration flag in Watchtower but it might be good to have this fixed in the Docker Image repository as well.

@mvantoor Do you have any ideas of how to fix it?

**Comment by timoknapp** [comment]
@coderaiser, @mvantoor : I just checked the issue and the links attached. We actually dont perform any `docker manifest inspect` commands on cloudcmd side. I guess, that the underlying GitHub Action which we are using ([docker/build-push-action@v2](https://github.com/coderaiser/cloudcmd/blob/master/.github/workflows/docker.yml#L38)) could be responsible for this.

@mvantoo: Whats your current issue with this? Are you only afraid by the warning being presented or do you actually have issues with the actual Docker images being downloaded? If first applies, than I would suggest to simply disable the warning as described.

**Comment by mvantoor** [comment]
@timoknapp @coderaiser I have no issues at the moment with the Docker image itself. 

Only thing was that Watchtower was notifying me on a daily basis about the Head request failure for the container which was quite annoying. Now with the configuration flag telling Watchtower to not warn on these Head request failures everything is fine for me.

I only wanted to let you know as maybe more users experience this and a fix/workaround could be applied on the build step of the image. 

It's fine with me to close this issue
