### ISSUE TITLE
Large number of files missing or deleted by aborting in the middle of a move file process

### ISSUE THREAD

**Issue by br0nd** [coderaiser/cloudcmd#389]
I'm using Cloud Commander on Unraid docker. 
I was trying to move a large directory between two disks using the Web interface. In the middle of the move, I clicked the abort option. Only a few files had successfully moved when I clicked abort, those files were successfully copied.. but the rest of the files in the "queue" seem to have disappeared. They are no longer in either the source or the destination directory. 

I'm not sure how to gather logs, but happy to do that. I can also try to replicate the issue again and report back. 
- **Version** (`cloudcmd -v`): Cloud Commander v16.14.0
- **Node Version** `node -v`: v18.14.2
- **OS** (`uname -a` on Linux): "Linux 406c53c45bc3 5.19.17-Unraid 2 SMP PREEMPT_DYNAMIC Wed Nov 2 11:54:15 PDT 2022 x86_64 GNU/Linux"
- **Browser name/version**: Microsoft Edge 
- **Used Command Line Parameters**:
- **Changed Config**:

**Comment by frepke** [comment]
I had the same issue. Moving 60Gb of files. Aborting after 5Gb, the the 5Gb is moved and the 55Gb what was left, is gone.

**Comment by coderaiser** [comment]
Looks like it's related to [`@cloudcmd/move-files`](https://github.com/cloudcmd/move-files/blob/master/lib/move-files.js#L50-L55) and `cancel` event in [`@cloudcmd/fileop`](https://github.com/cloudcmd/node-fileop/blob/master/server/operate.js#L53).

**Comment by coderaiser** [comment]
Fixed in [`v16.14.1`](https://github.com/coderaiser/cloudcmd/releases/tag/v16.14.1). Is it works for you?

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
