### ISSUE TITLE
Right click menu not available if root directory is empty.

### ISSUE THREAD

**Issue by danshick** [coderaiser/cloudcmd#39]
If the directory defined as the root for cloudcmd is empty, right click shows plain right click menu, and none of the functionality works. This is resolved as soon as one file is available in the root directory.

Tested on 3.4.0, but release notes for 3.5.0 don't indicate any changes that would resolve this issue.

**Comment by coderaiser** [comment]
`right click shows plain right click menu, and none of the functionality works`
What kind of functionality doesn't work?

**Comment by danshick** [comment]
You just get the browser context menu, not the app context menu with upload, new, etc... functionalities. Attached a screenshot of what the site looks like if you right click when the root is empty in Firefox.

![cloudcmd_error](https://cloud.githubusercontent.com/assets/3999378/8418036/792b3f2a-1e7e-11e5-9019-44bea334d409.png)

**Comment by danshick** [comment]
If you have any files in there at all (even an empty one) you get the app context menu like expected.

![cloudcmd_okay](https://cloud.githubusercontent.com/assets/3999378/8418095/d138c200-1e7e-11e5-97a2-f287a4193c8f.png)

**Comment by coderaiser** [comment]
Thank you for screen shots, I'll think about it.

**Comment by coderaiser** [comment]
I never thought that root directory could be empty, actually it was impossible before ability to change root existed. To fix this bug a couple not simple decisions should be made.
Anyway this bug definetly should be fixed. With this commit https://github.com/coderaiser/cloudcmd/commit/161a363b0439a05c82332e9aa3b92c7c9e4ca23b, as workaround Config window could be opened and root could be changed to folder one level up. I'll try to make things work in right direction. Any ideas are welcome.

**Comment by coderaiser** [comment]
Fixed in https://github.com/coderaiser/cloudcmd/commit/cbcda32df261849d932db1e8ff9e0f2dfa72f4bb.

**Comment by coderaiser** [comment]
Landed in [v3.6.0](https://github.com/coderaiser/cloudcmd/releases/tag/v3.6.0).
