### ISSUE TITLE
Copy recursive preserving permissions

### ISSUE THREAD

**Issue by rodrigohess** [coderaiser/cloudcmd#398]
Hello, how can I copy a folder preserving atributes like doing cp -pr in terminal? When I copy a file or folder it changes the file attributes

Thanks a lot
Rodrigo

**Comment by coderaiser** [comment]
There is now such a feature, but that's a good idea for a PR https://github.com/coderaiser/redzip/blob/master/lib/local/index.js#L35-L57

**Comment by coderaiser** [comment]
It should work for local files (no zip) https://github.com/coderaiser/redzip/blob/master/lib/local/index.js#L50-L52

**Comment by rodrigohess** [comment]
thanks how can I implement that?

**Comment by coderaiser** [comment]
As I see it should just work, is it works for you @rodrigohess?
