### ISSUE TITLE
File upload should appear when right clicking empty area in a directory

### ISSUE THREAD

**Issue by danshick** [coderaiser/cloudcmd#40]
The option to upload a new file is only available if you right click on an existing file. This option should be available when right clicking in empty space for a directory as well.

Tested in 3.4.0 but nothing in 3.5.0 release notes indicates a fix.

**Comment by coderaiser** [comment]
Sounds logical, I'll think about it, thank you.

**Comment by coderaiser** [comment]
Add in https://github.com/coderaiser/cloudcmd/commit/05f25e994e264e68630bf1f47793aa384e3e564c.

**Comment by coderaiser** [comment]
Landed in [v3.6.0](https://github.com/coderaiser/cloudcmd/releases/tag/v3.6.0).
