### ISSUE TITLE
Files get deleted on aborting move

### ISSUE THREAD

**Issue by DunklerPhoenix** [coderaiser/cloudcmd#400]
- **Version** (`cloudcmd -v`): 17.0
- **Node Version** `node -v`:
- **OS** (`uname -a` on Linux): debian docker
- **Browser name/version**: chrome
- **Used Command Line Parameters**:
- **Changed Config**:

Heho
I have a source folder with a subfolder that contains 12 files with a total size of about 10GB.
If I move this folder to an rclone mount which cache dir is on another drive and abort the proccess then the folder + subfolder + files in source get removed.

Is this behavior set via config or is this a bug?

**Comment by coderaiser** [comment]
There was such an error in #389, but it was fixed, is this also reproduced when you have much more files? How many percent you abort on? If it `99%` - it is expected behavior because this is move: file removed after copy.

**Comment by DunklerPhoenix** [comment]
Yes I saw this issue.
I didn't try it with many files yet, but with the constelation above it happens between 3% and 30% progress

Had this problem 3 times until now

**Comment by coderaiser** [comment]
You can add test here https://github.com/cloudcmd/move-files, better to keep files size minimal (couple kb).

**Comment by DunklerPhoenix** [comment]
Sry didn't understand what you meant with that ^^'

Should I run this code?
Or should I add a test case in that repo (don't know how)?

I'm confused rn

**Comment by coderaiser** [comment]
Could you reproduce the same with lots of small files? around 100.

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
