### ISSUE TITLE
No such image: coderaiser/cloudcmd:latest

### ISSUE THREAD

**Issue by rodrigohess** [coderaiser/cloudcmd#404]
Hello I am receiveing the message "No such image: coderaiser/cloudcmd:latest" after rebooting my server

![Captura](https://github.com/coderaiser/cloudcmd/assets/55641542/b4aac13e-bbb3-4314-927e-13aeb4059029)

Nothing has changed in my setup

version: "3.8"
services:
  cloudcmd:
    image: coderaiser/cloudcmd
    volumes:
      - /:/mnt/fs   
    environment:
      - PUID=1000 # The UID to run emby as (default: 2)
      - PGID=100 # The GID to run emby as (default 2)
      - CLOUDCMD_USERNAME=****
      - CLOUDCMD_PASSWORD=****
      - CLOUDCMD_AUTH=****
    ports:
      - 8008:8000
    restart: always

Please advice

thanks

**Comment by coderaiser** [comment]
That is strange https://hub.docker.com/r/coderaiser/cloudcmd/tags

**Comment by rodrigohess** [comment]
Now it worked....weird ! 

Is it possible to change the colors of cloudcmd?

Thanks

**Comment by coderaiser** [comment]
Yes, here is examples https://github.com/cloudcmd/theme
