### ISSUE TITLE
[feature request] disable specified items of context menu

### ISSUE THREAD

**Issue by uqix** [coderaiser/cloudcmd#405]
- **Used Command Line Parameters**:

` --no-console --no-contact --no-config-dialog`

**Comment by coderaiser** [comment]
Could you please add more description and maybe screenshots

**Comment by uqix** [comment]
Sorry for late replay.

Since we mount the volume at root `fs` as __readonly__, some menu items needs to be hidden like `Rename` `Delete` `Pack` `Extract` `Cut` `Copy` `Paster` `Upload` `New`.

<img width="658" alt="image" src="https://github.com/coderaiser/cloudcmd/assets/10142314/e58f058e-f8c5-4c5c-a08f-986b525b8048">

**Comment by coderaiser** [comment]
Are you up to implement this feature or make a donation?

**Comment by coderaiser** [comment]
What should be done is:
- hide buttons;
- hide menu items;
- disable key bindings;
- disable ability to copy on the backend side (`fileop` middleware);
- add command line option `—-readonly`;
- update `help.json` and `HELP.md`;

**Comment by coderaiser** [comment]
I'm not sure it worth implementing if you have read only file system all modification errors will be handled anyways.

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
