### ISSUE TITLE
Question session/auth timeout

### ISSUE THREAD

**Issue by antoniovalenzuela** [coderaiser/cloudcmd#407]
Hello

I can't find the session/auth storage to close it within a certain time.

Can timeout be enabled?

**Comment by coderaiser** [comment]
There is no such thing as timeout, [basic auth](https://en.wikipedia.org/wiki/Basic_access_authentication) used.

**Comment by antoniovalenzuela** [comment]
@coderaiser 
Can I close the session through the Linux console?
Or if they give me the information where it is stored.
