### ISSUE TITLE
Provide alternate image registry to dockerhub

### ISSUE THREAD

**Issue by onedr0p** [coderaiser/cloudcmd#408]
Hi 👋🏼 Awesome project here...

Dockerhub has aggressive pull rate limits, it would be awesome if you could push the image to Github Container Registry (GHCR) too.

Dockerhub was one of the best years ago... GHCR is completely free for open source projects. It's also nice in that it integrates into your repo under the packages section. Take a look at my project [here](https://github.com/onedr0p/exportarr) and look at the packages on the right side.

Thanks!

- [ ] **I'm ready to donate on [Patreon](https://patreon.com/coderaiser) 🎁**
- [ ] **I'm willing to work on this issue 💪**

**Comment by coderaiser** [comment]
Are you up for a PR? I don't mind to push to both repositories

**Comment by coderaiser** [comment]
@timoknapp it is possible? how hard it can be?
