### ISSUE TITLE
Icons in the top of each pane apply to the pane with focus, not to their parent pane

### ISSUE THREAD

**Issue by danshick** [coderaiser/cloudcmd#41]
If you are viewing two panes in the same directory and you create a file in the first, and then you click the refresh button in the second (without bringing the focus to a file or folder in the second), the refresh icon in the second pane will refresh the first pane.

Tested on 3.4.0. The release notes for 3.5.0 don't indicate a fix for this issue.

**Comment by coderaiser** [comment]
Thing is, refresh depends on cursor position, but I agree with you, refresh behavior should be more meaningful.

Feel free to make pull request.

**Comment by coderaiser** [comment]
Fixed in https://github.com/coderaiser/cloudcmd/commit/e685b5739b1615b30e4bb385ca97460aea84c670.

**Comment by coderaiser** [comment]
Landed in [v3.6.0](https://github.com/coderaiser/cloudcmd/releases/tag/v3.6.0).
