### ISSUE TITLE
terminal will leave zombie processes

### ISSUE THREAD

**Issue by bingzhangdai** [coderaiser/cloudcmd#410]
- **Version** (`cloudcmd -v`): v17.4.0
- **Node Version** `node -v`: v21.7.3
- **OS** (`uname -a` on Linux): Debian
- **Browser name/version**: chrome
- **Used Command Line Parameters**:
- **Changed Config**:
- [ ] **I'm ready to donate on [Patreon](https://patreon.com/coderaiser) 🎁**
- [ ] **I'm willing to work on this issue 💪**

I am running in docker container. The host root is mounted on `/mnt/fs` and the `terminalCommand` is `chroot /mnt/fs /bin/bash`. Everytime exiting the terminal in browser, there leaves a zombie process.
````
root@nas:~# ps aux | grep bash
root     1593376  0.0  0.0   7372  2988 ?        Ss   Apr24   0:00 bash ./run svc-cron
root     1593437  0.0  0.0   7372  3016 ?        Ss   Apr24   0:00 bash ./run svc-cron
root     1973697  0.0  0.1  14840 10244 pts/1    Ss   10:58   0:00 -bash
root     2030563  0.0  0.0      0     0 ?        Z    13:10   0:00 [bash] <defunct>
root     2030795  0.0  0.0      0     0 ?        Z    13:10   0:00 [bash] <defunct>
root     2031048  0.0  0.0      0     0 ?        Z    13:10   0:00 [bash] <defunct>
root     2031275  0.0  0.0      0     0 ?        Z    13:10   0:00 [bash] <defunct>
root     2031464  0.0  0.0   8140  7584 ?        Ss+  13:12   0:00 /bin/bash
root     2031670  0.0  0.0      0     0 ?        Z    13:12   0:00 [bash] <defunct>
root     2034349  0.0  0.0   7064  1916 pts/1    S+   13:19   0:00 grep --color=auto bash
```

**Comment by coderaiser** [comment]
When you **Cloud Commander** without Docker, you see the same behaviour?

**Comment by bingzhangdai** [comment]
I haven't installed the app on the host machine yet, but I found that every command I type will invoke a zombie process. However, using the following command is okay `chroot /mnt/fs /bin/bash -c 'ssh my-host-ip'`. Maybe this issue is related to the lib this project referencing.

I will create a virtual machine to test if this also happens without docker today night.

**Comment by coderaiser** [comment]
What other programs do you run and how you quit them?

**Comment by coderaiser** [comment]
I just run `mc` and quit on Mac OS in **Cloud Commander** terminal, no zombie process found with:

```sh
ps aux | grep defunct
```
