### ISSUE TITLE
move between drives dont get followed by moving to destination.

### ISSUE THREAD

**Issue by gdelcroix** [coderaiser/cloudcmd#411]
- **Version** (`cloudcmd -v`): 17.4.0
- **Node Version** `node -v`: 20.12.2
- **OS** (`uname -a` on Linux): debian 6.1.85-1
- **Browser name/version**: Firefox 125.0.2
- **Used Command Line Parameters**: F6 between 2 volumes
- **Changed Config**:
- [ ] **I'm ready to donate on [Patreon](https://patreon.com/coderaiser) 🎁**
- [X] **I'm willing to work on this issue 💪**

moving files between sda1 (4Tb hdd) and sdb1 (4Tb hdd) in fact filled to fullness system drive (64Gb sd) ./srv/dev-disk-by-uuid-"destination drive" folder.

i'm now stuck with locked server, accessible by console (ssh) but with data stuck in between here and there, not where intended, and in fearness of data transfer loss.

**Comment by gdelcroix** [comment]
i will add that copy from sda NTFS format drive to sdb ext4 worked like a charm, i got fucked when trying to get from sdb to sda back after formating sda to ext4, so if we don't solve the what and where, i may have lost data just by moving it. may in last resort restore it by drive forensics (testdisk) if we dont mess up before.

**Comment by coderaiser** [comment]
Could you provide more information, as I understand you move files from one directory to another? What size of files? Do you have any errors?

**Comment by coderaiser** [comment]
Here is the [code](https://github.com/cloudcmd/move-files/blob/a44027be137bfd6ee17a448df36fc12cba61e2d0/lib/move-files.js#L52): when copying is done - files from source is removed, this is what move is, you suggest to add an option to disable move?

**Comment by gdelcroix** [comment]
Hello, where do i need to go to find logs if there are any ? i didn't had any error, just didn't find files where i expected them to be, had an impossibility to login in openmediavault simultaneously, then investigated and found that the system drive of 64Gb was full and then that some of the data i intended to transfer back from slave A to B were the culprit. At that moment, we have a 48Gb in "./srv/disk-" and i was trying to transfer a bunch of files for almost 1.5Tb (if i recall well).
my main goal is to avoid messing again, because i am going to testdisk drive B to restore the files i wanted to rollback to slave A after switching it from NTFS to EXT4.

**Comment by coderaiser** [comment]
Write a video of what you doing, and what the error is. There is no additional logs in **Cloud Commander**, only that it writes to stdout.

**Comment by gdelcroix** [comment]
![image](https://github.com/coderaiser/cloudcmd/assets/4097422/26f10cf6-e7cc-458b-8d85-8ddd2038b1bf)

**Comment by gdelcroix** [comment]
![image](https://github.com/coderaiser/cloudcmd/assets/4097422/0df8f3d6-0e5d-4c5e-be19-0aed03005981)

**Comment by coderaiser** [comment]
What errors you had during move?

**Comment by gdelcroix** [comment]
it may be related to the first drive being erased and not reindexed well il the container parameters, but in that case cloudcmd might have raised an error "destination unreachable" and i couldn't have had the destination displayed in the gui ?

**Comment by gdelcroix** [comment]
extracted config.v2.json, and it is related to the container parameters.

**Comment by gdelcroix** [comment]
i can't understand why the container used a "server local" copy of the real drive, instead of using the physical disk, and how container and cloudcmd worked together to get there. 

"For I was conscious that I knew practically nothing..." (Plato, Apology 22d)

**Comment by coderaiser** [comment]
Looks like it is related to containers you using, **Cloud Commander** is node.js based, it knows nothing about any containers.
