### ISSUE TITLE
Terminal_path is not woking properly. (Docker)

### ISSUE THREAD

**Issue by zilion2000** [coderaiser/cloudcmd#415]
In docker container when i try to modify CLOUDCMD_TERMINAL_PATH env variable I got info that cloudcmd can't find a module with name of a path that I specify.

Example:
In docker compose:

```
environment:  
- CLOUDCMD_TERMINAL=true
- CLOUDCMD_TERMINAL_PATH=/
```

In container logs:

`mc  | cloudcmd --terminal: Cannot find module '/'`

**Comment by coderaiser** [comment]
`TERMINAL_PATH` is path of [Terminal](https://cloudcmd.io/#terminal) module, most likely you don’t want to override it.
