### ISSUE TITLE
logout working in microsoft edge, but not in firefox

### ISSUE THREAD

**Issue by godfuture** [coderaiser/cloudcmd#416]
- **Version** (`cloudcmd -v`): 17.4.0
- **Node Version** `node -v`: 20.12.2
- **OS** (`uname -a` on Linux): docker container (f9695130498b605c10d76db425e5f4eb07ddb22fe242024e495475c6c71d8fe2)
- **Browser name/version**: Firefox 128.0.2
- **Used Command Line Parameters**: -
- **Changed Config**: -
- [ ] **I'm ready to donate on [Patreon](https://patreon.com/coderaiser) 🎁**
- [ ] **I'm willing to work on this issue 💪**

Clicking on "logout" does work on Microsoft Edge, but when doing the same thing with firefox, no logout happens, but simply a refresh of website.

**Comment by coderaiser** [comment]
There is a bug in firefox https://bugzilla.mozilla.org/show_bug.cgi?id=260839, You better write there

**Comment by antoniovalenzuela** [comment]
It's not the best idea...I edited it directly 

/usr/local/lib/node_modules/cloudcmd/dist/cloudcmd.js

And replace:
this -> document.location.reload() 
for -> window.location.replace("https://logout@"+location.host+"/cloudcmd")       _//My custom Nginx Proxy Pass URL_

`this.logOut=async()=>{const t=n.prefix+"/logout",{prefix:r}=n;await e.Storage.clear(),p(r),e.load.ajax({url:t,error:()=>window.location.replace("https://logout@"+location.host+"/cloudcmd")})`

Log Out
![imagen](https://github.com/user-attachments/assets/6c64bc3b-d636-425e-89d4-0082db760f63)

Logoff, prompt login
![imagen](https://github.com/user-attachments/assets/7c4ba346-100e-4c28-9492-42d36e1ae83d)

**Comment by coderaiser** [comment]
I tried that, it caches requests and shows a couple logins at once, so it doesn’t looks like clean solution.

**Comment by coderaiser** [comment]
Anyways you can add this lines to [User Menu](https://cloudcmd.io/) and you will have a custom logout feature for FireFox.

**Comment by antoniovalenzuela** [comment]
I don't have that problem. After the change, I checked the operation also in Chrome, Edge, because it could affect, but no, all browsers log out, and then I log in again without problems.

They could look for a definitive solution, compatible with all browsers.

**Comment by antoniovalenzuela** [comment]
> I tried that, it caches requests and shows a couple logins at once, so it doesn’t looks like clean solution.

Now I understand, the loop occurs in the same tab.
