### ISSUE TITLE
Multi select files

### ISSUE THREAD

**Issue by hagaygo** [coderaiser/cloudcmd#418]
Hi

Maybe i missing it, but is there an option to multi select files on "mobile" interface ?

There is only the context menu option (un)select all.

On a PC i can use the CTRL key to toggle multiple file selection , how can it be done on smartphone ?

Thanks

**Comment by coderaiser** [comment]
There is no such an option. How it can be done?

**Comment by hagaygo** [comment]
Well , there is no "one way" to do so.

Currently it is possible using CTRL key and click which is not possible on normal smartphone.

I can see 3 options :

1. "long press" , which can be implemented on a web interface in several ways (for example https://stackoverflow.com/questions/6596432/continuous-mouse-click-event) which will trigger select/deselect action (I think this is the most intuitive way)

2. Show an extra icon for selection/deselection for each file. (uses more screen/view space)

3. The easiest way (but not for the user) to implement (since you already have the code infrastructure) is to add two options to the context menu , select + unselect for the selected file. (next to existing (un)select all option).

**Comment by coderaiser** [comment]
Can you implement one of this?

**Comment by hagaygo** [comment]
Maybe , did not look at the code base yet.

But if you don't have much time/need for this feature , I am quite sure option 3 should be really easy/fast for a novice in the codebase.

**Comment by hagaygo** [comment]
I'll will also try to implement "long press" selection (option 1) when i'll find the time.

**Comment by hagaygo** [comment]
Should be reasonably possible after  https://github.com/coderaiser/cloudcmd/pull/422 got merged.
