### ISSUE TITLE
Can't log into to Cloud Commander

### ISSUE THREAD

**Issue by dbrewood** [coderaiser/cloudcmd#425]
Hi guys I'm a new user to Cloud Commander. It's installed on my Synology NAS and seemed to be working well.
It was installed into Portainer using this guide: https://mariushosting.com/how-to-install-cloud-commander-on-your-synology-nas/

I wanted to edit the \etc\hosts file and I had thought I'd done it correctly. However on a reboot the changes I'd made were overwritten when the NAS rebooted . I posted the problem on the Synology forum and they advised that I needed to be logged in as the root user to get the changes to stick.
I went into the settings and clicked on authentication (I left it as 'root' and *********** for the pssword). I now get prompted for a user and a password any time I try to use the application. The issue is that any accounts I try to log in with fail. I've tried:

'root' using the 'Admin' account password.
'admin' using the 'Admin' account password.
my 'usual admin account
And none of them work. Each time I try and access Cloud Commander I hit the log in prompts so I'm somewhat stuck.

Any assistance would be greatly appreciated.

- **Version** (`2.29.2`):
- **Node Version** `20.18.0`:
- **OS** (`macOS 15.1 (24B83` on Linux):
- **Browser name/version**: Brave Version 1.71.12
- **Used Command Line Parameters**: n/n
- **Changed Config**:
- [ No ideas yet] **I'm ready to donate on [Patreon](https://patreon.com/coderaiser) 🎁**
- [ X] **I'm willing to work on this issue 💪**

**Comment by coderaiser** [comment]
You cat set new password with:

```js
cloudcmd —-no-start -u username -p password
```

**Comment by dbrewood** [comment]
Okay silly question. Where do I run that from? Terminal on the Mac once connected to the NAS with SSH?
Once I’m back ‘in’ will that allow me to edit files in /DSM/ETC? In particular I need to edit the HOSTS file. I’m told I need root access to edit that do the changes will be retained after a reboot?

**Comment by coderaiser** [comment]
I have no idea how your NAS works, I can only help you with Cloud Commander itself, install it locally and try to use commands. Most likely you need to run it inside docker container with Cloud Commander.

**Comment by corrosive4354** [comment]
If you can access your Synology NAS via SSH, try logging in using SSH and checking Cloud Commander's log files. Log files are usually located in the Cloud Commander installation directory and may provide more information about the login failure.

In addition, seeing that you are using Docker, I would like to recommend [Servbay](servbay.com) to you, which is more professional and easy to use than Docker on Mac
