### ISSUE TITLE
Console - Interactive mode

### ISSUE THREAD

**Issue by Slind14** [coderaiser/cloudcmd#43]
Hey,

is there any way to use applications which require interactive mode with the console? In my case it is a python app using the urwid lib which doesn't support non-interactive.

**Comment by coderaiser** [comment]
Unfortunately no, [Console](https://github.com/cloudcmd/console "Console") uses [jq-consle](https://github.com/replit/jq-console "Jq-console"). You can hack around. I think this is a useful feature, but I do not know how to implement it.
Maybe you will have some ideas.

**Comment by Slind14** [comment]
hmm, I'm looking for a lightweight web file explorer and console with authentication. Where cloudcmd brightened my eyes. Unfortunately I have the limitation of needing to be able to open up service consoles, attach to a screen instances and as ultimate feature on top use tools like vim, atop.. 
I assume this isn't possible and looking for a library kinda failed. The only one I found which would go towards this direction is [GateOne](https://github.com/liftoff/GateOne). I guess its optional implementation would be a hassle, wouldn't it?
(authentication bridge + button to start in a new window or in a lightbox from cloudcmd)

**Comment by coderaiser** [comment]
Main problem with `GetOne` it is not designed for using as a node.js library or midleware, it's written on `python`, it's to large dependency for `Cloud Commander`.
[butterfly](https://github.com/paradoxxxzero/butterfly) works good, it also python based.
Any way you could use `Cloud Commander` as file manager and `GateOne` (or any other) as terminal in other tab.

**Comment by Slind14** [comment]
alright thanks. Would you recommend butterfly or tty.js on a unix system? Could I use cloud commanders auth system or should I use it as middleware and build a custom auth system?

offtopic: ever thought about pastebin, gist upload for text files?

**Comment by Slind14** [comment]
A quick research let me came up with these. I will test them and see how well they work with highly used utils, like screen, vim, htop. But if you know some of them and can say this one won't work.. This one doesn't work on windows.. you could save me a lot of testing time :) (I still hope we can find one that is worth being implanted directly into cloudcmd)

- https://github.com/Runnable/dockworker + https://github.com/chjj/term.js - demo: http://bellard.org/jslinux/
- https://github.com/Gottox/terminal.js
- https://github.com/pm2-hive/pm2-webshell - demonstrating htop on the screenshots
- https://github.com/rabchev/web-terminal

**Comment by coderaiser** [comment]
```js
offtopic: ever thought about pastebin, gist upload for text files?
```
No, I have not. But there is github gist uploader, you could try it.

I had problems `term.js` it is not maintained. But maybe now situations is better, I think you definitely should test this things.

**Comment by Slind14** [comment]
I don't think it is what you are looking for. Take a look at the last commits, they are purely pull req based since 2014 https://github.com/chjj/term.js/commits/master

**Comment by coderaiser** [comment]
`wetty` uses `pty.js` that doesn't maintained and dosn't works on windows but works pretty good on linux.
`terminal.js` works not as good (have issues with `mc`), but seems like it's totally written in JavaScript.
`webshell` uses same unsupported `tty.js` and depends on `pm2`.

**Comment by Slind14** [comment]
I see. In my opinion the possibility to use vim, screen... is already a major step forward. But I haven't used mc for a long time, still there wouldn't be many features left cloudcmd offers which mc doesn't cover :P 

About pty and windows, there is an up to date pull req: https://github.com/chjj/pty.js/pull/111
JamesMGreene also picked it up under the new name of node-partty: https://github.com/JamesMGreene/node-partty it also includes windows compatibility #8bb1493a060d37b5e370be2cf405a1366cfe485c (I hope he only is on a break an continues)

**Comment by coderaiser** [comment]
You could try install [cloudcmd v2.0.0](https://github.com/coderaiser/cloudcmd/tree/v2.0.0/) with:
```
npm i cloudcmd@2.0.0
```
Than do next things:
```
cd node_modules/cloudcmd
npm i partty
```
An change [12 line](https://github.com/coderaiser/cloudcmd/blob/v2.0.0/lib/server/terminal.js#L12)  in `lib/server/terminal.js` (I tried to use `pty.js` but had a lot problems with it so I drop it):

```js
tryRequire('pty.js') -> tryRequire('pty.js')
```

After that run:
```
node bin/cloudcmd
```

You could start terminal with `shift + ~`.

**Comment by Slind14** [comment]
thanks, I'll do that :)

**Comment by coderaiser** [comment]
Closed until proper terminal library will be found

**Comment by coderaiser** [comment]
Added support of a terminal in [v6.7.0](https://github.com/coderaiser/cloudcmd/releases/tag/v6.7.0).
