### ISSUE TITLE
Права файла

### ISSUE THREAD

**Issue by kultpro** [coderaiser/cloudcmd#45]
Хотелось бы иметь возможность выставлять права на файлы, в т.ч. масово (управлять атрибутами). Это основное. Из мелочей - было бы здорово составлять списки проигрывания аудио и видео, и что бы настройки ( в т.ч. звука) сохранялись). Сейчас проигрывается по одному ...

Благодарю за отличное приложение!

Из ошибок. не уверен что это ошибка. задумал сначала, при перебросе портов в nginx привязать не в корень домена, а в папку допустим /cmd/. Слетели все стили и скрипты, видимо пути до них так прописаны.. Я уж не смог разобраться где и что править.

**Comment by coderaiser** [comment]
По-поводу прав доступа - это хорошая идея, об этом уже говорилось в https://github.com/coderaiser/cloudcmd/issues/33, есть проблема с Windows/Unix, у которых понятие о правах разное. Сейчас с этим есть сложности, возможно в будущем что-то получится.

Список проигрывания, это немного выходит за рамки файлового менеджера, хотя может быть реализовано и подключено как middleware (как и предыдуший пункт), по-аналогии с [консолью](https://github.com/cloudcmd/console) и [редактором](https://github.com/cloudcmd/edward).

По-поводу, третьего пункта, это было в https://github.com/coderaiser/cloudcmd/issues/38, вы можете использовать [код](https://github.com/coderaiser/cloudcmd/issues/38#issuecomment-113927854), который подключает Cloud Commander как middleware, и устанавливает стартовый  `prefix` (вместо первого шага, используйте `npm i cloudcmd`, для локальной установки зависимости). Такой опции нет в конфиге, поскольку это (пока) не самый распространенный сценарий, и вступает в силу только после перезапуска файлового менеджера. Думаю, в будущем это будет проще сделать.

**Comment by kultpro** [comment]
Благодарю за ответ!
Извиняюсь что не изучил все сообщения!
Желаю успехов в развитии!

**Comment by coderaiser** [comment]
И вам спасибо :), если будут сложности с установкой префикса - пишите, постараемся решить.

**Comment by coderaiser** [comment]
[Добавлен](https://github.com/coderaiser/cloudcmd/commit/d62049cd5915681a1fe94e8901b442bf5cc645d0) параметр `prefix` в конфиг. Теперь устанавливать `prefix` можно с помощью флага `--prefix`.

**Comment by kultpro** [comment]
Ура! Благодарю!

**Comment by coderaiser** [comment]
Возможность устанавливать `--prefix` выпущена в [v4.3.0](https://github.com/coderaiser/cloudcmd/releases/tag/v4.3.0).
