### ISSUE TITLE
View of image file

### ISSUE THREAD

**Issue by geewid** [coderaiser/cloudcmd#47]
Doesn't show the image. Console log reports "Uncaught TypeError: DOM.getSelectedNames is not a function (view.js:188)". Tested on Chromium and Firefox.

**Comment by geewid** [comment]
And I think I've found a fix.

-- lib/client/view.js (line: 188)
`names   = DOM.getSelectedNames(files)` should be `names   = DOM.getSelectedFiles()`

**Comment by coderaiser** [comment]
Thank you, fixed in https://github.com/coderaiser/cloudcmd/commit/8149939d6f754a93f2b6d2a07c2fc8e93f71adc1.

**Comment by coderaiser** [comment]
Landed in [v4.3.2](https://github.com/coderaiser/cloudcmd/releases/tag/v4.3.2).
