### ISSUE TITLE
Tooltips on keyspanel start with lower letter case.

### ISSUE THREAD

**Issue by FrEeD0M** [coderaiser/cloudcmd#49]
Keyspanel tooltips that are appearing on mouseover, start with lower letter case.
Should start with upper letter case.

Steps to reproduce:
1. Hover mouse on any button in keyspanel.
2. Tooltip is displayed.

**Comment by tarzak** [comment]
I have prepared [PR](https://github.com/coderaiser/cloudcmd/pull/50) for you :)

**Comment by coderaiser** [comment]
Nice, thank you.
