### ISSUE TITLE
IE9 ignores prefix for /fs

### ISSUE THREAD

**Issue by moesingh** [coderaiser/cloudcmd#51]
also needed a proxypass for /fs since the prefix is ignored when moving directories 

e.g. 

http://domain/prefix/fs/directory

will work everywhere, but not IE9, where if you click on a directory, it will try to go to 

http://domain/fs/directory

**Comment by coderaiser** [comment]
Thanks a lot, I saw your messages at https://github.com/coderaiser/coderaiser.github.io/issues/4. I'll think about it. Colud you please provide me errors or screenshots from JavaScipt Console when you working with `Cloud Commander`?

**Comment by coderaiser** [comment]
Closed due to lack of information. Can not reproduce on latest version of browsers, try to use [one of them](http://outdatedbrowser.com/ "Outdated Browser") and update `Cloud Commander` to [v5.0.4](https://github.com/coderaiser/cloudcmd/releases/tag/v5.0.4) there was fix related to prefix.
