### ISSUE TITLE
api ignores the context root

### ISSUE THREAD

**Issue by moesingh** [coderaiser/cloudcmd#52]
hi, 

the api still ignores the context root.  

replicate:
server1:
setup cloudcmd with a context root

server2:
do a proxypass to the other server for that context root

on server 2, you cannot download since it tries to get server2/api which is not defined.  
of course, on server1, you can download, since it tries to get server1/api which is available.

**Comment by coderaiser** [comment]
Hi, is it relates to https://github.com/coderaiser/cloudcmd/issues/51?
Could you provide more details? Errors in developer tools console for example.
What browsers have you used?

**Comment by coderaiser** [comment]
Closed due to lack of information.
