### ISSUE TITLE
showing the date modified

### ISSUE THREAD

**Issue by moesingh** [coderaiser/cloudcmd#53]
hi, 

we are using this app alot, it is excellent.  

a user was asking if there is any way to show the modified date with the file list?  (e,g, rather than the owner).

**Comment by coderaiser** [comment]
It is a nice idea, thank you. I will think about it. To make it happen a couple things should be resolved. One of them it is: sizes of columns in style sheets for file attributes if their count would be more then 3. Anyway it is a good feature to implement. Feel free to share your ideas. Could you please tell me, how you use `Cloud Commander`?

**Comment by moesingh** [comment]
we use it to transfer files from server to server (site to site).  it makes it easy because a lot of our employees are not technical enough to use anything other than a webpage (e.g. filezilla, sftp, etc.) to transfer stuff. 

your program is a lot better than other php type stuff available.  very impressed!

**Comment by coderaiser** [comment]
Nice to hear, thank you for feedback. I'll think about feature you asking for. But can guarantee nothing because need a lot help with [media queries](https://github.com/coderaiser/cloudcmd/blob/1c8c387d8e3c939633910b939da1b69d5b295547/css/query.css) for all resolutions.

**Comment by coderaiser** [comment]
To implement this feature a couple things should be implemented, actually:
- modification of [readify](https://github.com/coderaiser/readify) to get modification time.
- modification of [format-io](https://github.com/coderaiser/format-io) to convert time to user friendly format
- recalculation of [size, owner, mode columns sizes](https://github.com/coderaiser/cloudcmd/blob/1c8c387d8e3c939633910b939da1b69d5b295547/css/style.css#L186)
- adding new column to [template](https://github.com/coderaiser/cloudcmd/blob/d533a4259d5f260f8c6cd7bfc5c02fad15ca4fdb/tmpl/fs/file.hbs)

Feel free to make pull request.

**Comment by coderaiser** [comment]
Okey, it could be something like this:
![image](https://cloud.githubusercontent.com/assets/1573141/13181341/56a0b6b8-d735-11e5-9fbc-f94cb0b1bbfc.png)
With help of [shortdate](https://github.com/coderaiser/shortdate) [readify](https://github.com/coderaiser/readify/blob/87306dc194be9efe5b9439caf9117b04ab235113/lib/readify.js#L125) could parse date. I'll think about it.

**Comment by coderaiser** [comment]
Added in https://github.com/coderaiser/cloudcmd/commit/d556948c87ab0e46b5a08c12bf3633f4000328c3.
Landed in [v5.1.0](https://github.com/coderaiser/cloudcmd/releases/tag/v5.1.0).
