### ISSUE TITLE
Console is not working

### ISSUE THREAD

**Issue by rafaelcastrocouto** [coderaiser/cloudcmd#54]
Seems like socket.io cannot connect to the console-io module.

Client error: GET http://localhost/cloudcmd/socket.io/?EIO=3&transport=polling&t=LAiwPQD 404 (Not Found)
Server error: GET /cloudcmd/socket.io/?EIO=3&transport=polling&t=LAiwmPU 404 0.994 ms - -

**Comment by coderaiser** [comment]
Thank you, fixed in https://github.com/coderaiser/cloudcmd/commit/8eeeb3e6c62116b3185bacf3498653f580a26b94. Landed in [v5.0.10](https://github.com/coderaiser/cloudcmd/releases/tag/v5.0.10).

**Comment by rafaelcastrocouto** [comment]
:+1:
