### ISSUE TITLE
Editor polling error when running as middleware

### ISSUE THREAD

**Issue by brianmcmichael** [coderaiser/cloudcmd#56]
App is running as express middleware with prefix `pun/dev/cloudcmd/`

The default editor is attempting to poll socket.io on the server, but it is affixing the entire app prefix, which includes the `cloudcmd` app name. The socket.io app was deployed by the installer into the same `node_modules` directory as the `cloudcmd` app, so the appropriate prefix would be `pun/dev/socket.io` in this case.

It seems that the editor needs to be informed to step back a directory from the prefix to connect to socket.io. Alternatively, cloudcmd maintains it's own node_modules folder, but `socket.io` isn't present in that path. Perhaps adding socket.io to `cloudcmd/node_modules/socket.io` would also resolve this issue. I haven't had a chance to experiment with it yet, but I'm reporting it here in case you have any thoughts.

The editor begins polling on open:
![pollingerror](https://cloud.githubusercontent.com/assets/2374718/13189573/3d501406-d726-11e5-9e31-9e34a07ecbdf.png)

Poller gets 404 from invalid path:
![pollingerror2](https://cloud.githubusercontent.com/assets/2374718/13189574/3fc220f8-d726-11e5-8bb2-fc4d2566e7e8.png)

**Comment by coderaiser** [comment]
Thank you, I think about it. Which version of `cloudcmd` you use?

**Comment by brianmcmichael** [comment]
`cloudcmd` 5.0.15
`socket.io` 1.4.5

Here's how the folders are structured on the system.

```
bmcmichael@websvcs02:~/ood_dev/cloudcmd$ ll
total 16
drwxr-xr-x 3 bmcmichael appl 4096 Feb 11 12:14 ./
drwxr-xr-x 4 bmcmichael appl 4096 Feb 16 16:19 ../
-rw-r--r-- 1 bmcmichael appl  649 Feb 16 10:11 app.js
drwxr-xr-x 6 bmcmichael appl 4096 Feb 16 12:01 node_modules/

bmcmichael@websvcs02:~/ood_dev/cloudcmd$ tree -d -L 3
.
`-- node_modules
    |-- cloudcmd
    |   |-- bin
    |   |-- css
    |   |-- font
    |   |-- html
    |   |-- img
    |   |-- json
    |   |-- lib
    |   |-- man
    |   |-- modules
    |   |-- node_modules
    |   |-- shell
    |   |-- test
    |   `-- tmpl
    |-- express
    |   |-- lib
    |   `-- node_modules
    `-- socket.io
        |-- lib
        `-- node_modules

21 directories
bmcmichael@websvcs02:~/ood_dev/cloudcmd$

```

**Comment by coderaiser** [comment]
You should add path on `socket.io` init with prefix you going to use like in [lib/server.js](https://github.com/coderaiser/cloudcmd/blob/9bf97a900ea71a08aa73818528bd9ae4f2e348bc/lib/server.js#L43).

[Added](https://github.com/coderaiser/cloudcmd/commit/54352af7283cdbdc84196902475d6c715bcf9850) this information to docs.

All this things made in this way to make prefixes work around all `Cloud Commander's` middleware.

**Comment by brianmcmichael** [comment]
Thanks, I'll try that!

**Comment by brianmcmichael** [comment]
I found the issue.

`edit.js` is using `CloudCmd.PREFIX` instead of the actual socket `path`.

https://github.com/coderaiser/cloudcmd/blob/56aef95c0f6b46c6fbcca90028ff2af37f82f8bb/lib/client/edit.js#L143

I am able to fix this by manually eding the `socketPath` var to my socket path, ex. `pun/dev/socket.io`, but I am new to express and I haven't figured out how to get the Socket's `path` variable into the `edit.js` yet.

This also appears to be an issue in `konsole.js`

https://github.com/coderaiser/cloudcmd/blob/97ada5a4e0ffd4c8f7ac237e0643771c68c6753e/lib/client/konsole.js#L53

Also, I'm not sure that the updates to the README.md regarding prefixing the path are correct. My `app.js` currently for the middleware app currently looks like:

```
socket = io.listen(server, {
  path: '/pun/dev/socket.io'
});

app.use(cloudcmd({
    socket: socket,                   /* used by Config, Edit (optional) and Console (required)   */
    config: {                         /* config data (optional)                                   */
      root: homeDir(),  
      prefix: '/pun/dev/cloudcmd',  /* base URL or function which returns base URL (optional)   */
    }
}));
```

**Comment by brianmcmichael** [comment]
Disregard. I seem to have managed to fix it in the socket path. Thanks!!!
