### ISSUE TITLE
Recent change breaks file upload.

### ISSUE THREAD

**Issue by brianmcmichael** [coderaiser/cloudcmd#62]
I'm not sure where the change occurred yet, but a recent update broke the file upload capability. (A recent change to (client.js), I think?

It appears that the prefix and API url is being added twice to the request.

![virtualbox_ubuntu 15 10 ssd_10_03_2016_11_01_04](https://cloud.githubusercontent.com/assets/2374718/13675529/0b97a372-e6b0-11e5-8bce-9099d2b7c840.png)

Downloads are not affected.

**Comment by coderaiser** [comment]
Could not reproduce uploading:
- by drag'n'drop
- via menu "upload"
- from cloud

What type of upload have you used? What version of `Cloud Commander` you use? What browser?

**Comment by brianmcmichael** [comment]
This is resolved. It looks like my browser was using a cached copy of the old .js files.
