### ISSUE TITLE
Allow for file permission control.

### ISSUE THREAD

**Issue by brianmcmichael** [coderaiser/cloudcmd#63]
It may be a good idea to include a file permission modifier using [`fs.chmod()`](https://nodejs.org/api/fs.html#fs_fs_chmod_path_mode_callback) CloudCmd already displays these permissions, but there is no way to modify them.

![2016-03-10 4](https://cloud.githubusercontent.com/assets/2374718/13677521/47cc4fb6-e6b8-11e5-952b-a265a4297457.png)

As an example, our current file manager is an old version of AjaxExplorer (now Pydio) that includes this feature as a context menu. I have included images below of how that looks.

This would actually probably be a feature that would need to be added to Restafary, with the cloudcmd client sending the request to make the modification.

Context Menu:
![permissionscontext](https://cloud.githubusercontent.com/assets/2374718/13677242/194a198a-e6b7-11e5-8fd3-f6d38c4ddd18.png)

Modify permissions:

![permissions selection](https://cloud.githubusercontent.com/assets/2374718/13677246/1bace0ea-e6b7-11e5-843f-197019721b30.png)

**Comment by coderaiser** [comment]
We have talked about it in https://github.com/coderaiser/cloudcmd/issues/33 and https://github.com/coderaiser/cloudcmd/issues/45.
It is a good idea but `Cloud Commander` works on Windows, Linux and Unix. This operation systems understands file attributes in different way. To make this feature we need:
- [x] module that gets and sets file permissions on unix (`fs.chmod` is good)
- [ ] modules that gets and sets file permissions on windows
- [ ] module that uses both of previous and adds ability to work via http and/or web sockets.
- [ ] module that uses previous, shows 2 types of UI (for windows and unix) and could work as `express midleware`.

Do you have any thoughts where to start from?

**Comment by brianmcmichael** [comment]
node's `fs.chmod()` will work on windows file systems, but it will only set to `0444` or `0666` (the readonly/writeonly bit), apparently the node developers haven't solved fine-tuning the Windows permission scheme yet. Some discussion and examples here: 
https://github.com/nodejs/node-v0.x-archive/issues/4812

I think that the same GUI could be used, but javascript can enforce readonly/writeonly if the server is running on a windows os. (Which can be detected in express with `os.platform() === 'win32'`, then add `CloudCmd.HOST_OS = os.platform()` or something )

So, if cloudcmd knows that the server is running windows, the menu might only show one row for permissions, with "r" checked and disabled, and "w" available to check, and the "x" checkbox disabled and unchecked.

Something like this for windows:

![1bace0ea-e6b7-11e5-843f-197019721b30](https://cloud.githubusercontent.com/assets/2374718/13710463/aaef1608-e787-11e5-91b9-91f48c803130.jpg)

`'win32'` is returned even on x64 windows systems by `os.process()`. So it's predictable.
```
D:\Documents\Projects\>node
> os.platform()
'win32'
```

To start, I might add the chmod to [`restfary` PATCH](https://github.com/coderaiser/node-restafary/blob/master/lib/fs/patch.js) that accepts the filepath, the chmod command, and the mode as  string (i.e. "0644", "0444", "0600", etc.). Then just call fs.chmod(filepath, mode).

**Comment by coderaiser** [comment]
I think better to create to [express middleware](http://expressjs.com/en/guide/writing-middleware.html) module that will work with mode on `windows` and `linux`. Something like [console](https://github.com/cloudcmd/console "console") [does](https://github.com/cloudcmd/console/blob/747e00e1312b2b41293afa3737c83d4dcce1d989/lib/server.js#L68) but simpler. `PATCH` in `restafary` is little bit different (but we could add it in a future anyway).
It could receive `PUT /mode/home/user/.cloudcmd.json` parameter. And convert paths to `windows` with help of [mellow](https://github.com/coderaiser/mellow). With help of [stat-mode](https://github.com/TooTallNate/stat-mode) ui could be build on a server. If you want I could create repo in [Cloud Commander group](https://github.com/cloudcmd) add you as collaborator, and we could try something with it. This module could provide ui for windows/linux and work like `config` part of `cloudcmd` which is work via http/web sockets and connected [as middleware](https://github.com/coderaiser/cloudcmd/blob/343716ce0e8518272fe6bbe48fb5364fb475c2a3/lib/cloudcmd.js#L201).

**Comment by brianmcmichael** [comment]
Yes, I can help with this. It will take some time to familiarize myself with all of the relevant code, but this is definitely a worthwhile addition.

**Comment by coderaiser** [comment]
OK, we could start from [this repo](https://github.com/cloudcmd/file-mode). You can use `npm test` to run tests, `npm run codestyle` to check code with `jshint` and `jscs`. We could use
[chmod](https://github.com/popomore/chmod) module in a future. What we should do next is:
- middleware that checks is it windows or linux and creates template that works via `http` and `websockets`. 
- client side template filled with data according to unix (3 groups of `rwx` fields) and for windows (read-only or not) (we can use [react](https://facebook.github.io/react/) or any other template engine for this purpose, but will generate everything on the server).

The only one bad side here it is: [file attributes](https://en.wikipedia.org/wiki/File_attribute) on `windows` and `unix` has different meaning as well as `file permissions` with is controlled by [cacls](https://en.wikipedia.org/wiki/Cacls) on `windows`. What way you think would be better:
- to use same name for cross platform tool but different meaning (file mode for `unix`, read-only flag for `windows`).
- use one name for same mining (file mode for unix, and [acl](https://en.wikipedia.org/wiki/Access_control_list) for windows)

As for me, I think that better to use same meaning for same functions. In this case we could start from unifying `chmod`, and than work on middle ware.
Actually we can start from any side, in any case no body have done none of this so benefit would be in both variants.

**Comment by coderaiser** [comment]
Closed until some activity begins in [file-mode](https://github.com/cloudcmd/file-mode) repo.
