### ISSUE TITLE
Command line args to disable config dialog and console

### ISSUE THREAD

**Issue by jojow** [coderaiser/cloudcmd#65]
Hi,

The Cloud Commander provides this config dialog (e.g. by pressing F10) to change some parameters.
Wouldn't it be great to have a command-line argument available to disable this config dialog? For example:

`cloudcmd --no-config-dialog`

This is because some of the config options are not meant to be changed by a user such as the port or the root directory, or even the auth credentials. Same is true for the console dialog, which also provides too much access for some use cases. So another option would be nice:

`cloudcmd --no-console`

Johannes

**Comment by coderaiser** [comment]
Hi @jojow,

I'll think about it, this can have sense, can you tell me please how are you use `Cloud Commander`?

**Comment by jojow** [comment]
I'm currently using Cloud Commander in a research project, dealing the complex simulation workflows in the field of e-science. More specifically, I'm working on a concrete use case, which requires to manage input and output files for a particular workflow.
Therefore, Cloud Commander is a great fit to manage the input/output files, by uploading/downloading files or transferring files from existing cloud storage.
However, it would be extremely helpful to strictly limit access of a Cloud Commander instance a particular directory, e.g. the user's home directory, so it's not possible for the user to access other files on the system. This is already possible by setting the "--root" argument, for example. However, the problem is that you can change the root directory at runtime through the config dialog. Thus, it would make a lot of sense for this use case to disable the config dialog completely, so the user does not have any chance to change the settings at runtime.
Same is true for the console, through which you have access to the entire filesystem.

I'm pretty sure that this would be helpful for other usage scenarios, too. This would also help to safely run several instances of Cloud Commander on the same host, each with its very own root directory.

**Comment by coderaiser** [comment]
There is a couple things we should do to implementing this feature (I'll better write it down to not forget):
- add command line option to [bin/cloudcmd.js](https://github.com/coderaiser/cloudcmd/blob/v5.3.1/bin/cloudcmd.js#27)
- add config check in middle ware [lib/cloudcmd.js](https://github.com/coderaiser/cloudcmd/blob/v5.3.1/lib/cloudcmd.js#L105)
- conditional show buttons in [index.html](https://github.com/coderaiser/cloudcmd/blob/v5.3.1/html/index.html#L30) and [lib/server/route.js](https://github.com/coderaiser/cloudcmd/blob/v5.3.1/lib/server/route.js#L69).

I do not know how better implement 3-rd step. Feel free to share ideas.

**Comment by coderaiser** [comment]
Closed due to absence of ideas and time. I'll come back to this when ideas will come.

**Comment by vostok4** [comment]
This would be ideal for instances where you want to expose a directory on the webserver to multiple users without giving them inherent trust to browse your entire filesystem or change settings that will break things (port/auth/etc).

Cloud Commander is fantastic but seems that it's geared at a single, trusted, user scenario, when in reality we'd probably just use SSH for that as the sysadmins.

If this can ever be added it would be great!

**Comment by coderaiser** [comment]
Added ability to hide `config` via `--no-config-dialog` option with ac9a6ad.

**Comment by coderaiser** [comment]
Ability to hide `config` landed in [v5.8.0](https://github.com/coderaiser/cloudcmd/releases/tag/v5.8.0).

**Comment by coderaiser** [comment]
Added ability to disable `console` with help of `--no-console` with c3c008ff.

**Comment by coderaiser** [comment]
`--no-console` landed in [v5.9.0](https://github.com/coderaiser/cloudcmd/releases/tag/v5.9.0).
