### ISSUE TITLE
Не работает c electron.atom.io

### ISSUE THREAD

**Issue by MrFranke** [coderaiser/cloudcmd#66]
При попытке запустить в окружении electron.atom.io получаем ошибку `Uncaught Error: Cannot find module 'execon'  module.js:341`

**Comment by coderaiser** [comment]
Скорее всего дело в поле `node-integration` конструктора [BrowserWindow](https://github.com/electron/electron/blob/master/docs/api/browser-window.md "BrowserWindow").
[lib/util.js](https://github.com/coderaiser/cloudcmd/blob/8066cab4514c66b7e522b41b41266d6c880d5390/lib/util.js#L8) использует глобальные переменные, только если нет `module.exports`
[Вот]( https://github.com/cloudcmd/atom/blob/76d12b6841f0ff9a9ee72a3811c15c8bd453c9dc/main.js#L35) пример Cloud Commander в [Electron](http://electron.atom.io/) (который раньше назывался `Atom Shell`).

**Comment by coderaiser** [comment]
Если нужен включенный `node-integration`, можно подключить [preload](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions) таким образом:
```js
mainWindow = new BrowserWindow({
  width: 800,
  height: 600,
  webPreferences: {
    preload: __dirname + '/preload.js'
  }
});
```
В `preload.js` удалить переменные связанные с `module`, `module.exports` (согласно [документации electron](https://github.com/electron/electron/blob/master/docs/faq/electron-faq.md#i-can-not-use-jqueryrequirejsmeteorangularjs-in-electron):
```js
window.nodeRequire = require;
delete window.require;
delete window.exports;
delete window.module;
```
либо подключить все используемые модули, через `require` и сохранить их в `global scope`:
```js
require('module').globalPaths.push(__dirname + '/node_modules');
try {
window.exec = require('execon');
window.Util = require('cloudcmd/lib/util');
window.CloudFunc = require('cloudcmd/lib/cloudfunc');
window.input = require('cloudcmd/lib/client/input');
[
  'rendy',
  'smalltalk'
].forEach((name) => {
  window[name] = require(`cloudcmd/modules/${name}`);
});

window.rendy = require('cloudcmd/modules/rendy');
window.smalltalk = require('cloudcmd/modules/smalltalk');
window.$ = window.jQuery = require('cloudcmd/modules/jquery/dist/jquery.min');
window.join = require('join-io/www/join');
window.load = require('console-io/modules/load/load');
window.skipfirst = require('console-io/modules/skipfirst/lib/skipfirst');

[
  'edward',
  'dword',
  'spero',
  'remedy',
  'ishtar'
].forEach((name) => {
    window[name] = require(`${name}/lib/client`);
});
} catch(error) {
  alert(error);
}
```

**Comment by zkochan** [comment]
I would love to try cloud commander as a substitution of total commander, is there a separate project that can install an electron version of cloud commander? If not, Is it documented somewhere how to do it manually?

(you can answer in Russian or Ukrainian if you wish. I speak those languages)

**Comment by coderaiser** [comment]
@zkochan no there is no such project, but you can use https://github.com/cloudcmd/atom as start point.
