### ISSUE TITLE
documents preview

### ISSUE THREAD

**Issue by aeifn** [coderaiser/cloudcmd#68]
Do you plan to include in distribution something like [ViewerJS](http://viewerjs.org/) to make it possible to preview DOC, ODT, PDF etc. documents (as it is made in midnight commander throught filters)?

**Comment by coderaiser** [comment]
It could be a good idea. Feel free to make PR.

**Comment by aeifn** [comment]
Для подобных расширений предусмотрен программный интерфейс или поведение полностью зашито в код?

**Comment by coderaiser** [comment]
По `<shift> + <f3>` в  [key](https://github.com/coderaiser/cloudcmd/blob/db4323427b5e255d555a85cbe5e425a3ba4bac5f/lib/client/key.js#L282) запускается просмотрщик из модуля [markdown](https://github.com/coderaiser/cloudcmd/blob/db4323427b5e255d555a85cbe5e425a3ba4bac5f/lib/client/markdown.js), который использует [view](https://github.com/coderaiser/cloudcmd/blob/db4323427b5e255d555a85cbe5e425a3ba4bac5f/lib/client/view.js), основанный на [fancybox](http://fancyapps.com/fancybox/).

В принципе, модуль `markdown` может быть переименован в `document`, который будет смотреть на расширение файла и использовать либо серверный рендеринг маркдауна либо `ViewerJS`.

Вас интересует только `pdf` или `odf` так же? Возможно имеет смысл использовать напрямую библиотеки [pdf.js](http://mozilla.github.io/pdf.js/) и [odf](http://webodf.org/), что бы не менять кардинально интерфейс. О поддержке `doc` на сайте `ViewerJS` не говорится, а лично я вижу `odf` впервые. Вы используете этот формат?

**Comment by coderaiser** [comment]
Closed due to long time of inactivity.

**Comment by coderaiser** [comment]
Landed `pdf` support in [Cloud Commander v13.4.0](https://github.com/coderaiser/cloudcmd/releases/tag/v13.4.0) 🎉

**Comment by coderaiser** [comment]
> Для подобных расширений предусмотрен программный интерфейс или поведение полностью зашито в код?

Подобные расширения могут быть реализованы с помощью [User Menu](https://github.com/coderaiser/cloudcmd/releases/tag/v12.2.0), в [Cookbook](https://github.com/coderaiser/cloudcmd/wiki/User-Menu-Cookbook) можно ознакомится с примерами использования `User Menu`.
