### ISSUE TITLE
Can't download beyond 1GB

### ISSUE THREAD

**Issue by Issam2204** [coderaiser/cloudcmd#69]
When I try to download a file bigger than 1 GB, owncloud stops at 1GB exactly.

Example: File size is 3,2 GB. Download starts and finishes after downloading 1GB.

**Comment by coderaiser** [comment]
`Cloud Commander` doesn't provide such feature as upload to `owncloud`. What did you do to achieve the goal?

**Comment by Issam2204** [comment]
I've no idea why I wrote "owncloud". Apologies.

What I mean is: When I try to download a file bigger than 1 GB, the **download** stops at 1GB exactly.

Sorry again for the confusion.

**Comment by coderaiser** [comment]
Could you tell me please what version are you use and what browser?
I just downloaded 1,3 GB via `wget` everything looks good.

**Comment by Issam2204** [comment]
Cloud Commander v5.4.1, Browser: latest stable chrome on Ubuntu Linux 14.04 64 bit.

I re-tried to download a file (3,2 GB size) and this time it has downloaded 1,1GB. To download a file I use the option provided from the right click:

![image](https://cloud.githubusercontent.com/assets/8282518/15865356/b824525a-2cda-11e6-9922-12f2b73b316e.png)

**Comment by coderaiser** [comment]
OK, one more important thing, what version of `node` are you use?

**Comment by Issam2204** [comment]
My version of node is 0.10.40

**Comment by coderaiser** [comment]
It is pretty old version actually. Could you please upgrade to [last stable version](https://nodejs.org/en/) (it is `v6.2.1` for now). You can use [nvm](https://github.com/creationix/nvm) for this purpose.

**Comment by Issam2204** [comment]
Yes, I'll update today and let you know if this was the actual issue. Thank you for the help so far!

**Comment by coderaiser** [comment]
Closed due to long time of inactivity.
