### ISSUE TITLE
как использовать auth авторизацию

### ISSUE THREAD

**Issue by sergeydurov** [coderaiser/cloudcmd#72]
В конфиге пишу
```
    "auth"              : true,    
    "username"          : "root",   
    "password"          : "my_password",   
    "algo"              : "sha512WithRSAEncryption", 
...
```
В браузере ввожу юзера и пароль - говорит не верный пароль.
Спасибо.

* **Version** (`cloudcmd -v`): 
* **Node Version** `node -v`: 
* **OS** (`uname -a` on Linux): 
* **Browser name/version**:

**Comment by coderaiser** [comment]
Пароль в файле `~/.cloudcmd.json` хранится в зашифрованном виде, шифруется он алгоритмом, указанным в поле `algo`, по-умолчанию это: `sha512WithRSAEncryption`.

Для того, что бы установить пароль лучше воспользоваться командой:

```sh
cloudcmd --username hello --password world
```

Для пользователя `hello` с паролем `world`. Изменения будут действовать одну сессию, до выхода из `Cloud Commander`. Для сохранения данных авторизации, без запуска файлового менеджера можно воспользоваться следующей командой:

```sh
cloudcmd --auth --username hello --password world --save --no-server

```
