### ISSUE TITLE
Cannot extract compressed archives.

### ISSUE THREAD

**Issue by wernight** [coderaiser/cloudcmd#79]
* **Version** (`cloudcmd -v`): v5.7.0 (Dockerized version)
* **OS**: Windows
* **Browser name/version**: Chrome

Uploaded a 7z, zip, tar, and none can be extracted using a right click > extract. Tried however using the terminal from cloudcmd and it worked (for the tar at least). Also it didn't show any error.

**Comment by coderaiser** [comment]
`Cloud Commander` uses [jaguar](https://github.com/coderaiser/node-jaguar), so only `.tar.gz` supported for now. I tried to add `zip` format with help of [yazl](https://github.com/thejoshwolfe/yazl), but [they are unsuccessful for now](https://github.com/thejoshwolfe/yazl/pull/26). Feel free to make pull request.

**Comment by wernight** [comment]
Would be nice to show an error message indicating the format isn't supported with a list of supported ones.

If calling a shell script is possible, it could fall back to `tar -xf "filename"` which should work as long as the filename contains the right extension.

**Comment by coderaiser** [comment]
Thank you, I'll think about it.
