### ISSUE TITLE
Cannot download a files containing #

### ISSUE THREAD

**Issue by wernight** [coderaiser/cloudcmd#80]
- **Version** (`cloudcmd -v`): v5.7.0 (Dockerized version)
- **OS**: Windows
- **Browser name/version**: Chrome

If a file contains `#` in its name, drag & drop of that file to the local file explorer will fail: Browser says cannot find the file.

My guess is that `#` is not escaped which leads to probably other filenames other that are not working.

**Comment by coderaiser** [comment]
> It is worth noting that the part after the #, also known as fragment identifier, is never sent to the server with the request.

[Identifying resources on the Web](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Identifying_resources_on_the_Web#Fragment).

The only way out from this situation is avoid such names, unfortunately. Have no idea how to fix this. Do you have some? Can you tell my why you need such file names?

**Comment by coderaiser** [comment]
Looks like it related to https://github.com/coderaiser/cloudcmd/issues/17.

**Comment by coderaiser** [comment]
Fixed with 47b12bb.

**Comment by coderaiser** [comment]
Landed in [v5.7.2](https://github.com/coderaiser/cloudcmd/releases/tag/v5.7.2).

**Comment by wernight** [comment]
Look like a good fix, but should it also escape other characters like `?`, `%`, etc? Sounds like it should URL-escape the string.

**Comment by machuu** [comment]
Downloading a file with a hash is breaking in the latest Docker image.

I think `.replace(/#/g, '%23')` needs to happen when setting `encodedPath` in `client/modules/menu.js`. In fact, `path` doesn't need to be encoded at all.

Here's what I'm seeing:

- filename is `"filename_with_#"`
- `.replace(/#/g, '%23')` converts `#` -> `%23`
    - `path="filename_with_%23"`
- `encodeURI(path)` converts `%` -> `%25`
    - `encodedPath="filename_with_%2523"`

Using the Chrome Dev Tools, I can successfully download the test file by:

1. Pause after `encodedPath` is set on line `menu.js:321`
2. Edit `encodedPath`, `filename_with_%2523` -> `filename_with_%23`
3. Edit `path`, `filename_with_%23` -> `filename_with_#`
4. Continue Script Execution
5. File `filename_with_#` successfully downloads

I've sent a Pull Request with a fix that works after editing `main.js` in my docker container.

**Comment by coderaiser** [comment]
Thank you :). Landed in [v9.1.4](https://github.com/coderaiser/cloudcmd/releases/tag/v9.1.4)
