### ISSUE TITLE
Default PWD should be the defined root

### ISSUE THREAD

**Issue by wernight** [coderaiser/cloudcmd#82]
* **Version** (`cloudcmd -v`): 5.7.2

When starting a shell from cloudcmd, I'd suggest the working directory to be the one set in cloudcmd as root. For example if `--root=/drive_c` it should start with `$PWD` == `/drive_c`.

I guess adding:

    var process = require('process');
    process.chdir(root);

in https://github.com/coderaiser/cloudcmd/blob/master/lib/server/repl.js would work.

**Comment by coderaiser** [comment]
Actually current directory in `console` is directory `Cloud Commander` started from. It is not a problem to change it after startup. But how do you suggest to disallow changing this directory from `console`?

**Comment by wernight** [comment]
I didn't mean it as a `chroot` (even though that might be possible). I just meant to make it more consistent. For example if I start the shell it may be to mass rename files, or extract some zip... and for that I just expect the current directory to be the one I'm looking at.

Actually it may be better if it were the current directory shown in cloudcmd.

**Comment by coderaiser** [comment]
It is a great idea. But I have no time for this unfortunately. Feel free to make pull request.

**Comment by wernight** [comment]
Why close it?

**Comment by coderaiser** [comment]
You have something to add?

**Comment by wernight** [comment]
If you think also it's good, why not keep it as a reference for possible improvements?

**Comment by coderaiser** [comment]
No need for this issue to be opened. In the near future is not expected work on this. We can proceed in your (or someone else) pull request. If something will change (or If I'll get idea how to do it right and implement it) I'll write about it here.

Anyway you can look into [console](https://github.com/cloudcmd/console), maybe you will have some ideas: just keep in mind `console` know nothing about `Cloud Commander`, but `Cloud Commander` can work with console via [api](https://github.com/cloudcmd/console#client-api). So changes should be done there, and they should be compatible with `Windows`, `Linux` and `Mac OS`.
