### ISSUE TITLE
ssl connection

### ISSUE THREAD

**Issue by muralikodali** [coderaiser/cloudcmd#83]
this programme is simply nice and practical.but we need to make secure connection (ssl),
when we connect from outside.
there is no sslPort option available in config file as mentioned in http://cloudcmd.io/#.
if we add sslPort to config, it is not recognised.
when we add sslPort option manually, it is giving following output:
**cloudcmd --port: should be a number**
###

**Comment by coderaiser** [comment]
@muralikodali you have a couple options for using `ssl`:
- use proxy server like `nginx` with such config (as mentioned at [cloudcmd.io](https://cloudcmd.io)):

```
server {
    listen 443;
    client_max_body_size 100m;
    ssl                  on;
    ssl_certificate      /home/coderaiser/cloudcmd/ssl/ssl.crt;
    ssl_certificate_key  /home/coderaiser/cloudcmd/ssl/ssl.key;
    server_name io.cloudcmd.io;
    access_log /var/log/nginx/io.cloudcmd.io.access.log;
    location / {
        proxy_pass    http://127.0.0.1:8000/;
    }
}
```

- use `Cloud Commander` as middleware with built in [https](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener) module:

```js
const https = require('https');
const cloudcmd = require('cloudcmd');
const express = require('express');
const io = require('socket.io');

const app = express();
const PORT = 1337;
const PREFIX = '/cloudcmd';
    
const options = {
    key: fs.readFileSync('test/fixtures/keys/agent2-key.pem'),
    cert: fs.readFileSync('test/fixtures/keys/agent2-cert.pem')
};

const server = https.createServer(options, app);
const socket = io.listen(server, {
    path: PREFIX + '/socket.io'
});

const config = {
    prefix: PREFIX /* base URL or function which returns base URL (optional)   */
};


app.use(cloudcmd({
    config,     /* config data (optional) */
    socket,     /* used by Config, Edit (optional) and Console (required)   */
}));

server.listen(PORT);
```

By the way, with [letsencrypt](https://letsencrypt.org/) you can get free ssl certificates.
