### ISSUE TITLE
Path by query string? 

### ISSUE THREAD

**Issue by johntdyer** [coderaiser/cloudcmd#85]
Is it possible to point to a particular file ( and path ) by query string ?  I would like to link directly to editing a particular file if possible

**Comment by coderaiser** [comment]
Yes there is such undocumented experimental feature, you can try it using [v5.7.5](https://github.com/coderaiser/cloudcmd/releases/tag/v5.7.5) with:

```
http://localhost:8000/#<module>/<file>
```
For example to view file `hello.txt` you can use:
```
http://localhost:8000/#view/edit.txt
```

To edit file `world.txt` you can use:

```
http://localhost:8000/#edit/edit.txt
```

**Comment by ICDeadPpl** [comment]
I know it's possible to have the path in a query string like this: 
`http://myserver:8000/fs/user/Downloads/`

I'd like to know if it would be feasible to have the option to populate the left and right panel with a query string like this? (just an example):
`http://myserver:8000?left=/fs/user/Downloads/&right=/fs/user/Stuff/`

**Comment by coderaiser** [comment]
It is an interesting idea, to implement this a feature couple things should be done:
- handling of query params in [server/route](https://github.com/coderaiser/cloudcmd/blob/v10.0.3/server/route.js#L147)
- query params add to `url` in [client/client.js](https://github.com/coderaiser/cloudcmd/blob/v10.0.3/client/client.js#L100)

Why do you need this?

**Comment by ICDeadPpl** [comment]
It's mainly for convenience. Most times I use the same paths for copy/move operations.
The source path I can supply via the bookmarked URL, but the destination path requires me to locate the destination in the other panel.
Maybe a bookmark system for folders, like in Krusader and Total Commander, would be an alternative.
