### ISSUE TITLE
Allow packing ZIPs instead of Tarballs when Downloading Folders

### ISSUE THREAD

**Issue by vostok4** [coderaiser/cloudcmd#87]
It would be awesome if we can download ZIPs instead of Tarballs (.tar.gz), ZIP is a bit more convenient for many other tools locally.

Exposed as an option would be cool so that users still have choice.

Thanks for the awesome software.

**Comment by coderaiser** [comment]
This can be done with help of [onezip](github.com/coderaiser/node-tar-to-zip). This [rest.js](   https://github.com/coderaiser/cloudcmd/blob/master/lib/server/rest.js#L275] should contain check:

```
config('packType') === 'zip'
```

And use one of 2 packers: `onezip` or [jaguar](https://github.com/coderaiser/node-jaguar).

One more thing that is missing is [ishtar](https://github.com/coderaiser/node-ishtar) for `zip` files. With this `zip` could be used all around `Cloud Commander`.

Could you please tell me your `OS` and `node.js` version.

**Comment by vostok4** [comment]
OS = Archlinux
Node.js = v6.9.1 (lts-boron)

This would be awesome.

**Comment by coderaiser** [comment]
Related to #79.

**Comment by coderaiser** [comment]
Added support of `zip` archives wiht help of [salam](http://github.com/coderaiser/node-salam) via
`--packer` option with 689dd03. Landed in [v5.10.0](https://github.com/coderaiser/cloudcmd/releases/tag/v5.10.0).
