### ISSUE TITLE
creating users and logout

### ISSUE THREAD

**Issue by unixph** [coderaiser/cloudcmd#88]
Is there a way to create multiple users to access the cloud commander?
If I want to log out, how can I do this?
Thanks.

**Comment by coderaiser** [comment]
> Is there a way to create multiple users to access the cloud commander?

There is no such a way to create multiple users, only one. But you can handle it using
`Cloud Commander` as a middleware.

> If I want to log out, how can I do this?

With right click of a mouse you can show `context menu` and at the bottom find item: `Log Out`.
