### ISSUE TITLE
Make a file/directory public

### ISSUE THREAD

**Issue by qazs** [coderaiser/cloudcmd#91]
Is there a way to make a file/directory public while in auth mode?

* **Cloud Commander v5.10.1** (`cloudcmd -v`): 
* **v7.1.0** `node -v`: 
* **Browser name/version**:

**Comment by coderaiser** [comment]
There is no such a way, but you can upload file to any cloud storage like `dropbox` or `google drive` and share it from there. Or set `root` to some directory and disable [config](https://github.com/coderaiser/cloudcmd/releases/tag/v5.8.0) and [console](https://github.com/coderaiser/cloudcmd/releases/tag/v5.9.0).
