### ISSUE TITLE
Is there any file_size_limit option for uploading.

### ISSUE THREAD

**Issue by vingorius** [coderaiser/cloudcmd#95]
* **Version** (`cloudcmd -v`): cloudcmd@5.10.1
* **Node Version** `node -v`: v4.3.0
* **OS** (`uname -a` on Linux): Ubuntu 16.04 kernel : 4.4.0-53-generic
* **Browser name/version**: Firefox 50.2 on Windows 10

I tried to upload 2Gb file on local ethernet(100Mbps), it failed on 1.3GB.
Is there any upload file size limit ?

**Comment by coderaiser** [comment]
No there is no any `upload_file_size_limit`. Could you please show me which error did you have?

**Comment by vingorius** [comment]
I runed cloudcmd as "Using as Middleware" on your document(http://cloudcmd.io).
When upload a 2.6 Gb file, it stop at 25%.
There's no error on server. In client browser(Firfox 50.2), no more progress on 25%.

- Image-01 : Console View

![01](https://cloud.githubusercontent.com/assets/5274928/21208262/6c2b0184-c2b0-11e6-820f-bffafccb37df.PNG)

- Image-02 : Debug View

![02](https://cloud.githubusercontent.com/assets/5274928/21208266/7010388c-c2b0-11e6-98ac-a1e638e291e1.PNG)

**Comment by coderaiser** [comment]
It is realy strange, can you show me server output? Do you have enaugh space on your hard drive?

**Comment by vingorius** [comment]
There's no server side error, only client.

**Comment by coderaiser** [comment]
Can't reproduce it. Just uploaded `2.18gb`, `6.52gb` files. Could you try other environment, or other files?

**Comment by coderaiser** [comment]
Closed due to inability to reproduce.
