### ISSUE TITLE
html-dialogs listed in help but not accepted

### ISSUE THREAD

**Issue by pikkewyn** [coderaiser/cloudcmd#97]
* **Version** (`cloudcmd -v`): v5.11.1
* **Node Version** `node -v`: v4.2.6
* **OS** (`uname -a` on Linux): Linux annabelle 2.6.32-32-pve #1 SMP Thu Aug 21 08:50:19 CEST 2014 i686 i686 i386 GNU/Linux
* **Browser name/version**: Mozilla Firefox 50.0

$ cloudcmd --html-dialogs
'--html-dialogs' is not a cloudcmd option. See 'cloudcmd --help'.

$ cloudcmd --help
Usage: cloudcmd [options]
Options:
  -h, --help                  display this help and exit
  -v, --version               display version and exit
  -s, --save                  save configuration
  -o, --online                load scripts from remote servers
  -a, --auth                  enable authorization
  -u, --username              set username
  -p, --password              set password
  -c, --config                configuration file path
  --editor                    set editor: "dword", "edward" or "deepword"
  --packer                    set packer: "tar" or "zip"
  --root                      set root directory
  --prefix                    set url prefix
  --port                      set port number
  --minify                    enable minification
  --progress                  show progress of file operations
  --html-dialogs              use html dialogs
  --one-panel-mode            set one panel mode
  --config-dialog             enable config dialog
  --console                   enable console
  --open                      open web browser when server started
  --no-server                 do not start server
  --no-auth                   disable authorization
  --no-online                 load scripts from local server
  --no-open                   do not open web browser when server started
  --no-minify                 disable minification
  --no-progress               do not show progress of file operations
  --no-html-dialogs           do not use html dialogs
  --no-one-panel-mode         unset one panel mode
  --no-config-dialog          disable config dialog
  --no-console                disable console

**Comment by coderaiser** [comment]
Landed in [v5.12.0](https://github.com/coderaiser/cloudcmd/releases/tag/v5.12.0).
