### ISSUE TITLE
Missing line number in invalid config parsing

### ISSUE THREAD

**Issue by pikkewyn** [coderaiser/cloudcmd#98]
`
cloudcmd 
cloudcmd --config ~/.cloudcmd.json: Unexpected token /
url: http://localhost:8000/
`

This happens with sample config from manual, but the real problem is missing line number.

* **Version** (`cloudcmd -v`): v5.11.1
* **Node Version** `node -v`: v4.2.6
* **OS** (`uname -a` on Linux): Linux annabelle 2.6.32-32-pve #1 SMP Thu Aug 21 08:50:19 CEST 2014 i686 i686 i386 GNU/Linux
* **Browser name/version**: Mozilla Firefox 50.0

**Comment by coderaiser** [comment]
The thing is `json` format doesn't support comments. In manual they used to better describe what option can be used for. I'll think about line numbers. It is a good idea for a pull request, actually :).
