### ISSUE TITLE
Unable to disable console

### ISSUE THREAD

**Issue by pikkewyn** [coderaiser/cloudcmd#99]
* **Version** (`cloudcmd -v`): v5.11.1
* **Node Version** `node -v`: v4.2.6
* **OS** (`uname -a` on Linux): Linux annabelle 2.6.32-32-pve #1 SMP Thu Aug 21 08:50:19 CEST 2014 i686 i686 i386 GNU/Linux 
* **Browser name/version**: Mozilla Firefox 50.0
Setting: 
`  "console": false `
in config file neither hides nor deactivates console button, while for instance setting
` "showKeysPanel": true`
works like a charm.

**Comment by coderaiser** [comment]
Landed in [v5.12.3](https://github.com/coderaiser/cloudcmd/releases/tag/v5.12.3).
